/* eslint-disable */
// Generated by Wrangler by running `wrangler types cloudflare-env.d.ts --config wrangler.jsonc --include-runtime false --strict-vars false` (hash: b397f2b12bc41432ca18a0e092aa5e31)
interface __BaseEnv_Env {
	BUCKET: R2Bucket;
	DB: D1Database;
	SITE_ORIGIN: string;
	REVIEW_MODERATOR_EMAIL: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./build/cloudflare-worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SITE_ORIGIN" | "REVIEW_MODERATOR_EMAIL">> {}
}
