import {getAdminUser} from "@/app/auth";
import {storage,moderatorEmail} from "@/db/storage";
import {listWorkshops,validateProfile,profileColumns,profileValues} from "@/db/directory";
import {json,sameOrigin,readJson} from "@/lib/http";
export const dynamic="force-dynamic";
export async function GET(request:Request){try{const admin=new URL(request.url).searchParams.get("admin")==="1";if(admin){const user=await getAdminUser();if(!user)return json({error:"Bitte melde dich an."},401);if(!user.isModerator)return json({error:"Kein Zugriff auf die Verwaltung."},403);}return json({workshops:await listWorkshops(admin)});}catch(e){console.error("directory-read",e);return json({error:"Die Werkstattdaten sind gerade nicht verfügbar. Bitte versuche es erneut."},503);}}
export async function POST(request:Request){return save(request,false);}
export async function PATCH(request:Request){return save(request,true);}
async function save(request:Request,update:boolean){const user=await getAdminUser();if(!user)return json({error:"Bitte melde dich an."},401);if(!user.isModerator)return json({error:"Kein Zugriff auf die Verwaltung."},403);if(!sameOrigin(request))return json({error:"Ungültige Anfrage."},403);let body:Record<string,unknown>;try{body=await readJson(request);}catch{return json({error:"Ungültige Eingaben."},400);}let profile;try{const id=update?String(body.id??""):String(body.id??crypto.randomUUID());if(!/^[a-z0-9][a-z0-9-]{2,80}$/.test(id))return json({error:"Ungültige Profilkennung."},400);profile=validateProfile(body,id);}catch(e){return json({error:e instanceof Error?e.message:"Bitte prüfe die Eingaben."},400);}try{const {db}=storage();if(update){const fields=profileColumns.slice(1);const values=profileValues(profile).slice(1);const r=await db.prepare(`UPDATE workshops SET ${fields.map(x=>`${x}=?`).join(",")} WHERE id=? AND updated_at=?`).bind(...values,profile.id,String(body.previousUpdatedAt??"")).run();if(!r.meta.changes)return json({error:"Das Profil wurde zwischenzeitlich geändert. Lade die Liste neu und prüfe deine Änderungen."},409);}else{await db.prepare(`INSERT INTO workshops (${profileColumns.join(",")}) VALUES (${profileColumns.map(()=>"?").join(",")})`).bind(...profileValues(profile)).run();}return json({id:profile.id},update?200:201);}catch(e){console.error("directory-save",e);return json({error:"Speichern fehlgeschlagen. Deine Eingaben bleiben erhalten."},503);}}
