"use client";
import {useNavigationGuard} from "@/lib/i18n/navigation-guard";
import {LocaleAnchor} from "@/components/locale-anchor";
import {useEffect,useState,type FormEvent} from "react";
import {ShieldCheck,LoaderCircle} from "lucide-react";
import {SiteHeader} from "@/components/site-header";
import {AdminNavigation} from "@/components/admin-navigation";
import type {AccountIdentity} from "@/components/account-storage-notice";
import {Checkbox} from "@/components/ui/checkbox";
import {Switch} from "@/components/ui/switch";
import {confirmationEmailSubject,confirmationEmailTemplate,recoveryEmailSubject,recoveryEmailTemplate} from "@/lib/auth/email-templates";
export default function AuthSetup({account}:{account:AccountIdentity}){const [url,setUrl]=useState(""),[key,setKey]=useState(""),[enabled,setEnabled]=useState(false),[mail,setMail]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const [dirty,setDirty]=useState(false);useNavigationGuard({busy,dirty});
 useEffect(()=>{const c=new AbortController();fetch("/api/auth-settings",{signal:c.signal}).then(async r=>{const d=await r.json() as {config:{projectUrl:string;publicKey:string;enabled:boolean;emailDeliveryConfirmed:boolean}|null;error?:string};if(!r.ok)throw Error(d.error);if(d.config){setUrl(d.config.projectUrl);setKey(d.config.publicKey);setEnabled(d.config.enabled);setMail(d.config.emailDeliveryConfirmed);}}).catch(e=>{if(e.name!=="AbortError")setError(e.message);}).finally(()=>setLoading(false));return()=>c.abort();},[]);
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setError("");setMessage("");try{const r=await fetch("/api/auth-settings",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({projectUrl:url,publicKey:key,enabled,emailDeliveryConfirmed:mail})});const d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error);setDirty(false);setMessage(enabled?mail?"Kundenanmeldung aktiviert. Teste E-Mail-Anmeldung und alle verbundenen Anbieter.":"Verfügbare Anmeldeanbieter und die vom Anbieter freigegebene Registrierung aktiviert. Die Passwort-Wiederherstellung bleibt bis zum erfolgreichen Versandtest geschlossen.":"Die Verbindung ist als Entwurf gespeichert. Der bisherige Zugang bleibt verfügbar.");}catch(e){setError(e instanceof Error?e.message:"Speichern fehlgeschlagen.");}finally{setBusy(false);}}
 return <><SiteHeader account={account} isAdmin/><AdminNavigation active="login"/><main className="auth-setup-page wrap"><div className="section-heading"><h1>Anmeldung verbinden.</h1><p>Google und E-Mail über Supabase einrichten.</p></div><div className="auth-setup-layout"><section className="setup-instructions" aria-labelledby="setup-instructions-heading">
 <h2 id="setup-instructions-heading">Einrichtung prüfen</h2>
 <p>Nutze das bestehende Supabase-Projekt. Bereits eingerichtete und getestete Einstellungen bleiben erhalten; ergänze nur fehlende Schritte.</p>
 <ol className="setup-steps">
  <li><h3>Projekt wählen</h3><p>Im <LocaleAnchor href="https://supabase.com/dashboard" target="_blank" rel="noopener noreferrer">Supabase-Projekt</LocaleAnchor> E-Mail/Passwort, Registrierung und E-Mail-Bestätigung prüfen. Ein neues Projekt ist nur bei Bedarf nötig.</p></li>
  <li><h3>Website und E-Mails</h3><p>Site URL und Callback prüfen. Für E-Mails eigenen SMTP-Versand und die Riparim-Vorlagen verwenden.</p>
   <details><summary>URLs, SMTP und Mailvorlagen</summary><div className="setup-help">
    <p>Unter Authentication → URL Configuration als Site URL <strong>https://riparim.com</strong> ohne abschließenden Slash eintragen. Nur den App-Callback <strong>https://riparim.com/auth/bestaetigen\?**</strong> erlauben; vorhandene benötigte Freigaben erhalten.</p>
    <p>Unter Authentication → SMTP Settings den eigenen SMTP-Dienst verbinden oder die bestehende Einrichtung beibehalten. Der Standardversand ist kein produktiver Versanddienst für externe Kunden. Bei neuen Free-Projekten schaltet eigener SMTP-Versand auch die Vorlagenbearbeitung frei.</p>
    <LocaleAnchor href="https://supabase.com/docs/guides/auth/auth-smtp" target="_blank" rel="noopener noreferrer">Offizielle Anleitung zum E-Mail-Versand</LocaleAnchor>
    <p>Danach unter Authentication → Email Templates jeweils <strong>Betreff und HTML-Body gemeinsam</strong> übernehmen: „Confirm sign up“ für die Bestätigung, „Reset password“ für die Wiederherstellung. Die Vorlagen erhalten Sprache, Token-Hash und Rücksprungziel.</p>
    <details><summary>E-Mail-Bestätigung</summary><h4>Betreff</h4><pre tabIndex={0} aria-label="Betreff für E-Mail-Bestätigung">{confirmationEmailSubject}</pre><h4>HTML-Body</h4><pre tabIndex={0} aria-label="HTML für E-Mail-Bestätigung">{confirmationEmailTemplate}</pre></details>
    <details><summary>Passwort-Wiederherstellung</summary><h4>Betreff</h4><pre tabIndex={0} aria-label="Betreff für Passwort-Wiederherstellung">{recoveryEmailSubject}</pre><h4>HTML-Body</h4><pre tabIndex={0} aria-label="HTML für Passwort-Wiederherstellung">{recoveryEmailTemplate}</pre></details>
    <LocaleAnchor href="https://supabase.com/docs/guides/auth/auth-email-templates" target="_blank" rel="noopener noreferrer">Offizielle Anleitung zu Mailvorlagen</LocaleAnchor>
   </div></details>
  </li>
  <li><h3>Versand testen</h3><p>Nach Änderungen Bestätigung und Passwort-Zurücksetzen mit einem eigenen Testkonto prüfen. Erst bei Erfolg den Versand rechts bestätigen.</p></li>
  <li><h3>Google verbinden</h3><p>Google bei Bedarf aktivieren; die Anmeldung funktioniert unabhängig vom E-Mail-Versand.</p>
   <details><summary>Google-Einstellungen</summary><div className="setup-help"><p>In Google einen OAuth-Web-Client verwenden: Website-Ursprung <strong>https://riparim.com</strong> und als Redirect-URI die Callback-Adresse aus dem Supabase-Google-Provider eintragen. Client-ID und Client-Secret dort hinterlegen und Google aktivieren. Bereits getestete Einstellungen beibehalten.</p><LocaleAnchor href="https://supabase.com/docs/guides/auth/social-login/auth-google" target="_blank" rel="noopener noreferrer">Anleitung für Google-Anmeldung</LocaleAnchor></div></details>
  </li>
 </ol>
 <div className="note"><ShieldCheck size={21}/><p>Bestehende Nachweise werden nur mit einem bestätigten bisherigen Zugang übernommen. Eine gleiche E-Mail-Adresse allein genügt nicht.</p></div>
 </section><form className="journey-form auth-settings-form" onChange={()=>setDirty(true)} onSubmit={save}><h2>Projekt verbinden</h2>{loading&&<p role="status" className="help">Konfiguration wird geladen …</p>}<label>Supabase-Projektadresse<input type="url" required value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://dein-projekt.supabase.co" autoComplete="off"/></label><label>Öffentlicher Publishable-Key<textarea required rows={3} value={key} onChange={e=>setKey(e.target.value)} placeholder="sb_publishable_…" autoComplete="off"/></label><p className="help">Ein öffentlicher Publishable- oder bisheriger Anon-Key genügt. Keinen Service-Role-Key oder Secret-Key eintragen.</p><label className="consent"><Checkbox checked={mail} onCheckedChange={v=>{setMail(v===true);setDirty(true);}} aria-label="Produktiven E-Mail-Versand bestätigen"/><span>Ich habe eigenen SMTP-Versand eingerichtet und Bestätigungs- sowie Wiederherstellungs-E-Mails erfolgreich getestet.</span></label><label className="activation-switch"><Switch checked={enabled} onCheckedChange={value=>{setEnabled(value);setDirty(true);}} aria-label="Kundenanmeldung aktivieren"/><span>Kundenanmeldung aktivieren</span></label>{error&&<p className="error" role="alert">{error}</p>}{message&&<p className="admin-feedback" role="status">{message}</p>}<button type="submit" className="primary" disabled={loading||busy}>{busy?<><LoaderCircle className="spin" size={17}/>Verbindung wird geprüft …</>:enabled?"Verbindung prüfen & aktivieren":"Verbindung als Entwurf speichern"}</button><div className="auth-preview-links"><LocaleAnchor href="/anmelden">Anmeldung ansehen</LocaleAnchor><LocaleAnchor href="/registrieren">Registrierung ansehen</LocaleAnchor><LocaleAnchor href="/passwort-vergessen">Passwort-Zurücksetzen ansehen</LocaleAnchor></div></form></div></main></>;
}
