import assert from 'node:assert/strict';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {createRequire} from 'node:module';
import {DatabaseSync} from 'node:sqlite';
const {build}=createRequire(new URL('../package.json',import.meta.url))('esbuild');
const output='.test-runtime/account-settings';
await mkdir(output,{recursive:true});
const bundle=await build({entryPoints:{account:'app/api/account/route.ts',grant:'lib/auth/deletion-grant.ts',visits:'app/api/visits/route.ts',proof:'lib/auth/password-proof.ts'},outdir:output,bundle:true,write:false,format:'esm',platform:'node',plugins:[{name:'account-boundaries',setup(b){
 b.onResolve({filter:/^(cloudflare:workers|@\/app\/auth|@\/lib\/auth\/(admin|client)|next\/headers|@\/db\/directory|@supabase\/supabase-js)$/},args=>({path:args.path,namespace:'fixture'}));
 b.onLoad({filter:/.*/,namespace:'fixture'},args=>({loader:'js',contents:
  args.path==='cloudflare:workers'?'export const env=globalThis.fixtureEnv;':
  args.path==='next/headers'?'export async function cookies(){return globalThis.fixtureCookies;} export async function headers(){return new Headers({host:"riparim.example.test"});}':
  args.path==='@/db/directory'?'export async function publishedWorkshop(){return {id:"fixture-workshop"};}':
  args.path==='@/app/auth'?'export async function getAppUser(){return globalThis.fixtureCurrent();} export async function getAdminUser(){return globalThis.fixtureCurrent();} export function ownsVisit(user,owner){return user.ownerKeys.includes(owner);} export function ownerPair(user){return [user.ownerKeys[0],user.ownerKeys[1]??user.ownerKeys[0]];} export function providerAccountId(url,id){return `supabase:${new URL(url).hostname}:${id}`;}':
  args.path==='@/lib/auth/admin'?'export async function getAuthAdmin(){return globalThis.fixtureAdmin;}':
  args.path==='@/lib/auth/client'?'export async function authClient(){return globalThis.fixtureClient;}':
  'export function createClient(...args){return globalThis.fixtureCreateClient(...args);}'
 }));
}}]});
for(const file of bundle.outputFiles)await writeFile(file.path.replace(/\.js$/,'.mjs'),file.contents);
const db=new DatabaseSync(':memory:');
for(const file of ['0000_handy_black_queen','0001_polite_killmonger','0002_exotic_slayback','0003_magenta_boom_boom','0004_ambiguous_morbius','0007_pink_tyrannus','0008_stormy_blazing_skull','0009_fine_sister_grimm','0010_handy_luminals','0011_funny_echo','0012_unique_wolfsbane'])db.exec(await readFile(`drizzle/${file}.sql`,'utf8'));
let beforeBatch=null,batchTail=Promise.resolve(),failDb=false;
const d1={prepare(sql){const s=db.prepare(sql);const adapter=(values=[])=>({bind:(...next)=>adapter(next),first:async()=>{if(failDb)throw Error('Fixture DB unavailable');return s.get(...values)??null;},all:async()=>({results:s.all(...values)}),run:async()=>({meta:s.run(...values)})});return adapter();},batch(statements){const result=batchTail.then(async()=>{if(beforeBatch){const fn=beforeBatch;beforeBatch=null;fn();}db.exec('BEGIN');try{const results=[];for(const statement of statements)results.push(await statement.run());db.exec('COMMIT');return results;}catch(e){db.exec('ROLLBACK');throw e;}});batchTail=result.catch(()=>{});return result;}};
const origin='https://riparim.example.test',projectUrl='https://fixture-project.supabase.co';
const id='00000000-0000-4000-8000-000000000001',otherId='00000000-0000-4000-8000-000000000002';
const accountId=(uid=id)=>`supabase:fixture-project.supabase.co:${uid}`;
let user={userId:accountId(),email:'member@example.test',provider:'E-Mail',displayName:'Fixture Member',ownerKeys:[accountId()],isModerator:false};
let providerUser={id,email:user.email,email_confirmed_at:'2026-10-04',user_metadata:{full_name:user.displayName,unrelated:'preserved'}};
const objects=new Map();let failBucket=false,failProvider=false,missingProvider=false,allowCurrent=true;
let reachedPut=null,releasePut=null;
const bucket={async put(key,bytes,options){if(options?.onlyIf&&reachedPut){reachedPut(key);await new Promise(resolve=>releasePut=resolve);}if(options?.onlyIf&&!objects.has(key))return null;objects.set(key,bytes??false);return {etag:key};},async head(key){return objects.has(key)?{key}:null;},async list({prefix,cursor}){if(failBucket)throw Error('Fixture R2 unavailable');const keys=[...objects.keys()].filter(key=>key.startsWith(prefix)&&(!cursor||key>cursor)).sort(),page=keys.slice(0,1);return {objects:page.map(key=>({key})),truncated:keys.length>page.length,cursor:page.at(-1)};},async delete(keys){if(failBucket)throw Error('Fixture R2 unavailable');for(const key of Array.isArray(keys)?keys:[keys])objects.delete(key);}};
globalThis.fixtureEnv={DB:d1,BUCKET:bucket,SITE_ORIGIN:origin,REVIEW_MODERATOR_EMAIL:'owner@example.test'};
globalThis.fixtureCurrent=()=>allowCurrent&&!db.prepare('SELECT account_id FROM auth_account_status WHERE account_id=?').get(user.userId)?user:null;
const cookieMap=new Map(),cookieOptions=new Map();
globalThis.fixtureCookies={get(name){const value=cookieMap.get(name);return value?{value}:undefined;},set(name,value,options){cookieOptions.set(name,options);if(options?.maxAge===0)cookieMap.delete(name);else cookieMap.set(name,value);}};
globalThis.fixtureClient={auth:{getUser:async()=>({data:{user:providerUser},error:null}),signOut:async()=>({error:null})}};
const writes=[];
const authAdmin={getUserById:async uid=>{assert.equal(uid,id,'Provider targets come from the authenticated identity');return missingProvider?{data:{user:null},error:{status:404,code:'user_not_found'}}:{data:{user:providerUser},error:failProvider?{status:503}:null};},updateUserById:async(uid,attributes)=>{writes.push({method:'update',uid,attributes});if(failProvider)return {data:{user:null},error:{status:503}};providerUser={...providerUser,user_metadata:attributes.user_metadata};return {data:{user:providerUser},error:null};},deleteUser:async uid=>{writes.push({method:'delete',uid});if(failProvider)return {error:{status:503}};missingProvider=true;return {error:null};}};
globalThis.fixtureAdmin={client:{auth:{admin:authAdmin}},projectUrl};
let proofUser=providerUser,proofError=false,proofUserError=false,proofCalls=0,proofSignouts=0,proofConfig=null;
globalThis.fixtureCreateClient=(...args)=>{proofConfig=args;return {auth:{signInWithPassword:async credentials=>{proofCalls++;assert.equal(credentials.email,user.email);return {data:{user:proofUser},error:proofError?{status:400}:null};},getUser:async()=>({data:{user:proofUser},error:proofUserError?{status:503}:null}),signOut:async options=>{assert.equal(options.scope,'local');proofSignouts++;return {error:null};}}};};
db.prepare("INSERT INTO auth_settings VALUES ('main',?,?,1,1,?)").run(projectUrl,'sb_publishable_fixture_key_12345678901234567890','2026-10-04');
const seed=()=>{db.prepare('DELETE FROM auth_account_status').run();db.prepare('DELETE FROM auth_account_deletions').run();db.prepare('DELETE FROM auth_account_roles').run();db.prepare('DELETE FROM auth_links').run();db.prepare('DELETE FROM auth_sessions').run();cookieMap.clear();missingProvider=false;user={...user,provider:'E-Mail',isModerator:false,email:'member@example.test',userId:accountId()};providerUser={...providerUser,id,email:user.email,email_confirmed_at:'2026-10-04'};proofUser=providerUser;allowCurrent=true;db.prepare('INSERT INTO auth_sessions (id,account_id,expires_at,created_at) VALUES (?,?,?,?)').run('fixture-current',accountId(),Date.now()+600000,'2026-10-04');};
seed();
const [account,grant]=await Promise.all(['account','grant'].map(file=>import(new URL(`../${output}/${file}.mjs`,import.meta.url))));
const request=(method,body,headers={})=>new Request(origin+'/api/account',{method,headers:{Origin:origin,'Content-Type':'application/json',...headers},body:JSON.stringify(body)});
const patch=body=>account.PATCH(request('PATCH',body)),confirm=body=>account.POST(request('POST',body)),remove=(body={confirmation:'KONTO LÖSCHEN'})=>account.DELETE(request('DELETE',body));
const grantRow=()=>db.prepare('SELECT * FROM auth_account_deletions WHERE account_id=?').get(accountId());
const status=()=>db.prepare('SELECT status FROM auth_account_status WHERE account_id=?').get(accountId())?.status;
let passed=0;const check=(condition,label)=>{assert(condition,label);passed++;};
let response=await account.GET(),data=await response.json();
check(data.account.email===user.email&&data.account.name===user.displayName&&!data.account.protected,'Only the verified current account is exposed');
check(!data.deletionReady&&!data.deletionStarted,'A normal session has no deletion permission');
check(response.headers.get('Cache-Control')==='no-store','Account responses are never cached');
allowCurrent=false;
check((await patch({name:'Another Name'})).status===401&&(await confirm({password:'fixture-password'})).status===401,'Anonymous name and proof requests are denied');
check((await remove()).status===401,'Deletion requires a separate verified identity grant');
allowCurrent=true;
for(const payload of [{name:'Another Name',id:otherId},{name:'Another Name',email:'other@example.test'},{name:'Another Name',role:'admin'},{name:'Another Name',active:true},{userId:otherId},{name:'x'},{name:'x'.repeat(81)},{name:1}])check((await patch(payload)).status===400,'Profile mutation rejects targets, authority fields and invalid names');
check(writes.length===0,'Invalid requests never write provider data');
check((await account.PATCH(request('PATCH',{name:'Another Name'},{Origin:'https://other.example.test'}))).status===400,'Cross-origin name changes are denied');
response=await patch({name:'  Another Name  '});data=await response.json();
check(response.ok&&data.name==='Another Name'&&writes.at(-1).uid===id,'Validated names update only the session identity');
check(writes.at(-1).attributes.user_metadata.unrelated==='preserved'&&Object.keys(writes.at(-1).attributes).length===1,'Name updates preserve unrelated profile metadata without writing identity or roles');
providerUser={...providerUser,id:otherId};check((await patch({name:'Other Name'})).status===401,'A mismatched verified provider subject fails closed');providerUser={...providerUser,id};
user={...user,provider:'ChatGPT'};check((await account.GET().then(r=>r.json())).account===null&&(await patch({name:'Another Name'})).status===401,'Native-only sessions cannot act on a Supabase account');user={...user,provider:'E-Mail'};
proofError=true;check((await confirm({password:'incorrect'})).status===401&&!grantRow(),'Incorrect passwords cannot authorize deletion');proofError=false;
proofUser={...providerUser,id:otherId};check((await confirm({password:'fixture-password'})).status===401&&!grantRow(),'Fresh proof for another subject cannot authorize this account');proofUser=providerUser;
proofUserError=true;check((await confirm({password:'fixture-password'})).status===401&&!grantRow(),'A failed server-side proof lookup cannot authorize deletion');proofUserError=false;
check((await confirm({password:'fixture-password',id:otherId})).status===400,'Reauthentication cannot choose a target');
response=await confirm({password:'fixture-password'});
check(response.ok&&grantRow(),'A fresh password proof creates a deletion-only grant');
check(proofCalls===proofSignouts&&proofConfig[2].auth.persistSession===false,'Proof sessions are isolated and locally signed out');
check(!grantRow().token_hash.includes(cookieMap.get('riparim-account-deletion'))&&grantRow().token_hash.length===64,'Only a hash of the deletion credential is stored');
check(cookieOptions.get('riparim-account-deletion').httpOnly&&cookieOptions.get('riparim-account-deletion').secure&&cookieOptions.get('riparim-account-deletion').sameSite==='strict','Deletion permission uses a protected same-site cookie');
check(db.prepare('SELECT revoked FROM auth_sessions').get().revoked===0,'Password confirmation does not revoke the enrolled browser session');
check((await account.GET().then(r=>r.json())).deletionReady,'A fresh proof is shown as ready for explicit confirmation');
for(const body of [{},{confirmation:'yes'},{confirmation:'KONTO LÖSCHEN',id:otherId}])check((await remove(body)).status===400&&!status(),'Deletion requires the exact confirmation and accepts no account target');
check((await account.DELETE(request('DELETE',{confirmation:'KONTO LÖSCHEN'},{Origin:'https://other.example.test'}))).status===400&&!status(),'Cross-origin deletion is denied');
db.prepare('UPDATE auth_account_deletions SET expires_at=0').run();check((await remove()).status===401&&!status(),'An expired identity proof cannot start deletion');
seed();user={...user,isModerator:true};check((await confirm({password:'fixture-password'})).status===403,'Admin sessions cannot create self-deletion grants');user={...user,isModerator:false,email:'owner@example.test'};providerUser={...providerUser,email:user.email};
check((await confirm({password:'fixture-password'})).status===403,'Bootstrap accounts are protected even without a moderator session flag');
seed();db.prepare("INSERT INTO auth_links (account_id,legacy_owner,owner_admin,created_at) VALUES (?, 'legacy-admin',1,'2026-10-04')").run(accountId());
check((await confirm({password:'fixture-password'})).status===403,'An administrative legacy linkage cannot be self-deleted');
seed();await confirm({password:'fixture-password'});
beforeBatch=()=>db.prepare("INSERT INTO auth_account_roles VALUES (?,'admin','2026-10-04','fixture-admin')").run(accountId());
check((await remove()).status===403&&!status(),'A promotion between authorization and commit prevents self-deletion');
seed();await confirm({password:'fixture-password'});
beforeBatch=()=>db.prepare('UPDATE auth_account_deletions SET token_hash=?').run('new-proof-hash');
check((await remove()).status===403&&!status(),'A rotated grant cannot be consumed after its earlier read');
seed();user={...user,provider:'Google'};
check((await confirm({password:'fixture-password'})).status===403,'Google sessions use the OAuth proof flow rather than password metadata');
await grant.issueDeletionGrant(user,projectUrl,id);
check((await account.GET().then(r=>r.json())).deletionReady,'A verified Google callback can issue the same scoped deletion grant');
seed();await confirm({password:'fixture-password'});
db.prepare("INSERT INTO auth_links (account_id,legacy_owner,created_at) VALUES (?,'legacy-member','2026-10-04')").run(accountId());
for(const owner of [accountId(),'legacy-member',accountId(otherId)]){
 db.prepare('INSERT INTO visits (id,owner,workshop,date,vehicle,service,evidence_type,display_name,status,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)').run('visit-'+owner,owner,'fixture-workshop','2026-10-04','Fixture Car','Repair','document','Original Public Name','approved','2026-10-04');
 objects.set(`evidence/${owner}/visit-${owner}/first.pdf`,true);objects.set(`evidence/${owner}/visit-${owner}/old.pdf`,true);objects.set(`evidence/${owner}/orphan/orphan.pdf`,true);
}
response=await patch({name:'Changed Name'});
check(response.ok&&db.prepare('SELECT display_name FROM visits WHERE owner=?').get(accountId()).display_name==='Original Public Name','Profile changes preserve published review display names');
failBucket=true;response=await remove();
check(response.status===503&&status()==='deleted'&&grantRow().started===1,'Storage failure preserves the access block and retry-only grant');
check(db.prepare('SELECT revoked FROM auth_sessions WHERE account_id=?').get(accountId()).revoked===1,'Deletion revokes the existing session before touching private files');
check(db.prepare('SELECT status FROM visits WHERE owner=?').get(accountId()).status==='deleting','Failed cleanup retains visit inventory for retry');
check(db.prepare('SELECT legacy_owner FROM auth_links WHERE account_id=?').get(accountId()),'Failed cleanup preserves confirmed ownership links');
data=await account.GET().then(r=>r.json());check(data.account===null&&data.deletionStarted,'A blocked account can see its scoped retry action without normal account access');
check((await patch({name:'Forbidden Name'})).status===401,'A blocked deletion grant cannot edit the account');
failBucket=false;failProvider=true;response=await remove();
check(response.status===503&&status()==='deleted'&&grantRow().started===1,'Provider lookup failure retains a repeatable deletion');
failProvider=false;
// Retry now fails at the final provider delete, after owned files are removed.
const originalDelete=authAdmin.deleteUser;authAdmin.deleteUser=async uid=>{writes.push({method:'delete',uid});return {error:{status:503}};};
response=await remove();
check(response.status===503&&db.prepare('SELECT COUNT(*) AS n FROM visits WHERE owner IN (?,?)').get(accountId(),'legacy-member').n===0,'Provider deletion failure occurs after local data cleanup');
check(db.prepare('SELECT legacy_owner FROM auth_links WHERE account_id=?').get(accountId())&&grantRow(),'Provider deletion failure retains link and grant for repeatable cleanup');
check([...objects.keys()].every(key=>key.startsWith(`evidence/${accountId(otherId)}/`)),'Paginated cleanup removes every owned version and orphan while preserving another account');
authAdmin.deleteUser=originalDelete;
response=await remove();check(response.ok&&missingProvider&&!grantRow(),'A blocked account can finish provider deletion through its scoped retry');
check(!cookieMap.has('riparim-account-deletion')&&!db.prepare('SELECT id FROM auth_sessions WHERE account_id=?').get(accountId()),'Completed deletion removes its grant cookie and local sessions');
check(!db.prepare('SELECT account_id FROM auth_links WHERE account_id=?').get(accountId()),'Completed deletion removes the verified ownership linkage');
check(db.prepare('SELECT status FROM auth_account_status WHERE account_id=?').get('legacy-member')?.status==='deleted','Legacy access remains blocked after its linkage is removed');
check((await remove()).status===401,'A completed grant cannot be reused');
seed();await confirm({password:'fixture-password'});await grant.startDeletion(await grant.readDeletionGrant());missingProvider=true;
check((await remove()).ok,'A provider account already deleted after an uncertain result is idempotently cleaned up');
seed();globalThis.fixtureAdmin=null;
check((await patch({name:'Name'})).status===503,'Missing server credentials cannot report a successful update');
globalThis.fixtureAdmin={client:{auth:{admin:authAdmin}},projectUrl};failDb=true;
check((await account.GET()).status===503,'Database failures fail closed without exposing an unverified account');failDb=false;
seed();for(let attempt=0;attempt<13;attempt++)response=await confirm({password:'incorrect'});
check(response.status===429,'Repeated proof attempts are rate limited by server-side identity');
seed();db.prepare('DELETE FROM auth_attempts').run();await confirm({password:'fixture-password'});
const visits=await import(new URL(`../${output}/visits.mjs`,import.meta.url));
const uploadId='00000000-0000-4000-8000-000000000010',form=new FormData();
for(const [key,value] of Object.entries({id:uploadId,workshop:'fixture-workshop',date:new Date().toISOString().slice(0,10),vehicle:'Fixture Car',service:'Inspektion & Wartung',evidenceType:'Rechnung',name:'Fixture Member',rating:'5',review:'A sufficiently detailed fictional account deletion regression review.',consent:'true'}))form.set(key,value);
form.set('file',new File(['%PDF-fixture'],'fixture.pdf',{type:'application/pdf'}));
const atPut=new Promise(resolve=>reachedPut=resolve);
const pendingUpload=visits.POST(new Request(origin+'/api/visits',{method:'POST',headers:{Origin:origin},body:form}));
const pendingKey=await atPut;
check(db.prepare('SELECT file_key FROM evidence_uploads WHERE file_key=?').get(pendingKey)&&objects.get(pendingKey)===false,'The upload has a durable empty reservation before private bytes can be stored');
response=await remove();
check(response.ok&&missingProvider&&!objects.has(pendingKey),'Deletion removes the reservation so a late conditional payload cannot write');
failBucket=true;releasePut();reachedPut=null;const uploadResponse=await pendingUpload;
check(uploadResponse.status===401&&!db.prepare('SELECT id FROM visits WHERE id=?').get(uploadId),'A late conditional upload cannot commit a visit after deletion starts');
check(!objects.has(pendingKey)&&db.prepare('SELECT file_key FROM evidence_uploads WHERE file_key=?').get(pendingKey),'Failed compensation retains cleanup inventory without writing any private late bytes');
failBucket=false;
check((await remove()).status===401,'Completed deletion grants remain consumed even if a stale upload needs housekeeping');
seed();db.prepare('DELETE FROM auth_attempts').run();await confirm({password:'fixture-password'});
const abandonedKey=`evidence/${accountId()}/abandoned/complete.pdf`;objects.set(abandonedKey,true);db.prepare('INSERT INTO evidence_uploads VALUES (?,?)').run(abandonedKey,accountId());
check((await remove()).ok&&!objects.has(abandonedKey),'An abandoned reservation with an object is safely recovered');
seed();db.prepare('DELETE FROM auth_attempts').run();await confirm({password:'fixture-password'});db.prepare('INSERT INTO evidence_uploads VALUES (?,?)').run(`evidence/${accountId()}/abandoned/missing`,accountId());
check((await remove()).ok,'An abandoned reservation with no object cannot permanently block deletion');
console.log(JSON.stringify({accountSettingsChecksPassed:passed,liveProviderTested:false,productionTouched:false}));
