import assert from 'node:assert/strict';
import {mkdir,readFile,readdir,writeFile} from 'node:fs/promises';
import {createRequire} from 'node:module';
import {DatabaseSync} from 'node:sqlite';
const {build}=createRequire(new URL('../package.json',import.meta.url))('esbuild');
const output='.test-runtime/business';await mkdir(output,{recursive:true});
const bundle=await build({entryPoints:{route:'app/api/business/route.ts',workshops:'app/api/workshops/route.ts',settings:'app/api/auth-settings/route.ts',directory:'db/directory.ts',cleanup:'lib/auth/delete-account.ts'},outdir:output,bundle:true,write:false,format:'esm',platform:'node',plugins:[{name:'business-boundaries',setup(b){b.onResolve({filter:/^(cloudflare:workers|@\/app\/auth|@\/db\/google-places)$/},args=>({path:args.path,namespace:'fixture'}));b.onLoad({filter:/.*/,namespace:'fixture'},args=>({loader:'js',contents:args.path==='cloudflare:workers'?'export const env=globalThis.fixtureEnv;':args.path==='@/app/auth'?'export async function getAppUser(){return globalThis.fixtureUser;} export async function getAdminUser(){return globalThis.fixtureUser;} export function ownerPair(user){return [user.ownerKeys[0],user.ownerKeys[1]??user.ownerKeys[0]];} export function providerAccountId(url,id){return `supabase:${new URL(url).hostname}:${id}`;}':'export async function confirmedPublicationPlace(...args){return globalThis.fixtureConfirmPlace(...args);}'}));}}]});
for(const file of bundle.outputFiles)await writeFile(file.path.replace(/\.js$/,'.mjs'),file.contents);
const db=new DatabaseSync(':memory:');for(const file of (await readdir('drizzle')).filter(file=>file.endsWith('.sql')).sort())db.exec(await readFile('drizzle/'+file,'utf8'));
let beforeBatch=null,beforeRun=null,holdBatch=null,batchTail=Promise.resolve(),failDb=false;
const d1={prepare(sql){const statement=db.prepare(sql);const adapter=(values=[])=>({fixtureValues:values,bind:(...next)=>adapter(next),first:async()=>{if(failDb)throw Error('Fixture storage unavailable');return statement.get(...values)??null;},all:async()=>({results:statement.all(...values)}),run:async()=>{if(beforeRun)beforeRun(sql);return {meta:statement.run(...values)};}});return adapter();},batch(statements){const execute=()=>{const result=batchTail.then(async()=>{if(beforeBatch){const fn=beforeBatch;beforeBatch=null;fn();}db.exec('BEGIN');try{const results=[];for(const statement of statements)results.push(await statement.run());db.exec('COMMIT');return results;}catch(e){db.exec('ROLLBACK');throw e;}});batchTail=result.catch(()=>{});return result;};return holdBatch?holdBatch(statements,execute):execute();}};
const origin='https://riparim.example.test',projectUrl='https://fixture-project.supabase.co';
const aId='00000000-0000-4000-8000-000000000001',bId='00000000-0000-4000-8000-000000000002',cId='00000000-0000-4000-8000-000000000003';
const accountId=id=>`supabase:fixture-project.supabase.co:${id}`;
const user=(id,email,admin=false)=>({userId:accountId(id),email,displayName:'Fixture Member',ownerKeys:[accountId(id)],isModerator:admin,provider:'E-Mail'});
const actors={a:user(aId,'a@example.test'),b:user(bId,'b@example.test'),c:user(cId,'c@example.test'),admin:user('00000000-0000-4000-8000-000000000009','admin@example.test',true)};
globalThis.fixtureEnv={DB:d1,BUCKET:{list:async()=>({objects:[],truncated:false}),delete:async()=>{},head:async()=>null},REVIEW_MODERATOR_EMAIL:actors.admin.email,SITE_ORIGIN:origin};
let googleAvailable=true,googleCalls=[];
globalThis.fixtureConfirmPlace=(profile,existing,persist)=>{googleCalls.push({profile,existing,persist});return googleAvailable?'ChIJfixture-owner-match-'+profile.id:null;};
const [route,directory,cleanup]=await Promise.all(['route','directory','cleanup'].map(file=>import(new URL(`../${output}/${file}.mjs`,import.meta.url))));
const workshops=await import(new URL(`../${output}/workshops.mjs`,import.meta.url));
const settings=await import(new URL(`../${output}/settings.mjs`,import.meta.url));
const publicProfiles=await directory.listWorkshops(),first=publicProfiles[0],second=publicProfiles[1],third=publicProfiles[2],fourth=publicProfiles[3];
const evidence='This fictional registered operator can be independently verified through its company register and official contact.';
const profile=workshop=>({phone:workshop.phone,phoneNote:workshop.phoneNote,whatsapp:workshop.whatsapp,services:workshop.services,serviceDetails:workshop.serviceDetails,description:workshop.description});
const request=(method,body,headers={},path='/api/business')=>new Request(origin+path,{method,headers:{Origin:origin,'Content-Type':'application/json',...headers},...(body?{body:JSON.stringify(body)}:{})});
async function post(actor,body){globalThis.fixtureUser=actors[actor]??null;return route.POST(request('POST',body));}
async function state(actor,moderation=false){globalThis.fixtureUser=actors[actor]??null;return route.GET(new Request(origin+'/api/business'+(moderation?'?moderation=1':'')));}
const claim=(actor,workshopId,extra={})=>post(actor,{kind:'claim',input:{workshopId,evidence,evidenceLinks:['https://business.example.test/proof'],...extra}});
async function decide(actor,kind,id,decision='approved',revision=0,note='The independently checked operator proof is sufficient.'){globalThis.fixtureUser=actors[actor]??null;return route.PATCH(request('PATCH',{kind,id,revision,decision,note}));}
const change=(actor,workshopId,fields)=>post(actor,{kind:'change',workshopId,profile:fields});
let passed=0;const check=(condition,label)=>{assert(condition,label);passed++;};
for(const locale of ['de','sq','en']){
 globalThis.fixtureUser=actors.a;
 const invalid=await route.POST(request('POST',{kind:'claim',input:{workshopId:first.id,evidence:'short',evidenceLinks:[]}},{'Accept-Language':locale}));
 const data=await invalid.json();check(invalid.status===400&&data.errorCode==='business_invalid_input'&&data.error==='Bitte prüfe deine Eingaben, den Nachweis und die Beleglinks.','Business input codes and legacy status/text are identical for all UI languages');
 assert.throws(()=>directory.validateProfile({...first,phone:'invalid'},first.id),error=>error.code==='workshop_invalid_profile');passed++;
 globalThis.fixtureUser=actors.admin;
 const profileResponse=await workshops.PATCH(request('PATCH',{...first,phone:'invalid'},{'Accept-Language':locale},'/api/workshops')),profileError=await profileResponse.json();
 check(profileResponse.status===400&&profileError.errorCode==='workshop_invalid_profile','Actual workshop mutation responses carry the source-owned validation code without changing authorization');
 const configResponse=await settings.POST(request('POST',{projectUrl:'not-a-url',publicKey:'invalid',enabled:false},{'Accept-Language':locale},'/api/auth-settings')),configError=await configResponse.json();
 check(configResponse.status===400&&configError.errorCode==='auth_project_url','The actual protected configuration API exposes only a stable source-owned URL validation code');
}
check((await state('guest')).status===401&&(await claim('guest',first.id)).status===401,'Anonymous users cannot read or submit private ownership requests');
check((await state('a',true)).status===403,'A customer cannot read other applicants’ evidence');
check((await decide('a','claim',crypto.randomUUID())).status===403,'Customer accounts cannot approve themselves');
globalThis.fixtureUser=actors.a;
check((await route.POST(request('POST',{kind:'claim',input:{workshopId:first.id,evidence,evidenceLinks:[]}},{Origin:'https://other.example.test'}))).status===403,'Claim submission rejects cross-origin requests');
for(const extra of [{owner:actors.b.userId},{status:'approved'},{evidence:'short'},{evidenceLinks:['http://business.example.test/proof']},{evidenceLinks:['https://password:secret@business.example.test/proof']}])check((await claim('a',first.id,extra)).status===400,'Claims validate proof and reject authority fields or unsafe links');
check((await claim('a','missing-profile')).status===409,'Claims require an existing public profile');
let response=await claim('a',first.id),body=await response.json(),claimA=body.id;
check(response.status===201&&body.status==='pending','A current account can submit a private ownership claim');
check(db.prepare('SELECT owner,evidence,status FROM workshop_claims WHERE id=?').get(claimA).owner===actors.a.userId,'Claim ownership derives only from the verified session');
check((await claim('a',first.id)).status===409,'The same account cannot create a duplicate pending claim');
check(!db.prepare('SELECT * FROM workshop_owners WHERE workshop_id=?').get(first.id),'A pending claim cannot grant profile rights');
check((await change('a',first.id,profile(first))).status===403,'Pending applicants cannot edit the workshop');
body=await state('b').then(r=>r.json());check(body.claims.length===0,'Foreign applicants cannot read private proof or status');
body=await state('a').then(r=>r.json());check(body.claims[0].evidence===evidence&&body.claims[0].status==='pending','Applicants can see their own request and status');
body=await state('admin',true).then(r=>r.json());check(body.claims.some(claim=>claim.id===claimA&&claim.evidenceLinks[0]==='https://business.example.test/proof'),'The authorized queue includes private evidence links for review');
response=await claim('b',first.id);const claimB=(await response.json()).id;
check(response.ok,'Another account may submit a competing claim for independent review');
check((await decide('admin','claim',claimA,'approved',0,'short')).status===400,'A moderator must provide a meaningful reason');
const firstBefore=db.prepare('SELECT * FROM workshops WHERE id=?').get(first.id),googleBefore=db.prepare('SELECT * FROM workshop_google_places WHERE workshop_id=?').get(first.id);
const simultaneous=await Promise.all([decide('admin','claim',claimA),decide('admin','claim',claimB)]);
check(simultaneous.filter(r=>r.ok).length===1,'Concurrent approvals cannot grant the same profile to two accounts');
check(db.prepare('SELECT account_id FROM workshop_owners WHERE workshop_id=?').get(first.id).account_id===actors.a.userId,'The accepted proof grants only the requested existing profile');
check(db.prepare('SELECT status FROM workshop_claims WHERE id=?').get(claimB).status==='rejected','Competing pending claims receive an explicit decision once ownership is confirmed');
assert.deepEqual(db.prepare('SELECT * FROM workshops WHERE id=?').get(first.id),firstBefore);passed++;
assert.deepEqual(db.prepare('SELECT * FROM workshop_google_places WHERE workshop_id=?').get(first.id),googleBefore);passed++;
check((await claim('c',first.id)).status===409,'Already assigned profiles cannot be claimed again');
check((await change('b',first.id,profile(first))).status===403,'Another authenticated account cannot submit changes for the owner’s profile');
for(const extra of [{status:'published'},{sources:[]},{name:'Other Identity'},{address:'Other Location'},{role:'admin'}])check((await change('a',first.id,{...profile(first),...extra})).status===400,'Owner drafts cannot alter identity, sources, publication or roles directly');
for(const field of [{phone:'abcdefgh'},{whatsapp:'invalid-value'}]){const invalid=await change('a',first.id,{...profile(first),...field});check(invalid.status===400&&!(await invalid.json()).error.includes('nicht verfügbar'),'Malformed contact data returns a useful input error without replacing public details');}
response=await change('a',first.id,{...profile(first),description:'A verified fictional operator describes documented passenger-car repair work.'});let changeA=(await response.json()).id;
check(response.status===201,'Confirmed owners can submit a validated contact/service/description draft');
check((await change('a',first.id,profile(first))).status===409,'A workshop has at most one pending change draft');
check(db.prepare('SELECT description FROM workshops WHERE id=?').get(first.id).description===first.description,'Pending owner changes never replace public details');
check((await decide('a','change',changeA)).status===403,'Owners cannot directly publish their drafts');
response=await decide('admin','change',changeA);
check(response.ok,'A moderator can approve a current validated draft');
check(googleCalls.at(-1).persist===false,'Draft identity checks cannot overwrite the live Google cache before the transaction');
const approved=db.prepare('SELECT * FROM workshops WHERE id=?').get(first.id);
check(approved.description.includes('fictional operator')&&approved.status===firstBefore.status&&approved.sources===firstBefore.sources&&approved.name===firstBefore.name&&approved.address===firstBefore.address,'Approval changes only permitted fields and preserves provenance, identity and publication status');
check(db.prepare('SELECT status FROM workshop_changes WHERE id=?').get(changeA).status==='approved','Owners see the successful approval decision');
check((await decide('admin','change',changeA)).status===409,'A stale repeated decision cannot publish twice');
let latest=(await directory.listWorkshops()).find(w=>w.id===first.id);
response=await change('a',first.id,{...profile(latest),phone:'+383441234567'});changeA=(await response.json()).id;googleAvailable=false;
const cachedBeforeFailure=db.prepare('SELECT * FROM workshop_google_places WHERE workshop_id=?').get(first.id);
check((await decide('admin','change',changeA)).status===422,'Changed telephone identity needs a new confirmed Google match');
check(db.prepare('SELECT phone FROM workshops WHERE id=?').get(first.id).phone===latest.phone,'Failed identity checks preserve the approved public contact');
assert.deepEqual(db.prepare('SELECT * FROM workshop_google_places WHERE workshop_id=?').get(first.id),cachedBeforeFailure);passed++;
googleAvailable=true;response=await decide('admin','change',changeA,'rejected');check(response.ok,'A failed identity draft can be rejected with an explanation');
body=await state('a').then(r=>r.json());check(body.changes.find(change=>change.id===changeA).status==='rejected'&&body.changes.find(change=>change.id===changeA).moderatorNote,'The operator receives rejection status and reason');
latest=(await directory.listWorkshops()).find(w=>w.id===first.id);response=await change('a',first.id,profile(latest));changeA=(await response.json()).id;
db.prepare('UPDATE workshops SET updated_at=? WHERE id=?').run('2099-01-01T00:00:00Z',first.id);
check((await decide('admin','change',changeA)).status===409,'Approval never overwrites a more recent administrative revision');
await decide('admin','change',changeA,'rejected');db.prepare('UPDATE workshops SET updated_at=? WHERE id=?').run(latest.updatedAt,first.id);
// A confirmed legacy assignment is accessible only through the session’s owner keys.
response=await claim('a',second.id);const secondClaim=(await response.json()).id;await decide('admin','claim',secondClaim);
db.prepare('UPDATE workshop_owners SET account_id=? WHERE workshop_id=?').run('legacy-a',second.id);db.prepare("INSERT INTO auth_links (account_id,legacy_owner,created_at) VALUES (?,'legacy-a','2026-10-04')").run(actors.a.userId);
actors.a={...actors.a,ownerKeys:[actors.a.userId,'legacy-a']};
response=await change('a',second.id,profile(second));const legacyChange=(await response.json()).id;
check(response.ok&&(await decide('admin','change',legacyChange)).ok,'A verified legacy owner key authorizes drafts and their moderation without reassigning account identity');
actors.a={...actors.a,ownerKeys:[actors.a.userId]};
check((await change('a',second.id,profile(second))).status===403,'A session without legacy access cannot use a historical link to edit the profile');
response=await claim('b',third.id);const blockedClaim=(await response.json()).id;
db.prepare("INSERT INTO auth_account_status VALUES (?,'inactive','2026-10-04')").run(actors.b.userId);
check((await decide('admin','claim',blockedClaim)).status===409&&!db.prepare('SELECT workshop_id FROM workshop_owners WHERE workshop_id=?').get(third.id),'A blocked applicant cannot receive confirmed ownership');
db.prepare('DELETE FROM auth_account_status WHERE account_id=?').run(actors.b.userId);
// Concurrent duplicate submission is protected in the INSERT, not just in the UI.
const duplicates=await Promise.all([claim('c',fourth.id),claim('c',fourth.id)]);
check(duplicates.filter(r=>r.ok).length===1,'Concurrent identical claims produce only one pending record');
const delegated={...actors.admin,email:'delegated@example.test'};actors.delegated=delegated;db.prepare("INSERT INTO auth_account_roles VALUES (?,'admin','2026-10-04','fixture-owner')").run(delegated.userId);
const duplicateClaim=db.prepare("SELECT id FROM workshop_claims WHERE workshop_id=? AND status='pending'").get(fourth.id).id;
beforeBatch=()=>db.prepare('DELETE FROM auth_account_roles WHERE account_id=?').run(delegated.userId);
check((await decide('delegated','claim',duplicateClaim)).status===409&&!db.prepare('SELECT workshop_id FROM workshop_owners WHERE workshop_id=?').get(fourth.id),'Authority removed between read and commit cannot confirm ownership');
// Async identity hashing can reorder transaction arrival. Both Google results
// may legitimately win; a late loser must preserve the actual winner's data.
for(const winningValidation of [1,2]){
 latest=(await directory.listWorkshops()).find(w=>w.id===first.id);
 response=await change('a',first.id,{...profile(latest),description:latest.description+' Concurrent operator approval fixture.'});const concurrentChange=(await response.json()).id;
 let validationSequence=0,ready;const bothBatches=new Promise(resolve=>{ready=resolve;}),batches=[];
 globalThis.fixtureConfirmPlace=async()=>`ChIJConcurrentOperatorResult${++validationSequence}`;
 holdBatch=(statements,execute)=>new Promise((resolve,reject)=>{batches.push({values:statements.flatMap(statement=>statement.fixtureValues),execute:()=>execute().then(resolve,reject)});if(batches.length===2)ready();});
 const originalNow=Date.now,fixedTime=Date.parse(latest.updatedAt)+1;
 Date.now=()=>fixedTime;
 try{
  const notes=['Concurrent decision from request A.','Concurrent decision from request B.'];
  const attempts=notes.map(note=>decide('admin','change',concurrentChange,'approved',0,note));
  await bothBatches;
  const placeId=`ChIJConcurrentOperatorResult${winningValidation}`,winner=batches.find(batch=>batch.values.includes(placeId)),loser=batches.find(batch=>batch!==winner);
  assert(winner&&loser,'Both real SQLite transactions must reach the controlled admission point');
  check(batches.every(batch=>batch.values.includes(new Date(fixedTime).toISOString())),'Both prepared decisions share the exact publication timestamp');
  const winnerNote=notes.find(note=>winner.values.includes(note));
  await winner.execute();const winnerResponse=await attempts[notes.indexOf(winnerNote)];
  check(winnerResponse.status===200,'The deliberately admitted transaction wins moderation');
  const readWinner=()=>({change:db.prepare('SELECT * FROM workshop_changes WHERE id=?').get(concurrentChange),profile:db.prepare('SELECT * FROM workshops WHERE id=?').get(first.id),place:db.prepare('SELECT * FROM workshop_google_places WHERE workshop_id=?').get(first.id),rating:db.prepare('SELECT * FROM workshop_google_ratings WHERE workshop_id=?').get(first.id)});
  const committed=readWinner();
  check(committed.change.moderator_note===winnerNote&&committed.change.revision===1&&typeof committed.change.decision_token==='string','The actual winner owns the decision revision and operation token');
  check(committed.profile.updated_at===new Date(fixedTime).toISOString(),'Both candidates use the same publication timestamp');
  check(committed.place.place_id===placeId&&new URL(committed.rating.maps_url).searchParams.get('query_place_id')===placeId,'Google identity and Maps URL come from the winning transaction');
  await loser.execute();const concurrentDecisions=await Promise.all(attempts);
  check(concurrentDecisions.filter(response=>response.status===200).length===1&&concurrentDecisions.filter(response=>response.status===409).length===1,'Concurrent moderation approves exactly one candidate and rejects its stale competitor');
  assert.deepEqual(readWinner(),committed,'A losing optimistic decision cannot overwrite the winner’s profile, audit data or Google identity');passed++;
 }finally{Date.now=originalNow;holdBatch=null;}
}
const deleteAuth={projectUrl,client:{auth:{admin:{deleteUser:async()=>({error:null})}}}};
await cleanup.deleteAccount(deleteAuth,aId);
check(db.prepare('SELECT COUNT(*) AS n FROM workshop_claims WHERE owner=?').get(actors.a.userId).n===0&&db.prepare('SELECT COUNT(*) AS n FROM workshop_changes WHERE owner IN (?,?)').get(actors.a.userId,'legacy-a').n===0,'Account deletion removes private ownership evidence and drafts, including linked legacy records');
check(!db.prepare('SELECT workshop_id FROM workshop_owners WHERE account_id IN (?,?)').get(actors.a.userId,'legacy-a'),'Deleted accounts retain no confirmed workshop rights');
check(db.prepare('SELECT id FROM workshops WHERE id=?').get(first.id),'Account deletion preserves independently maintained public workshop catalogue records');
// Complete moderation/history queues use stable keyset pagination.
db.prepare('DELETE FROM workshop_claims').run();
for(let index=0;index<101;index++)db.prepare('INSERT INTO workshop_claims (id,workshop_id,owner,evidence,created_at,status) VALUES (?,?,?,?,?,?)').run(`00000000-0000-4000-8000-${String(index).padStart(12,'0')}`,first.id,actors.c.userId,evidence,'2026-10-04T12:00:00Z','pending');
globalThis.fixtureUser=actors.admin;
let seen=[];let cursor=null;do{const url=new URL(origin+'/api/business');url.searchParams.set('moderation','1');if(cursor)url.searchParams.set('claimCursor',cursor);const page=await route.GET(new Request(url)).then(response=>response.json());seen.push(...page.claims.map(claim=>claim.id));cursor=page.nextClaimCursor;}while(cursor);
check(seen.length===101&&new Set(seen).size===101&&seen.includes('00000000-0000-4000-8000-000000000000'),'Every pending claim remains reachable beyond the first hundred, including equal timestamps');
db.prepare("UPDATE workshop_claims SET status='approved' WHERE id<>'00000000-0000-4000-8000-000000000000'").run();
globalThis.fixtureUser=actors.c;seen=[];cursor=null;do{const url=new URL(origin+'/api/business');if(cursor)url.searchParams.set('claimCursor',cursor);const page=await route.GET(new Request(url)).then(response=>response.json());seen.push(...page.claims);cursor=page.nextClaimCursor;}while(cursor);
check(seen.length===101&&seen.find(claim=>claim.id==='00000000-0000-4000-8000-000000000000').status==='pending','An applicant can still reach an older pending request beneath more than one hundred history entries');
check((await route.GET(new Request(origin+'/api/business?claimCursor=invalid'))).status===400,'Malformed pagination is an input error');
failDb=true;check((await state('admin',true)).status===503,'Storage failure does not expose an incomplete private review queue');failDb=false;
console.log(JSON.stringify({businessContractChecksPassed:passed,liveProviderCalls:false,productionTouched:false}));
