import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {createRequire} from 'node:module';
import {JSDOM,VirtualConsole} from 'jsdom';
const dom=new JSDOM('<div id="root"></div>',{url:'https://riparim.example.test/betrieb',pretendToBeVisual:true,virtualConsole:new VirtualConsole()});
for(const key of ['window','document','navigator','HTMLElement','HTMLButtonElement','HTMLFormElement','HTMLInputElement','HTMLSelectElement','HTMLTextAreaElement','DocumentFragment','Element','Node','NodeFilter','MutationObserver','CustomEvent','Event','MouseEvent','KeyboardEvent','getComputedStyle'])Object.defineProperty(globalThis,key,{value:dom.window[key],configurable:true});
globalThis.requestAnimationFrame=dom.window.requestAnimationFrame.bind(dom.window);globalThis.cancelAnimationFrame=dom.window.cancelAnimationFrame.bind(dom.window);globalThis.IS_REACT_ACT_ENVIRONMENT=true;
const {build}=createRequire(new URL('../package.json',import.meta.url))('esbuild');
const out='.test-runtime/business-ui';await mkdir(out,{recursive:true});
const bundle=await build({stdin:{contents:"export {I18nProvider} from './lib/i18n/client';export {getMessages} from './lib/i18n/messages';export {BusinessPanel} from './components/business-panel';",resolveDir:process.cwd(),loader:'tsx'},outfile:out+'/ui.mjs',bundle:true,write:false,format:'esm',platform:'node',packages:'external'});await writeFile(out+'/ui.mjs',bundle.outputFiles[0].contents);
const {createElement,act}=await import('react'),{createRoot}=await import('react-dom/client'),{BusinessPanel,I18nProvider,getMessages}=await import(new URL('../'+out+'/ui.mjs',import.meta.url));
const workshop={id:'fixture-workshop',name:'Fiktive Werkstatt',city:'Prishtina',address:'Fixture Street 10',phone:'+38344123456',phoneNote:'Betrieb',whatsapp:'',services:['Inspektion & Wartung'],serviceDetails:['Inspektion'],description:'A sufficiently detailed fictional passenger-car workshop description.',status:'published',updatedAt:'2026-10-04T09:00:00Z'};
let records={claims:[],changes:[],workshops:[]},mode='success',pending=null,loadFailure=false,holdLoad=false,resolveLoad=null;
const requests=[];
const requestView=(id,kind)=>({id,workshopId:workshop.id,workshopName:workshop.name,owner:'fixture-owner',status:'pending',moderatorNote:'',revision:0,createdAt:'2026-10-04T10:00:00Z',...(kind==='claim'?{evidence:'A private and sufficiently detailed fictional company-register explanation.',evidenceLinks:['https://business.example.test/proof']}:{profile:{phone:workshop.phone,phoneNote:workshop.phoneNote,whatsapp:workshop.whatsapp,services:workshop.services,serviceDetails:workshop.serviceDetails,description:workshop.description+' Proposed extra services.'},baseUpdatedAt:workshop.updatedAt})});
const currentState=()=>({...records,pendingClaims:records.pendingClaims??records.claims.filter(row=>row.status==='pending').map(({id,workshopId,workshopName,createdAt})=>({id,workshopId,workshopName,createdAt})),pendingChangeRequestIds:records.pendingChangeRequestIds??records.changes.filter(row=>row.status==='pending').map(row=>row.id),pendingChangeWorkshopIds:records.pendingChangeWorkshopIds??records.changes.filter(row=>row.status==='pending'&&records.workshops.some(workshop=>workshop.id===row.workshopId)).map(row=>row.workshopId)});
globalThis.fetch=async(url,options)=>{
 const method=options?.method??'GET',body=options?.body?JSON.parse(options.body):null;requests.push({url,method,body});
 if(method==='GET'){assert(url.startsWith('/api/business'));if(holdLoad)return new Promise(resolve=>resolveLoad=resolve);const query=new URL(url,'https://riparim.example.test').searchParams;if(query.has('claimCursor'))return Response.json({...currentState(),claims:records.claimPage??[requestView('00000000-0000-4000-8000-000000000011','claim')],nextClaimCursor:null});if(query.has('changeCursor'))return Response.json({...currentState(),changes:records.changePage??[requestView('00000000-0000-4000-8000-000000000012','change')],nextChangeCursor:null});if(loadFailure)return Response.json({error:'Fixture loading failed',errorCode:'business_unavailable'},{status:503});return Response.json(url.includes('moderation')?{...currentState(),claims:records.claims.filter(row=>row.status==='pending'),changes:records.changes.filter(row=>row.status==='pending')}:currentState());}
 assert.equal(url,'/api/business','Only the isolated business fixture receives writes');
 if(method==='POST'){
  if(mode==='failure')return Response.json({error:'Fixture duplicate or invalid draft',errorCode:'business_draft_conflict'},{status:409});
  if(body.kind==='claim'){assert.deepEqual(Object.keys(body),['kind','input']);assert.deepEqual(Object.keys(body.input),['workshopId','evidence','evidenceLinks']);records.claims.push(requestView('00000000-0000-4000-8000-000000000001','claim'));return Response.json({status:'pending'},{status:201});}
  assert.equal(body.kind,'change');assert.deepEqual(Object.keys(body.profile).sort(),['description','phone','phoneNote','serviceDetails','services','whatsapp'].sort());
  const commit=()=>{records.changes.push({...requestView('00000000-0000-4000-8000-000000000002','change'),profile:body.profile});return Response.json({status:'pending'},{status:201});};
  if(mode==='pending')return new Promise(resolve=>pending={resolve,commit});return commit();
 }
 assert.equal(method,'PATCH');assert.deepEqual(Object.keys(body),['kind','id','revision','decision','note']);
 if(mode==='failure')return Response.json({error:'Fixture stale decision',errorCode:'business_claim_conflict'},{status:409});
 const commit=()=>{const list=body.kind==='claim'?records.claims:records.changes;const record=list.find(row=>row.id===body.id);record.status=body.decision;record.revision++;record.moderatorNote=body.note;return Response.json({ok:true});};
 if(mode==='pending')return new Promise(resolve=>pending={resolve,commit});return commit();
};
let root=createRoot(document.getElementById('root')),passed=0;
const check=(value,label)=>{assert(value,label);passed++;};
const button=label=>[...document.querySelectorAll('button')].find(node=>node.textContent===label);
const control=label=>[...document.querySelectorAll('label')].find(node=>node.textContent.startsWith(label))?.querySelector('input,select,textarea')??document.getElementById([...document.querySelectorAll('label')].find(node=>node.textContent===label)?.htmlFor);
const click=async node=>{assert(node,'Expected UI control exists');await act(async()=>{node.focus();node.click();});};
const type=async(node,value)=>{const prototype=node instanceof HTMLTextAreaElement?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;await act(async()=>{Object.getOwnPropertyDescriptor(prototype,'value').set.call(node,value);node.dispatchEvent(new Event('input',{bubbles:true}));});};
const submit=async form=>act(async()=>form.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));
const render=async(moderation=false)=>act(async()=>root.render(fixtureMessages(createElement(BusinessPanel,{directory:[workshop],initialWorkshop:workshop.id,moderation}))));
const remount=async(moderation=false)=>{await act(async()=>root.unmount());root=createRoot(document.getElementById('root'));await render(moderation);};
const dialog=()=>document.querySelector('[role="alertdialog"]');
try{
 loadFailure=true;await render();check(document.querySelector('[role="alert"]').textContent===getMessages('de').management.businessUnavailable&&button('Aktualisieren'),'Loading failure exposes an accessible refresh action');
 check(document.querySelector('header h1')?.textContent==='Mein Betrieb'&&document.querySelector('header').contains(button('Aktualisieren')),'Refresh is available beside the page title even when the first load fails');
 loadFailure=false;await click(button('Aktualisieren'));
 check([...document.querySelectorAll('h2')].map(heading=>heading.textContent).join('|')==='Werkstattprofil beanspruchen','The first visit leads directly to the claim form without empty profile or history panels');
 check(control('Bestehendes Profil').value===workshop.id,'The profile claim preserves its selected public workshop');
 const proof=control('Privater Inhabernachweis');check(proof.minLength===40&&proof.maxLength===4000&&proof.required,'The private proof field is labelled and bounded');
 await type(proof,'A sufficiently detailed fictional register explanation proving operator ownership.');await type(control('Beleglinks'),'https://business.example.test/proof');mode='failure';await submit(proof.form);
 check(document.querySelector('[role="alert"]').textContent===getMessages('de').management.business_draft_conflict&&control('Privater Inhabernachweis').value.includes('register explanation'),'Rejected submission preserves the private draft and announces its error');
 mode='success';await submit(proof.form);
 check(document.querySelector('[role="status"]').textContent.includes('privater Inhabernachweis')&&document.querySelector('.business-status').textContent==='In Prüfung','Successful submission announces review without granting ownership');
 check(control('Privater Inhabernachweis').value===''&&!button('Bestätigen'),'Customer views clear submitted proof and offer no moderation action');
 check(document.querySelector('.business-panel').textContent.includes('Warte auf die Entscheidung')&&document.querySelector('.business-panel').textContent.includes('separate Freigabe'),'A pending claim explains manual review and the next step without implying publication');
 check(document.querySelector('details summary')?.textContent==='Weiteres Profil beanspruchen'&&!document.querySelector('details').open,'A pending applicant can reach another claim without a second expanded primary form');
 check(!document.querySelector('.business-evidence')&&!document.querySelector('.business-request a'),'Customer request cards do not expose evidence or review links belonging to other applicants');
 records.workshops=[workshop];await click(button('Aktualisieren'));
 check(document.querySelector('h2').textContent==='Deine Profile'&&document.querySelector('.business-panel').textContent.includes('Änderungen werden erst nach Freigabe öffentlich'),'Owners can find profile editing and understand the separate publication approval');
 await click(button('Profil bearbeiten'));
 check(control('Telefon').value===workshop.phone&&control('Beschreibung').value===workshop.description,'The owner editor uses the current approved contact and description');
 check(document.querySelector('.business-panel').textContent.includes('Quellen und Freigabestatus bleiben geschützt'),'The editor explains protected identity and publication fields');
 await type(control('Beschreibung'),workshop.description+' Additional documented repair services.');mode='pending';await submit(control('Telefon').form);
 check(document.querySelector('.business-form fieldset').disabled,'A pending draft disables conflicting editor actions');
 check(requests.filter(row=>row.method==='POST'&&row.body.kind==='change').length===1,'The pending editor issues one scoped change request');
 await act(async()=>pending.resolve(pending.commit()));pending=null;mode='success';
 check(!document.querySelector('.business-panel').textContent.includes('Entwurf für')&&button('Profil bearbeiten').disabled,'Submitted drafts close the editor and prevent duplicates while awaiting moderation');
 check(document.querySelector('[role="status"]').textContent.includes('bisherigen öffentlichen Angaben'),'Submission clearly preserves the previously published profile');
 const proposal=document.querySelector('.business-proposal').closest('details');check(proposal&&!proposal.open&&proposal.querySelector('summary').textContent==='Eingereichte Angaben ansehen','Customers can inspect submitted changes without a large expanded proposal');
 records.claims=[requestView('00000000-0000-4000-8000-000000000003','claim')];records.workshops=[workshop];await remount(true);
 check(document.querySelector('.business-evidence').textContent.includes('company-register')&&document.querySelector('.business-request a').getAttribute('rel')==='noopener noreferrer','The administrator sees private evidence with safe external links');
 check(document.querySelector('.business-current summary').textContent==='Aktuell freigegebene Angaben ansehen','Change review includes the approved profile for comparison');
 await click(button('Bestätigen'));check(dialog().contains(document.activeElement),'Moderation confirmation takes keyboard focus');
 check(button('Entscheidung speichern').disabled,'Moderation cannot be confirmed without a meaningful reason');
 await act(async()=>document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true,cancelable:true})));
 check(!dialog()&&requests.filter(row=>row.method==='PATCH').length===0,'Escape cancels moderation without sending a decision');
 await click(button('Bestätigen'));await type(control('Begründung'),'Independent fictional operator proof was checked.');mode='pending';await click(button('Entscheidung speichern'));
 check([...dialog().querySelectorAll('button')].every(node=>node.disabled),'Pending moderation locks confirmation and cancellation');
 await act(async()=>document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true,cancelable:true})));
 check(dialog()&&requests.filter(row=>row.method==='PATCH').length===1,'A pending decision cannot be dismissed or duplicated');
 await act(async()=>pending.resolve(pending.commit()));pending=null;mode='success';
 check(!dialog()&&document.querySelector('[role="status"]').textContent==='Entscheidung gespeichert.','Confirmed ownership refreshes the queue and announces completion');
 await click(button('Ablehnen'));await type(control('Begründung'),'The proposed fictional changes require additional proof.');mode='failure';await click(button('Entscheidung speichern'));
 check(dialog().querySelector('[role="alert"]').textContent===getMessages('de').management.business_claim_conflict,'A stale decision remains visible and is not announced as success');
 mode='success';await click(button('Entscheidung speichern'));
 check(!dialog()&&document.querySelector('.business-panel').textContent.includes('Keine Änderungsentwürfe vorhanden'),'A confirmed rejection clears the pending change queue');
 records={workshops:[workshop],claims:[requestView('00000000-0000-4000-8000-000000000004','claim')],changes:[requestView('00000000-0000-4000-8000-000000000005','change')],nextClaimCursor:'fixture-claim-cursor',nextChangeCursor:'fixture-change-cursor'};await remount(true);
 await click(button('Weitere Anträge laden'));
 check(document.querySelectorAll('.business-request').length===3&&!button('Weitere Anträge laden')&&button('Weitere Änderungen laden'),'Claim pagination appends older requests without resetting the independent draft queue');
 await click(button('Weitere Änderungen laden'));
 check(document.querySelectorAll('.business-request').length===4&&!button('Weitere Änderungen laden'),'Draft pagination appends older proposals and stops at the last page');
 records={workshops:[],claims:[{...requestView('00000000-0000-4000-8000-000000000020','claim'),status:'rejected',moderatorNote:'Please supplement the fictional register entry.'}],changes:[]};await remount();
 check(document.querySelector('h2').textContent==='Werkstattprofil beanspruchen'&&!document.querySelector('.business-form').closest('details'),'A history-only applicant returns directly to the claim form');
 check(document.querySelector('.business-request').textContent.includes('Dieser Antrag wurde abgelehnt. Beachte den Prüfvermerk.')&&document.querySelector('.business-note').textContent.includes('supplement'),'Historical rejected claims report their outcome and retain the private review note');
 records={workshops:[workshop],claims:[{...requestView('00000000-0000-4000-8000-000000000021','claim'),status:'approved'}],changes:[{...requestView('00000000-0000-4000-8000-000000000022','change'),status:'rejected',moderatorNote:'Please correct the fictional contact number.'},{...requestView('00000000-0000-4000-8000-000000000023','change'),status:'approved'}]};await remount();
 check(document.querySelector('.business-panel').textContent.includes('Dieser Inhabernachweis wurde bestätigt')&&button('Profil bearbeiten')&&!button('Profil bearbeiten').disabled,'Confirmed ownership points to the assigned profile editor');
 check(document.querySelector('.business-panel').textContent.includes('Diese Änderungen wurden abgelehnt. Beachte den Prüfvermerk.')&&[...document.querySelectorAll('.business-status')].some(node=>node.textContent==='Freigegeben'),'Historical rejected changes report their outcome while approved changes clearly indicate publication approval');
 records={workshops:[],claims:[],changes:[]};await remount();await type(control('Privater Inhabernachweis'),'Another sufficiently detailed and isolated fictional register explanation.');loadFailure=true;await submit(control('Privater Inhabernachweis').form);
 check(document.querySelector('[role="status"]').textContent.includes('eingereicht')&&document.querySelector('[role="alert"]').textContent.includes('bereits eingereicht')&&document.querySelector('[role="alert"]').textContent.includes('Aktualisieren'),'A saved claim with a failed follow-up reload is clearly saved and asks for refresh instead of resubmission');
 loadFailure=false;await click(button('Aktualisieren'));check(document.querySelector('.business-status').textContent==='In Prüfung','Refresh recovers the saved request after a follow-up reload failure');
 records={workshops:[],claims:[],changes:[]};holdLoad=true;await remount();
 check(document.querySelector('[role="status"]').textContent==='Betriebsdaten werden geladen …'&&button('Aktualisieren').disabled&&document.querySelector('header h1').textContent==='Mein Betrieb','Initial loading keeps the page title visible and prevents a duplicate reload');
 holdLoad=false;await act(async()=>resolveLoad(Response.json(currentState())));resolveLoad=null;holdLoad=true;await click(button('Aktualisieren'));
 check([...document.querySelectorAll('[role="status"]')].some(node=>node.textContent==='Betriebsdaten werden aktualisiert …')&&button('Aktualisieren').disabled&&control('Privater Inhabernachweis').matches(':disabled'),'Refresh announces progress and prevents conflicting submissions while preserving the loaded screen');
 holdLoad=false;await act(async()=>resolveLoad(Response.json(currentState())));resolveLoad=null;
 records={workshops:[],claims:Array.from({length:50},(_,index)=>({...requestView(`history-${index}`,'claim'),status:'approved'})),changes:[],pendingClaims:[{id:'older-pending-claim',workshopId:workshop.id,workshopName:workshop.name,createdAt:'2020-01-01T00:00:00Z'}],pendingChangeWorkshopIds:[],nextClaimCursor:'older-history'};await remount();
 check(document.querySelector('h2').textContent==='Deine Anträge'&&document.querySelector('.business-status').textContent==='In Prüfung'&&document.querySelector('.business-request').textContent.includes('Warte auf die Entscheidung')&&!document.querySelector('.business-claim').open,'An older current claim remains the visible next step without paging through historical decisions');
 records={...records,pendingClaims:[]};await remount();check(document.querySelector('h2').textContent==='Werkstattprofil beanspruchen'&&button('Weitere Anträge laden'),'A history cursor alone does not imply an ongoing claim or hide direct claim entry');
 records={workshops:[workshop],claims:[],changes:Array.from({length:50},(_,index)=>({...requestView(`change-history-${index}`,'change'),status:'approved'})),pendingClaims:[],pendingChangeWorkshopIds:[workshop.id],nextChangeCursor:'older-change-history'};await remount();
 check(button('Profil bearbeiten').disabled&&document.querySelector('.business-request').textContent.includes('Warte auf die Freigabe'),'An older pending change locks editing and explains the current next step before history is loaded');
 records={workshops:[workshop],claims:[],changes:[requestView('replacement-pending','change'),{...requestView('old-rejected-change','change'),status:'rejected',moderatorNote:'Replaced with a corrected draft.'}]};await remount();
 const rejectedDraft=document.querySelector('.business-status.rejected').closest('article');check(button('Profil bearbeiten').disabled&&rejectedDraft.textContent.includes('Diese Änderungen wurden abgelehnt')&&!rejectedDraft.textContent.includes('erneut ein'),'A rejected historical draft does not ask for resubmission while its replacement is pending');
 records={workshops:[],claims:[{...requestView('competing-rejected-claim','claim'),status:'rejected',moderatorNote:'Ein anderer Übernahme-Antrag wurde bestätigt.'}],changes:[]};await remount();
 const rejectedClaim=document.querySelector('.business-status.rejected').closest('article');check(rejectedClaim.textContent.includes('anderer Übernahme-Antrag')&&!rejectedClaim.textContent.includes('neuen Antrag')&&rejectedClaim.textContent.includes('abgelehnt'),'An automatically rejected competing claim reports the assignment decision without promising a retry of that profile');
 records={workshops:[],claims:[requestView('visible-current-claim','claim')],changes:[]};await remount();check(document.querySelector('.business-request').textContent.includes('privaten Nachweis manuell')&&document.querySelector('.business-request').textContent.includes('separate Freigabe'),'Current claim guidance visibly explains private manual verification and separate publication approval');
 records={workshops:[],claims:[requestView('claim-approved-between-pages','claim')],changes:[],nextClaimCursor:'older-approved-history'};await remount();records.workshops=[workshop];records.pendingClaims=[];records.claimPage=[{...requestView('older-approved-claim','claim'),status:'approved'}];await click(button('Weitere Anträge laden'));
 check(document.querySelector('h2').textContent==='Deine Profile'&&button('Profil bearbeiten')&&!button('Profil bearbeiten').disabled,'Pagination adopts current ownership together with current request summaries after external approval');
 for(const kind of ['claim','change'])for(const outcome of ['approved','rejected','replacement']){
  const obsolete={...requestView('obsolete-pending-change','change'),profile:{...requestView('obsolete-pending-change','change').profile,description:'Obsolete pending proposal before an external decision.'}};
  records={workshops:[workshop],claims:[],changes:[obsolete],nextClaimCursor:'older-claim-page',nextChangeCursor:'older-change-page'};await remount();
  records.claimPage=[{...requestView('older-claim-history','claim'),status:'approved'}];records.changePage=[{...requestView('older-change-history','change'),status:'approved'}];
  records.pendingChangeWorkshopIds=outcome==='replacement'?[workshop.id]:[];records.pendingChangeRequestIds=outcome==='replacement'?['replacement-current-change']:[];
  records.changes=outcome==='replacement'?[{...obsolete,id:'replacement-current-change',profile:{...obsolete.profile,description:'The replacement proposal is the current pending change.'}}]:[{...obsolete,status:outcome,moderatorNote:'An external '+outcome+' decision.'}];
  await click(button(kind==='claim'?'Weitere Anträge laden':'Weitere Änderungen laden'));
  check(!document.body.textContent.includes('Obsolete pending proposal')&&button('Profil bearbeiten').disabled===(outcome==='replacement'),`Pagination in the ${kind} queue reconciles an obsolete pending card after external ${outcome} without guessing its decision`);
  if(outcome==='replacement'){await click(button('Aktualisieren'));check(document.body.textContent.includes('The replacement proposal is the current pending change.'),'A full refresh reveals the current replacement proposal rather than the obsolete one');}
 }
 console.log(JSON.stringify({businessUiChecksPassed:passed,liveRequests:false}));
}finally{await act(async()=>root.unmount());dom.window.close();}

function fixtureMessages(element){return createElement(I18nProvider,{locale:"de",messages:getMessages("de",["common","customer","management"])},element);}
