import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {createRequire} from 'node:module';
import {DatabaseSync} from 'node:sqlite';
const {build}=createRequire(new URL('../package.json',import.meta.url))('esbuild');
const bundle=await build({entryPoints:{auth:'app/auth.ts',config:'lib/auth/config.ts',actions:'app/api/auth/[action]/route.ts',callback:'app/auth/bestaetigen/route.ts'},bundle:true,format:'esm',platform:'node',outdir:'.test-runtime/google-auth',write:false,plugins:[{name:'auth-fixtures',setup(b){
 b.onResolve({filter:/^(cloudflare:workers|@\/app\/chatgpt-auth|\.\/chatgpt-auth|@\/lib\/auth\/client|next\/headers)$/},args=>({path:args.path,namespace:'fixture'}));
 b.onLoad({filter:/.*/,namespace:'fixture'},args=>({contents:args.path==='cloudflare:workers'?'export const env=globalThis.fixtureEnv;':args.path==='next/headers'?'export async function cookies(){return globalThis.fixtureCookies;}':args.path.includes('chatgpt-auth')?'export async function getChatGPTUser(){return globalThis.fixtureNative;}':'export async function authClient(){return globalThis.fixtureClient;}',loader:'js'}));
}}]});
await mkdir('.test-runtime/google-auth',{recursive:true});
for(const file of bundle.outputFiles)await writeFile(file.path.replace(/\.js$/,'.mjs'),file.contents);
const db=new DatabaseSync(':memory:');
for(const file of ['0002_exotic_slayback','0003_magenta_boom_boom','0004_ambiguous_morbius'])db.exec(await readFile('drizzle/'+file+'.sql','utf8'));
const d1={prepare(sql){const statement=db.prepare(sql);const adapter=(values=[])=>({first:async()=>statement.get(...values)??null,run:async()=>({meta:statement.run(...values)}),all:async()=>({results:statement.all(...values)}),bind:(...next)=>adapter(next)});return adapter();}};
const projectUrl='https://fixture-project.supabase.co',origin='https://riparim.example.test';
globalThis.fixtureEnv={DB:d1,BUCKET:{},REVIEW_MODERATOR_EMAIL:'owner@example.test',SITE_ORIGIN:origin};
globalThis.fixtureNative=null;
const cookieMap=new Map(),cookieOptions=new Map();
globalThis.fixtureCookies={get(name){const value=cookieMap.get(name);return value?{name,value}:undefined;},getAll(){return [...cookieMap].map(([name,value])=>({name,value}));},set(name,value,options){cookieOptions.set(name,options);if(options?.maxAge===0)cookieMap.delete(name);else cookieMap.set(name,value);}};
let user={id:'00000000-0000-4000-8000-000000000001',email:'owner@example.test',email_confirmed_at:'2026-10-03',user_metadata:{full_name:'Owner',provider:'google'},identities:[{provider:'google',identity_data:{sub:'google-owner-123',email:'owner@example.test',email_verified:true}}]};
let sessionId='oauth-session-1',method='oauth',claimsError=null,claimedId=null,googleEnabled=true,googleProfile={sub:'google-owner-123',email:'owner@example.test',email_verified:true};
let emailAutoConfirm=false,passwordCalls=0,oauthCalls=0,codeExchanges=0,lastOAuth=null,lastSetSession=null;
const providerSession=()=>({access_token:'fixture-supabase-access',refresh_token:'fixture-supabase-refresh',provider_token:'fixture-google-token',user});
globalThis.fixtureClient={auth:{
 getUser:async()=>({data:{user},error:null}),
 getClaims:async()=>({data:{claims:{session_id:sessionId,sub:claimedId??user.id,amr:[{method}]}},error:claimsError}),
 setSession:async(value)=>{lastSetSession=value;return {data:{session:providerSession()},error:null};},
 signInWithOAuth:async(value)=>{oauthCalls++;lastOAuth=value;return {data:{url:projectUrl+'/auth/v1/authorize?provider=google'},error:null};},
 signInWithPassword:async()=>{passwordCalls++;return {data:{user},error:null};},
 exchangeCodeForSession:async()=>{codeExchanges++;method='oauth';return {data:{user,session:providerSession()},error:null};},
 signOut:async()=>({error:null}),
}};
const originalFetch=globalThis.fetch;
globalThis.fetch=async(url)=>{
 if(String(url)===projectUrl+'/auth/v1/settings')return Response.json({external:{email:true,google:googleEnabled},mailer_autoconfirm:emailAutoConfirm,disable_signup:false});
 if(String(url)==='https://openidconnect.googleapis.com/v1/userinfo')return Response.json(googleProfile);
 throw Error('Unexpected live request blocked: '+url);
};
db.prepare("INSERT INTO auth_settings VALUES ('main',?,?,1,0,?)").run(projectUrl,'sb_publishable_fixture_public_key_1234567890','2026-10-03');
const auth=await import(new URL('../.test-runtime/google-auth/auth.mjs',import.meta.url));
const cfg=await import(new URL('../.test-runtime/google-auth/config.mjs',import.meta.url));
const actions=await import(new URL('../.test-runtime/google-auth/actions.mjs',import.meta.url));
const callback=await import(new URL('../.test-runtime/google-auth/callback.mjs',import.meta.url));
let passed=0;
const check=(value,label)=>{assert(value,label);passed++;};
const post=(action,body={},requestOrigin=origin)=>actions.POST(new Request(origin+'/api/auth/'+action,{method:'POST',headers:{'content-type':'application/json',Origin:requestOrigin,'cf-connecting-ip':'fixture-ip'},body:JSON.stringify(body)}),{params:Promise.resolve({action})});
const callbackRequest=(query)=>callback.GET(new Request(origin+'/auth/bestaetigen?'+new URLSearchParams(query)));
const accountId=auth.providerAccountId(projectUrl,user.id);
const row=()=>db.prepare('SELECT * FROM auth_sessions WHERE id=?').get(sessionId);
const config=await cfg.getAuthConfig();
await cfg.verifyProvider(config,false);passed++;
let availability=await cfg.providerAvailability(config);
check(availability.google&&availability.email&&!availability.emailSignup&&!availability.emailRecovery,'Email/password and Google login do not require sending email');
check((await post('register',{email:user.email,password:'fixture-password-123'})).status===503,'SMTP-unconfirmed registration cannot send live mail');
check((await post('recovery',{email:user.email})).status===503,'SMTP-unconfirmed recovery cannot send live mail');
sessionId='email-without-smtp';method='password';
check((await post('login',{email:user.email,password:'fixture-password-123'})).status===200,'Confirmed account can log in while SMTP is unconfirmed');
check(row()?.provider==='password'&&!row()?.moderator,'Email login grants a password session without Google privileges');
user={...user,email_confirmed_at:null};sessionId='unconfirmed-email-login';
check((await post('login',{email:user.email,password:'fixture-password-123'})).status===401&&!row(),'Unconfirmed email cannot obtain an app session');
user={...user,email_confirmed_at:'2026-10-03'};emailAutoConfirm=true;
check((await post('login',{email:user.email,password:'fixture-password-123'})).status===503&&passwordCalls===2,'Server blocks password login if email confirmation is disabled at the provider');
emailAutoConfirm=false;sessionId='oauth-session-1';method='oauth';
check((await post('google',{},'https://other.example.test')).status===403,'Google start rejects cross-origin POST');
googleEnabled=false;
check((await post('google')).status===503&&oauthCalls===0,'Disabled Google never produces a pretend OAuth URL');
googleEnabled=true;
let response=await post('google',{returnTo:'//other.example.test'});
check(response.status===200&&oauthCalls===1,'Enabled Google starts real SDK OAuth');
check(lastOAuth.provider==='google'&&lastOAuth.options.skipBrowserRedirect,'Server-owned PKCE flow');
check(lastOAuth.options.scopes==='openid email profile','Only identity scopes requested');
let destination=new URL(lastOAuth.options.redirectTo);
check(destination.origin===origin&&destination.pathname==='/auth/bestaetigen','OAuth callback is canonical Site URL');
check(destination.searchParams.get('weiter')==='/?besuche=1','OAuth external return path is rejected');
let flow=cookieMap.get('riparim-google-flow'),options=cookieOptions.get('riparim-google-flow');
check(options.httpOnly&&options.secure&&options.sameSite==='lax'&&options.maxAge===600,'OAuth intent cookie is private, secure and short-lived');
response=await callbackRequest({anbieter:'google',code:'fixture-code',fluss:'wrong-flow'});
check(response.status===303&&new URL(response.headers.get('Location')).searchParams.get('fehler')==='google'&&codeExchanges===0,'Mismatched intent cannot exchange a code');
check(!cookieMap.has('riparim-google-flow'),'Invalid callback consumes intent cookie');
await post('google',{returnTo:'/?besuche=1'});
flow=cookieMap.get('riparim-google-flow');
globalThis.fixtureNative={userId:'legacy-owner',email:user.email,displayName:'Native owner',fullName:null};
response=await callbackRequest({anbieter:'google',code:'fixture-code',fluss:flow,weiter:'/?besuche=1'});
check(response.status===303&&new URL(response.headers.get('Location')).search==='?besuche=1','Successful Google callback returns to requested private view');
check(codeExchanges===1&&row().provider==='google'&&row().google_subject==='google-owner-123'&&row().moderator===1,'Verified current Google proof enrolls exact session');
check(row().expires_at>Date.now()+29*86400000&&row().expires_at<=Date.now()+30*86400000,'Session retains a bounded 30-day lifetime');
check(lastSetSession.access_token&&lastSetSession.refresh_token&&!('provider_token' in lastSetSession),'Google provider credentials are removed before cookie persistence');
check(db.prepare('SELECT password_access FROM auth_links WHERE account_id=?').get(accountId).password_access===0,'Google-created native ownership link does not grant password access');
globalThis.fixtureNative=null;
let current=await auth.getAppUser();
check(current.isModerator&&current.provider==='Google'&&current.ownerKeys.includes('legacy-owner'),'Verified Google session can own legacy records and administer without native ChatGPT');
check((await auth.getAdminUser(current)).isModerator,'Configured owner is reachable through verified Google identity');
sessionId='preclaimed-password-session';method='password';
await auth.recordPasswordSession(projectUrl,user,globalThis.fixtureClient);
current=await auth.getAppUser();
check(current.provider==='E-Mail'&&!current.isModerator&&current.ownerKeys.length===1,'Password on linked account cannot inherit Google role or Google-created legacy link');
check(row().legacy_access===0&&row().moderator===0,'Password session stores no Google grants');
globalThis.fixtureNative={userId:'someone-else',email:'other@example.test',displayName:'Other',fullName:null};
sessionId='password-mismatched-native';
await auth.recordPasswordSession(projectUrl,user,globalThis.fixtureClient);
check(row().legacy_access===0,'Unrelated native identity cannot upgrade password ownership');
globalThis.fixtureNative={userId:'legacy-owner',email:user.email,displayName:'Owner',fullName:null};
sessionId='password-fresh-native';
await auth.recordPasswordSession(projectUrl,user,globalThis.fixtureClient);
current=await auth.getAppUser();
check(current.ownerKeys.includes('legacy-owner')&&!current.isModerator,'Fresh matching native proof may upgrade password legacy ownership but never Google moderation');
globalThis.fixtureNative=null;
sessionId='oauth-session-1';method='oauth';
method='password';check(await auth.getAppUser()===null,'Google session requires continuing signed OAuth method proof');method='oauth';
const originalIdentity=user.identities;
user={...user,identities:[]};
check(await auth.getAppUser()===null,'Unlinked Google identity invalidates Google session access');
user={...user,identities:originalIdentity,user_metadata:{full_name:'Forged owner',email:'another@example.test',is_admin:true}};
check((await auth.getAppUser()).isModerator,'Mutable metadata cannot replace independently verified Google role proof');
claimedId='another-user';
check(await auth.getAppUser()===null,'JWT subject must match server-verified identity');
claimedId=null;claimsError={message:'fixture bad signature'};
check(await auth.getAppUser()===null,'Invalid JWT signature cannot pass D1 session allowlist');
claimsError=null;
await auth.revokeCurrentSession(globalThis.fixtureClient);
check(await auth.getAppUser()===null,'Revocation denies otherwise valid Google session');
db.prepare('UPDATE auth_sessions SET revoked=0,expires_at=0 WHERE id=?').run(sessionId);
check(await auth.getAppUser()===null,'Expired app session cannot be prolonged by provider refresh');
sessionId='unverified-google-session';method='oauth';googleProfile={...googleProfile,email_verified:false};
await assert.rejects(auth.recordGoogleSession(projectUrl,providerSession(),globalThis.fixtureClient),/INVALID_GOOGLE_IDENTITY/);passed++;
check(!row(),'Unverified Google email never enrolls a session');
googleProfile={sub:'wrong-google-subject',email:user.email,email_verified:true};
await assert.rejects(auth.recordGoogleSession(projectUrl,providerSession(),globalThis.fixtureClient),/INVALID_GOOGLE_IDENTITY/);passed++;
check(!row(),'Different Google subject never enrolls a session');
googleProfile={sub:'google-owner-123',email:user.email,email_verified:true};method='password';
await assert.rejects(auth.recordGoogleSession(projectUrl,providerSession(),globalThis.fixtureClient),/INVALID_AUTH_SESSION/);passed++;
check(!row(),'Historical linked Google identity cannot prove a current password session');
method='oauth';
await assert.rejects(auth.recordGoogleSession(projectUrl,{...providerSession(),provider_token:null},globalThis.fixtureClient),/INVALID_GOOGLE_SESSION/);passed++;
check(!row(),'OAuth callback requires fresh provider proof, not account metadata');
globalThis.fetch=originalFetch;
console.log(JSON.stringify({googleAuthBoundaryChecksPassed:passed,liveProviderCalls:false,realEmailsSent:false}));
