import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir,readdir} from 'node:fs/promises';
import {createRequire} from 'node:module';
import {DatabaseSync} from 'node:sqlite';
import {createHash} from 'node:crypto';
const {build}=createRequire(new URL('../package.json',import.meta.url))('esbuild');
const output='.test-runtime/google-places';
const bundle=await build({entryPoints:{identity:'lib/google-place-identity.ts',places:'db/google-places.ts',directory:'db/directory.ts',config:'app/api/google-places/route.ts',match:'app/api/google-places/[id]/route.ts',browser:'lib/google-maps-browser.ts'},outdir:output,bundle:true,write:false,format:'esm',platform:'node',plugins:[{name:'google-fixtures',setup(b){b.onResolve({filter:/^cloudflare:workers$/},args=>({path:args.path,namespace:'fixture'}));b.onLoad({filter:/.*/,namespace:'fixture'},()=>({contents:'export const env=globalThis.fixtureEnv;',loader:'js'}));}}]});
await mkdir(output,{recursive:true});for(const file of bundle.outputFiles)await writeFile(file.path.replace(/\.js$/,'.mjs'),file.contents);
const sqlite=new DatabaseSync(':memory:');for(const file of (await readdir('drizzle')).filter(file=>file.endsWith('.sql')).sort())sqlite.exec(await readFile('drizzle/'+file,'utf8'));
const d1={prepare(sql){const statement=sqlite.prepare(sql);const adapter=(values=[])=>({bind:(...next)=>adapter(next),first:async()=>statement.get(...values)??null,all:async()=>({results:statement.all(...values)}),run:async()=>({meta:statement.run(...values)})});return adapter();},async batch(statements){const result=[];for(const statement of statements)result.push(await statement.run());return result;}};
globalThis.fixtureEnv={DB:d1,BUCKET:{}};
const load=name=>import(new URL('../'+output+'/'+name+'.mjs',import.meta.url));
const [identity,places,directory,config,match,browser]=await Promise.all(['identity','places','directory','config','match','browser'].map(load));
const all=await directory.listWorkshops(true),mita=all.find(w=>w.id==='auto-mita');
sqlite.exec('DELETE FROM workshop_google_places');
const candidate={id:'ChIJFixtureAutoMitaOnly',displayName:{text:'Auto Mita'},internationalPhoneNumber:'+383 45 686 868',formattedAddress:'Prishtina, Kosovo',addressComponents:[{types:['country'],shortText:'XK',longText:'Kosovo'}],location:{latitude:mita.lat,longitude:mita.lng}};
assert.equal(identity.verifiedGooglePlace(mita,[candidate]),candidate.id);
assert.equal(identity.verifiedGooglePlace(mita,[{...candidate,internationalPhoneNumber:'+38349111111'}]),null,'phone must match');
assert.equal(identity.verifiedGooglePlace(mita,[{...candidate,displayName:{text:'Auto Bardhi'}}]),null,'generic car-service names are insufficient');
assert.equal(identity.verifiedGooglePlace(mita,[{...candidate,addressComponents:[{types:['country'],shortText:'MK',longText:'North Macedonia'}]}]),null,'country must match');
assert.equal(identity.verifiedGooglePlace(mita,[{...candidate,location:{latitude:42.85,longitude:21.13}}]),null,'known premises must match');
assert.equal(identity.verifiedGooglePlace(mita,[candidate,{...candidate,id:'ChIJAnotherAutoMita'}]),null,'ambiguous identities are rejected');
assert.equal(identity.verifiedGooglePlace(mita,[{...candidate,id:'fake'}]),null,'invalid Google identifiers are rejected');
assert.equal(identity.verifiedGooglePlace({...mita,lat:null,lng:null,city:'Fushë Kosovë'},[candidate]),null,'country text alone does not match Fushë Kosovë');
const localSearch=identity.googlePlaceSearchRequest(mita);
assert.equal(localSearch.textQuery,'+383 45686868');assert.equal(localSearch.regionCode,'XK');
assert.deepEqual(localSearch.locationBias,{circle:{center:{latitude:mita.lat,longitude:mita.lng},radius:3000}},'known workshop premises replace the server IP as search bias');
const legacySearch=identity.googlePlaceSearchRequest({...mita,phone:'+38138765432',lat:null,lng:null});
assert.equal(legacySearch.textQuery,'+381 38765432');assert.equal(legacySearch.regionCode,'RS','calling-code region does not rewrite the actual phone number');
assert.deepEqual(legacySearch.locationBias,{rectangle:{low:{latitude:41.8,longitude:19.8},high:{latitude:43.3,longitude:21.9}}});
assert.equal(identity.verifiedGooglePlace({...mita,phone:'+38138765432'},[{...candidate,internationalPhoneNumber:'+381 38 765432',addressComponents:[{types:['country'],shortText:'RS',longText:'Serbia'}]}]),null,'legacy calling codes never authorize a workshop outside Kosovo');
assert.equal(identity.verifiedGooglePlace(mita,[{...candidate,displayName:{text:'Renault - Dacia dhe Nissan #AutoMita'}}]),candidate.id,'joined brand names still match');
assert.equal(identity.verifiedGooglePlace(mita,[{...candidate,primaryType:'electric_vehicle_charging_station',displayName:{text:'AutoMita charging station'}}]),null,'charging stations are not workshop profiles');
assert.equal(identity.verifiedGooglePlace(mita,[{...candidate,addressComponents:undefined}]),candidate.id,'Google omits Kosovo country: exact sourced premises, phone and name still verify identity');
assert.equal(identity.verifiedGooglePlace(mita,[{...candidate,addressComponents:undefined,location:{latitude:mita.lat+0.02,longitude:mita.lng}}]),null,'missing country requires exact premises');
const origin='https://riparim.example.test',request=path=>new Request(origin+path),params=id=>({params:Promise.resolve({id})});
let calls=0,lastRequest=null,apiError=false;
const originalFetch=globalThis.fetch;
globalThis.fetch=async(url,options)=>{assert.equal(String(url),'https://places.googleapis.com/v1/places:searchText','fixtures never use live Google APIs');calls++;lastRequest=options;return apiError?Response.json({error:'fixture'}, {status:503}):Response.json({places:[candidate]});};
assert.deepEqual(await (await config.GET(request('/api/google-places'))).json(),{enabled:false});
assert.deepEqual(await (await match.GET(request('/api/google-places/auto-mita'),params('auto-mita'))).json(),{enabled:false,placeId:null});
assert.equal(calls,0,'missing keys never call Google');
globalThis.fixtureEnv.GOOGLE_MAPS_BROWSER_API_KEY='fixture-browser-key';
globalThis.fixtureEnv.GOOGLE_PLACES_SERVER_API_KEY='fixture-server-key';
const configResponse=await config.GET(request('/api/google-places'));
const body=await configResponse.text();assert(body.includes('fixture-browser-key')&&!body.includes('fixture-server-key'),'the private server key never crosses the HTTP boundary');
assert.equal(configResponse.headers.get('Cache-Control'),'no-store');
assert.equal((await config.GET(new Request(origin+'/api/google-places',{headers:{Origin:'https://other.example.test'}}))).status,403);
const draft=all.find(w=>w.status==='draft');assert.equal((await match.GET(request('/api/google-places/'+draft.id),params(draft.id))).status,404,'drafts cannot trigger a Google lookup');
assert.equal((await match.GET(request('/api/google-places/bad/id'),params('bad/id'))).status,404);
const legacyHash=createHash('sha256').update(JSON.stringify([mita.name,mita.phone,mita.city,mita.address,mita.lat,mita.lng])).digest('hex');
sqlite.prepare('INSERT INTO workshop_google_places (workshop_id,place_id,profile_hash,checked_at,retry_after) VALUES (?,NULL,?,?,?)').run(mita.id,legacyHash,Date.now(),Date.now()+7*86400000);
assert.equal(await places.resolveWorkshopGooglePlace(mita),candidate.id);assert.equal(calls,1,'the corrected resolver retries a negative result from the old search strategy');
assert.equal(await places.resolveWorkshopGooglePlace(mita),candidate.id);assert.equal(calls,1,'a stored verified ID prevents repeated identity searches');
assert.deepEqual(JSON.parse(lastRequest.body),localSearch,'query and search geography come only from server-owned public workshop data');
assert(!lastRequest.headers['X-Goog-FieldMask'].includes('rating')&&!lastRequest.headers['X-Goog-FieldMask'].includes('reviews'),'matching never imports review content');
assert.equal(lastRequest.headers['X-Goog-Api-Key'],'fixture-server-key');
const columns=sqlite.prepare('PRAGMA table_info(workshop_google_places)').all().map(row=>row.name);assert(!columns.includes('rating')&&!columns.includes('review_count')&&!columns.includes('reviews'),'persistent matching stores only IDs and application metadata');
const matchesBefore=sqlite.prepare('SELECT COUNT(*) AS n FROM workshop_google_places').get().n;
assert.equal(matchesBefore,1);assert.equal((await directory.listWorkshops()).length,78);assert.equal((await directory.listWorkshops(true)).filter(w=>w.status==='draft').length,85);
assert.equal((await directory.listWorkshops()).find(w=>w.id===mita.id).rating,null,'Google matching leaves Riparim aggregates untouched');
const quotaKey='google-place-lookups:'+new Date().toISOString().slice(0,10);
sqlite.prepare('UPDATE catalog_state SET value=? WHERE key=?').run('100',quotaKey);
sqlite.prepare('INSERT INTO workshop_google_places (workshop_id,place_id,profile_hash,checked_at,retry_after) VALUES (?,?,?,?,?)').run('legacy-positive-fixture',candidate.id,legacyHash,Date.now(),Date.now()+365*86400000);
assert.equal(await places.resolveWorkshopGooglePlace({...mita,id:'legacy-positive-fixture'}),candidate.id,'an unchanged verified legacy match survives the strategy upgrade even with no remaining quota');assert.equal(calls,1);
assert.equal(await places.resolveWorkshopGooglePlace({...mita,id:'legacy-positive-fixture',phone:'+38349111111'}),null,'a changed profile cannot reuse a legacy verified identity');assert.equal(calls,1);
assert.equal(await places.resolveWorkshopGooglePlace({...mita,id:'quota-fixture'}),null);assert.equal(calls,1,'daily identity-search budget cannot be exceeded');
sqlite.prepare('UPDATE catalog_state SET value=? WHERE key=?').run('1',quotaKey);
assert.equal(await places.resolveWorkshopGooglePlace({...mita,id:'ambiguous-fixture',phone:'+38349111111'}),null);assert.equal(calls,3);assert.equal(await places.resolveWorkshopGooglePlace({...mita,id:'ambiguous-fixture',phone:'+38349111111'}),null);assert.equal(calls,3,'unmatched candidates are not retried on every visit');
apiError=true;await assert.rejects(places.resolveWorkshopGooglePlace({...mita,id:'error-fixture'}));assert.equal(calls,4);assert.equal(await places.resolveWorkshopGooglePlace({...mita,id:'error-fixture'}),null);assert.equal(calls,4,'provider failures back off');
apiError=false;
let fallbackCalls=0;
globalThis.fetch=async(url,options)=>{fallbackCalls++;const query=JSON.parse(options.body);if(fallbackCalls===1){assert.equal(query.textQuery,localSearch.textQuery);return Response.json({places:[]});}assert.equal(query.textQuery,`${mita.name} ${mita.city} Kosovo`);return Response.json({places:[candidate]});};
assert.equal(await places.resolveWorkshopGooglePlace({...mita,id:'name-fallback-fixture'}),candidate.id,'verified name lookup recovers an empty phone search');
assert.equal(fallbackCalls,2);
let countryCalls=0;
globalThis.fetch=async(url,options)=>{countryCalls++;if(String(url).includes('searchText'))return Response.json({places:[{...candidate,addressComponents:undefined}]});assert.equal(options.headers['X-Goog-FieldMask'],'addressComponents');return Response.json({addressComponents:candidate.addressComponents});};
assert.equal(await places.resolveWorkshopGooglePlace({...mita,id:'country-details-fixture'}),candidate.id,'missing search country is verified through Place Details');
assert.equal(countryCalls,2);
let requestedFields=null,requestedPlace=null;
globalThis.window={google:{maps:{importLibrary:async()=>({Place:class{constructor(options){requestedPlace=options;this.rating=4.6;this.userRatingCount=123;this.googleMapsURI='https://maps.google.com/?cid=123';this.attributions=[];}async fetchFields(options){requestedFields=options.fields;}}})}}};
const live=await browser.currentGoogleRating(candidate.id,'fixture-browser-key');assert.equal(live.rating,4.6);assert.equal(live.count,123);assert.equal(requestedPlace.id,candidate.id);assert.deepEqual(requestedFields,['rating','userRatingCount','googleMapsURI','attributions']);
assert.equal(sqlite.prepare('SELECT rating FROM workshop_google_ratings WHERE workshop_id=?').get(mita.id).rating,4.8,'current API data is displayed, not written over sourced snapshots');
globalThis.fetch=originalFetch;delete globalThis.window;sqlite.close();
console.log(JSON.stringify({googleIdentityChecks:9,explicitSearchGeography:true,negativeCacheUpgrade:true,apiBoundaries:true,dailyBudget:100,existingPublicWorkshops:78,existingDraftsPreserved:85,currentGoogleRatings:true,googleRatingsPersisted:false,liveProviderCalls:false}));
