import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {mkdir,writeFile} from 'node:fs/promises';
import {JSDOM,VirtualConsole} from 'jsdom';
const dom=new JSDOM('<div id="root"></div>',{url:'https://riparim.test/werkstatt/fixture-workshop',pretendToBeVisual:true,virtualConsole:new VirtualConsole()});
for(const key of ['document','navigator','HTMLElement','HTMLButtonElement','HTMLInputElement','HTMLTextAreaElement','HTMLFormElement','HTMLSelectElement','Option','DocumentFragment','Element','Node','NodeFilter','MutationObserver','CustomEvent','Event','MouseEvent','KeyboardEvent','getComputedStyle'])Object.defineProperty(globalThis,key,{value:dom.window[key],configurable:true});
const navigations=[];const location={get href(){return dom.window.location.href;},get pathname(){return dom.window.location.pathname;},get search(){return dom.window.location.search;},get hash(){return dom.window.location.hash;},assign(value){navigations.push(value);}};
Object.defineProperty(globalThis,'window',{value:new Proxy(dom.window,{get(target,key){return key==='location'?location:Reflect.get(target,key,target);}}),configurable:true});
globalThis.requestAnimationFrame=dom.window.requestAnimationFrame.bind(dom.window);globalThis.cancelAnimationFrame=dom.window.cancelAnimationFrame.bind(dom.window);globalThis.IS_REACT_ACT_ENVIRONMENT=true;window.matchMedia=()=>({matches:false,addEventListener(){},removeEventListener(){}});globalThis.ResizeObserver=class{observe(){}unobserve(){}disconnect(){}};
const out='.test-runtime/i18n-whatsapp-guard.mjs',bundle=await build({stdin:{contents:`export {default as Profile} from './app/[locale]/werkstatt/[id]/profile';export {I18nProvider} from './lib/i18n/client';export {getMessages} from './lib/i18n/messages';export {useNavigationState} from './lib/i18n/navigation-guard';`,resolveDir:process.cwd(),loader:'tsx'},outfile:out,bundle:true,write:false,platform:'node',format:'esm',jsx:'automatic',packages:'external',external:['react','react/jsx-runtime'],plugins:[{name:'routing-boundary',setup(b){b.onResolve({filter:/^next\/(navigation|link)$/},a=>({path:a.path,namespace:'fixture'}));b.onLoad({filter:/.*/,namespace:'fixture'},a=>({loader:'js',resolveDir:process.cwd(),contents:a.path==='next/link'?`import React from 'react';export default function Link({children,href,...props}){return React.createElement('a',{...props,href},children);}`:`export function useRouter(){return {push(){},refresh(){},prefetch(){}};}export function usePathname(){return window.location.pathname;}export function useSearchParams(){return new URLSearchParams(window.location.search);}`}));}}]});
await mkdir('.test-runtime',{recursive:true});await writeFile(out,bundle.outputFiles[0].text);const {Profile,I18nProvider,getMessages,useNavigationState}=await import(new URL('../'+out,import.meta.url));
const React=await import('react'),{createRoot}=await import('react-dom/client'),h=React.createElement,root=createRoot(document.getElementById('root'));
function State(){const state=useNavigationState();return h('output',{'data-guard-dirty':String(state.dirty)});}
const workshop={id:'fixture-workshop',name:'Fixture Workshop',city:'Prishtina',address:'Fixture Address',phone:'+38349123456',phoneNote:'',whatsapp:'+38349123456',lat:null,lng:null,rating:null,count:0,specialty:'Original specialty',description:'Original description',services:['Bremsen & Fahrwerk'],serviceDetails:[],brands:['Volvo'],languages:[],sources:[],checkedAt:'2026-10-04',status:'published',googleRating:null};
const props={workshop,directory:[workshop],reviews:[],reviewError:'',signedIn:true,account:{email:'fixture@example.test',displayName:'Fixture Customer',provider:'Google'},isAdmin:false},nativeFetch=globalThis.fetch;
const click=async node=>{assert(node);await React.act(async()=>{node.focus();node.dispatchEvent(new MouseEvent('click',{bubbles:true,cancelable:true,button:0}));});},dirty=()=>document.querySelector('[data-guard-dirty]').dataset.guardDirty;
let checks=0;
try{for(const locale of ['de','sq','en'])for(const mode of ['cancel','confirm','untouched','closed','reopened']){
 const next=locale==='de'?'sq':locale==='sq'?'en':'de',current=`https://riparim.test${locale==='de'?'':`/${locale}`}/werkstatt/fixture-workshop`;
 dom.reconfigure({url:current});navigations.length=0;let finish,writes=[],confirmations=[];
 globalThis.fetch=async(url,init)=>{if(url==='/api/account'){writes.push({url,init});return new Promise(resolve=>{finish=resolve;});}if(url==='/api/google-places')return Response.json({enabled:false});throw Error('Unexpected fixture request: '+url);};
 window.confirm=text=>{confirmations.push(text);return mode==='confirm';};
 await React.act(async()=>root.render(h(I18nProvider,{locale,messages:getMessages(locale,['common','public','customer'])},h(Profile,props),h(State))));
 const selector=document.querySelector('.language-switcher select');assert.equal(dirty(),'false');await React.act(async()=>{selector.focus();selector.value=next;selector.dispatchEvent(new Event('change',{bubbles:true}));});
 assert(finish&&writes.length===1&&selector.disabled,'actual authenticated Header/LanguageSwitcher starts a deferred own preference PATCH');assert.deepEqual(JSON.parse(writes[0].init.body),{preferredLocale:next});
 await click(document.querySelector('.workshop-overview-actions button'));let textarea=document.querySelector('[role="dialog"] textarea'),initial=textarea.value;assert.equal(dirty(),'false','opening the unmodified generated message is not a new private edit');
 const edited=initial+'\nPrivate RAM-only fixture edit';if(mode!=='untouched'){await React.act(async()=>{textarea.focus();Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value').set.call(textarea,edited);textarea.dispatchEvent(new Event('input',{bubbles:true}));});assert.equal(textarea.value,edited);}
 if(mode==='closed'||mode==='reopened'){await React.act(async()=>document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true,cancelable:true})));await React.act(async()=>new Promise(resolve=>setTimeout(resolve,0)));assert.equal(dirty(),'false','closing unregisters the private draft');if(mode==='reopened'){await click(document.querySelector('.workshop-overview-actions button'));textarea=document.querySelector('[role="dialog"] textarea');assert.equal(textarea.value,initial,'reopening resets to a new generated baseline');assert.equal(dirty(),'false');}}
 if(mode==='cancel')textarea.focus();await React.act(async()=>finish(Response.json({preferredLocale:next})));
 if(mode==='cancel'){assert.equal(navigations.length,0,'declining the latest WhatsApp edit prevents the already pending language navigation');assert.equal(window.location.href,current);assert.equal(textarea.value,edited);assert.equal(document.activeElement,textarea,'declining preserves focus in the edited modal');assert.equal(selector.value,locale);assert.equal(selector.disabled,false);assert.equal(dirty(),'true');}
 else{assert.equal(navigations.length,1,'confirmed or unmodified/closed/reset drafts retain sensible existing navigation');assert.equal(navigations[0],`${next==='de'?'':`/${next}`}/werkstatt/fixture-workshop`);assert(!navigations[0].includes('Private')&&!JSON.stringify(writes).includes('Private'),'private message never enters URL or provider writes');}
 assert.equal(confirmations.length,['cancel','confirm'].includes(mode)?1:0,'only currently edited open drafts require confirmation');if(confirmations.length)assert.equal(confirmations[0],getMessages(locale).common.discardDraft,'confirmation uses current document locale');
 assert.equal(window.localStorage.length,0);assert.equal(window.sessionStorage.length,0,'message remains in RAM');checks++;await React.act(async()=>root.render(null));
}}finally{await React.act(async()=>root.unmount());globalThis.fetch=nativeFetch;dom.window.close();}
console.log(JSON.stringify({actualProfileHeaderPreferenceRaceChecks:checks,locales:['de','sq','en'],cancelPreservesUrlTextFocus:true,privateDraftPersisted:false,liveCalls:false}));
