import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {mkdir,writeFile} from 'node:fs/promises';
import {JSDOM,VirtualConsole} from 'jsdom';
const id='00000000-0000-4000-8000-000000000001',other='00000000-0000-4000-8000-000000000002';
const dom=new JSDOM('<div id="root"></div>',{url:'https://riparim.example.test/sq/bewertungen?einreichung='+id,pretendToBeVisual:true,virtualConsole:new VirtualConsole()});
for(const key of ['window','document','navigator','HTMLElement','HTMLButtonElement','HTMLFormElement','HTMLInputElement','HTMLSelectElement','HTMLTextAreaElement','Option','DocumentFragment','Element','Node','NodeFilter','MutationObserver','CustomEvent','Event','MouseEvent','KeyboardEvent','getComputedStyle','FormData'])Object.defineProperty(globalThis,key,{value:dom.window[key],configurable:true});
globalThis.requestAnimationFrame=dom.window.requestAnimationFrame.bind(dom.window);globalThis.cancelAnimationFrame=dom.window.cancelAnimationFrame.bind(dom.window);globalThis.IS_REACT_ACT_ENVIRONMENT=true;globalThis.ResizeObserver=class{observe(){}unobserve(){}disconnect(){}};
const out='.test-runtime/my-reviews-ui.mjs';
const bundle=await build({stdin:{contents:"export {MyVisits} from './app/journeys';export {I18nProvider} from './lib/i18n/client';export {getMessages} from './lib/i18n/messages';",resolveDir:process.cwd(),loader:'tsx'},outfile:out,bundle:true,write:false,format:'esm',platform:'node',packages:'external',plugins:[{name:'navigation-boundary',setup(builder){builder.onResolve({filter:/^next\/link$/},()=>({path:'link',namespace:'fixture'}));builder.onLoad({filter:/.*/,namespace:'fixture'},()=>({loader:'js',resolveDir:process.cwd(),contents:"import React from 'react';export default function Link({href,children,...props}){return React.createElement('a',{...props,href},children)}"}));}}]});
await mkdir('.test-runtime',{recursive:true});await writeFile(out,bundle.outputFiles[0].contents);
const {createElement,act}=await import('react'),{createRoot}=await import('react-dom/client'),{MyVisits,I18nProvider,getMessages}=await import(new URL('../'+out,import.meta.url));
const visit=(value=id,status='needs_more')=>({id:value,workshop:'fixture-workshop',workshop_name:'Fiktive Werkstatt',date:'2026-10-04',vehicle:'Fixture Car',service:'Inspektion & Wartung',evidence_type:'Rechnung',evidence_note:'Private fictional evidence.',status,moderator_note:'Private fictional request for another proof.',display_name:'Fixture Driver',rating:4,review:'A sufficiently detailed fictional repair review.',created_at:'2026-10-04',file_name:'fixture.png',revision:7});
let items=[visit()],mode='pending',mutationMode='success',deferred;
const requests=[];
globalThis.fetch=async(url,options)=>{
 const method=options?.method??'GET';requests.push({url,method,body:options?.body});assert(url.startsWith('/api/visits'),'Fixtures only use the private local submission API');
 if(method==='PUT'){const form=options.body;items=items.map(item=>item.id===form.get('id')?{...item,status:'pending',revision:item.revision+1}:item);return Response.json({ok:true});}
 if(method==='DELETE'){
  if(mutationMode==='error')return Response.json({errorCode:'review_conflict'},{status:409});
  const commit=()=>{items=items.filter(item=>item.id!==JSON.parse(options.body).id);return Response.json({ok:true});};
  if(mutationMode==='pending')return new Promise(resolve=>{deferred=()=>resolve(commit());});
  return commit();
 }
 if(mode==='pending')return new Promise(resolve=>{deferred=resolve;});
 if(mode==='error')return Response.json({errorCode:'review_unavailable',error:'Private raw error must not be shown'},{status:503});
 if(mode==='expired')return Response.json({errorCode:'authentication_required'},{status:401});
 const query=new URL(url,'https://riparim.example.test').searchParams;
 if(mode==='pages')return Response.json({visits:query.get('cursor')?[items[1]]:[items[0]],nextCursor:query.get('cursor')?null:'fixture-next'});
 return Response.json({visits:mode==='empty'?[]:query.get('id')?items.filter(item=>item.id===query.get('id')):items,nextCursor:null});
};
let root=createRoot(document.getElementById('root')),passed=0;
const check=(value,label)=>{assert(value,label);passed++;},copy=getMessages('sq').customer;
const button=label=>[...document.querySelectorAll('button')].find(node=>node.textContent===label);
const click=async control=>{assert(control);await act(async()=>{control.focus();control.click();});};
const render=async(props={})=>act(async()=>root.render(createElement(I18nProvider,{locale:'sq',messages:getMessages('sq',['common','customer'])},createElement(MyVisits,{directory:[{id:'fixture-workshop',name:'Fiktive Werkstatt',services:['Inspektion & Wartung']}],signedIn:true,account:{email:'fixture-a@example.test',displayName:'Fixture A',provider:'E-Mail'},submissionId:id,...props}))));
try{
 await render();check(document.querySelector('main [role="status"]').textContent===copy.myReviewsLoading&&document.querySelector('.visit-list').getAttribute('aria-busy')==='true','A pending own-history request has a localized announced loading state');
 check(document.querySelector('.storage-notice')&&button(copy.loading).disabled&&!document.querySelector('[role="dialog"]'),'Loading keeps the privacy notice and disables conflicting refresh without an overlay');
 await act(async()=>deferred(Response.json({visits:items,nextCursor:null})));mode='success';
 check(document.querySelectorAll('.visit').length===1&&document.querySelector('.evidence-details a').getAttribute('href')==='/api/evidence/'+id+'?locale=sq','Loaded own reviews retain private evidence download links in the active locale');
 mode='error';await click(button(copy.refresh));check(document.querySelector('[role="alert"]').textContent===copy.reviewUnavailable&&!document.body.textContent.includes('Private raw error'),'Failed refresh keeps a localized error and hides raw private/provider details');
 check(document.querySelectorAll('.visit').length===1&&!button(copy.refresh).disabled,'A transient refresh failure retains the prior history and offers retry');
 mode='empty';await click(button(copy.refresh));check(document.querySelector('.empty h3').textContent===copy.noReviews&&!document.querySelector('[role="alert"]'),'A successful empty history has a coherent localized empty state');
 mode='expired';await click(button(copy.refresh));const signIn=document.querySelector('.login-prompt a');
 check(signIn?.getAttribute('href')==='/sq/anmelden?weiter='+encodeURIComponent('/sq/bewertungen?einreichung='+id)&&!document.querySelector('.visit'),'An expired session clears private history and offers existing sign-in with the exact localized page return');
 mode='success';await click(button(copy.refresh));await click(button(copy.supplement));
 check(document.querySelector('[role="dialog"]').contains(document.activeElement)&&document.querySelector('[name="vehicle"]').value==='Fixture Car'&&document.querySelector('[name="evidenceNote"]').value==='Private fictional evidence.','Supplement opens the existing accessible editor with original private fields');
 await click(document.querySelector('[role="checkbox"]'));await act(async()=>document.querySelector('form').dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));
 const edit=requests.find(request=>request.method==='PUT');
 check(edit.body.get('id')===id&&edit.body.get('revision')==='7'&&edit.body.get('keepEvidence')==='true'&&edit.body.get('evidenceType')==='Rechnung','Editing keeps the owned submission revision and the existing private receipt contract');
 check(document.querySelector('[role="dialog"] a')?.getAttribute('href')==='/sq/bewertungen?einreichung='+id,'The edit completion link returns to the independent exact submission page');
 await click(button(copy.close));check(!document.querySelector('[role="dialog"]')&&document.querySelector('.visit-status').textContent==='Në shqyrtim','Closing the editor refreshes history on the page and shows the new moderation status');
 await click(button(copy.edit));await act(async()=>document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true,cancelable:true})));check(!document.querySelector('[role="dialog"]')&&requests.filter(request=>request.method==='PUT').length===1,'Escape cancels an unchanged edit without resubmitting');
 items=[{...visit(id,'approved'),review:null,rating:null,display_name:null}];await click(button(copy.refresh));await click(button(copy.completeReview));
 check(document.querySelector('[name="review"]').value===''&&document.querySelector('.existing-evidence').textContent.includes('fixture.png'),'An older approved visit can complete its review while retaining private evidence');
 await click(button(copy.cancel));
 items=[visit(id,'published'),visit(other,'pending')];mode='pages';await render({submissionId:null});
 check(document.querySelectorAll('.visit').length===1&&button(copy.moreReviews),'The own page retains the first history page and an accessible pagination action');
 await click(button(copy.moreReviews));check(requests.at(-1).url==='/api/visits?cursor=fixture-next'&&document.querySelectorAll('.visit').length===2&&!button(copy.moreReviews),'Pagination appends older owned submissions using only the server cursor');
 await click(button(copy.refresh));check(requests.at(-1).url==='/api/visits'&&document.querySelectorAll('.visit').length===1,'Refresh starts the history at the first page instead of duplicating older items');
 mode='success';await click(button(copy.refresh));
 const ownArticle=[...document.querySelectorAll('.visit')].find(article=>article.textContent.includes('Publikuar'));
 await click(ownArticle.querySelector('.delete-button'));check(document.querySelector('[role="alertdialog"]').contains(document.activeElement),'Deletion retains a focused accessible confirmation on the regular page');
 await act(async()=>document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true,cancelable:true})));check(!document.querySelector('[role="alertdialog"]')&&!requests.some(request=>request.method==='DELETE'),'Escape cancels deletion without changing the owned submission');
 await click(ownArticle.querySelector('.delete-button'));mutationMode='error';await click(document.querySelector('[role="alertdialog"] button[data-slot="alert-dialog-action"]'));
 check(document.querySelector('[role="alertdialog"] [role="alert"]').textContent===copy.reviewConflict&&document.querySelectorAll('.visit').length===2,'Failed deletion keeps its owned history and gives a localized retry');
 mutationMode='pending';await click(document.querySelector('[role="alertdialog"] button[data-slot="alert-dialog-action"]'));
 check([...document.querySelectorAll('[role="alertdialog"] button,.visit-actions button')].every(control=>control.disabled),'An active deletion prevents duplicate actions on both confirmation and page');
 await act(async()=>document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true,cancelable:true})));check(document.querySelector('[role="alertdialog"]'),'An active deletion cannot be dismissed by Escape');
 await act(async()=>deferred());mutationMode='success';check(!document.querySelector('[role="alertdialog"]')&&document.querySelectorAll('.visit').length===1&&requests.filter(request=>request.method==='DELETE').at(-1).body===JSON.stringify({id}),'Successful deletion refreshes the own page and sends only the chosen submission ID');
 mode='pending';await click(button(copy.refresh));const oldResponse=deferred;items=[{...visit(other),review:'B private fictional account content.'}];mode='success';await render({submissionId:null,account:{email:'fixture-b@example.test',displayName:'Fixture B',provider:'E-Mail'}});
 await act(async()=>oldResponse(Response.json({visits:[{...visit(id),review:'A private stale fictional account content.'}],nextCursor:null})));
 check(document.querySelectorAll('.visit').length===1&&document.body.textContent.includes('B private fictional account content.')&&!document.body.textContent.includes('A private stale fictional account content.'),'Changing the account clears history and ignores an old in-flight private response');
 const beforeGuest=requests.length;await render({signedIn:false});check(requests.length===beforeGuest&&!document.querySelector('.visit')&&document.querySelector('.login-prompt a').getAttribute('href')==='/sq/anmelden?weiter='+encodeURIComponent('/sq/bewertungen?einreichung='+id),'Signing out exposes only existing sign-in and performs no private history fetch');
 console.log(JSON.stringify({ownReviewsUiChecksPassed:passed,realAccounts:false,realEvidence:false}));
}finally{await act(async()=>root.unmount());dom.window.close();}
