"use client";
import {useState,type FormEvent} from "react";
import {Mail,LockKeyhole,LoaderCircle,ShieldCheck} from "lucide-react";
import {SiteHeader} from "@/components/site-header";
import type {AccountIdentity} from "@/components/account-storage-notice";
export type AuthScreen="login"|"register"|"recovery"|"reset";
const headings:Record<AuthScreen,string>={login:"Willkommen zurück.",register:"Dein Konto. Deine Bewertungen.",recovery:"Wieder Zugang bekommen.",reset:"Ein neues Passwort setzen."};
export default function AuthForm({screen,ready,isOwner,returnTo,errorHint,notice,account}:{account:AccountIdentity|null;screen:AuthScreen;ready:boolean;isOwner:boolean;returnTo:string;errorHint?:string;notice?:string}){
 const [error,setError]=useState(errorHint??""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);if(["register","reset"].includes(screen)&&f.get("password")!==f.get("passwordRepeat")){setError("Die beiden Passwörter stimmen nicht überein.");return;}setBusy(true);setError("");try{const r=await fetch(`/api/auth/${screen}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:f.get("email"),name:f.get("name"),password:f.get("password"),returnTo})});const d=await r.json() as {error?:string;message?:string;returnTo?:string};if(!r.ok)throw Error(d.error);if(d.returnTo)window.location.assign(d.returnTo);else setMessage(d.message??"Anfrage eingereicht.");}catch(e){setError(e instanceof Error?e.message:"Bitte versuche es erneut.");}finally{setBusy(false);}}
 return <><SiteHeader account={account} isAdmin={isOwner} section="Konto"/><main className="auth-page"><section className="auth-card"><div className="auth-icon"><ShieldCheck size={25}/></div><span className="eyebrow">DEIN PERSÖNLICHER ZUGANG</span><h1>{headings[screen]}</h1><p>{screen==="register"?"Deine Bewertungen – in jedem Browser.":screen==="recovery"?"Du erhältst einen Link zum Zurücksetzen.":screen==="reset"?"Wähle ein neues Passwort für dein Riparim-Konto.":"Melde dich an, um deine Bewertungen zu sehen."}</p>
 {notice&&<p className="admin-feedback" role="status">{notice}</p>}{!ready?<div className="auth-setup-needed"><h2>E-Mail-Anmeldung wird eingerichtet.</h2><p>Die Registrierung startet nach Einrichtung des E-Mail-Versands.</p>{isOwner&&<a className="primary" href="/verwaltung/anmeldung">Login & Registrierung einrichten</a>}<a className="outline" href={`/signin-with-chatgpt?return_to=${encodeURIComponent(returnTo)}`} target="_top">Bestehenden ChatGPT-Zugang nutzen</a></div>:message?<div className="auth-success" role="status"><Mail size={28}/><p>{message}</p><a className="outline" href={`/anmelden?weiter=${encodeURIComponent(returnTo)}`}>Zur Anmeldung</a></div>:<form onSubmit={submit} className="journey-form">
 {screen==="register"&&<label>Dein Name <span>(optional)</span><input name="name" autoComplete="name" maxLength={80}/></label>}{screen!=="reset"&&<label>E-Mail-Adresse<input name="email" type="email" autoComplete="email" required maxLength={254} placeholder="name@beispiel.de"/></label>}{screen!=="recovery"&&<label>Passwort<input name="password" type="password" autoComplete={screen==="login"?"current-password":"new-password"} required minLength={screen==="login"?1:12} maxLength={128}/>{screen!=="login"&&<span>12 bis 128 Zeichen, gern ein langer persönlicher Satz.</span>}</label>}{["register","reset"].includes(screen)&&<label>Passwort wiederholen<input name="passwordRepeat" type="password" autoComplete="new-password" required minLength={12} maxLength={128}/></label>}{error&&<p className="error" role="alert">{error}</p>}<button className="primary" disabled={busy} type="submit">{busy?<><LoaderCircle className="spin" size={17}/>Wird verarbeitet …</>:screen==="login"?"Anmelden":screen==="register"?"Konto erstellen":screen==="recovery"?"Link zum Zurücksetzen senden":"Neues Passwort speichern"}</button>{screen==="login"&&<a className="text-action" href="/passwort-vergessen">Passwort vergessen?</a>}</form>}
 {ready&&!message&&<p className="auth-switch">{screen==="login"?<>Noch kein Konto? <a href={`/registrieren?weiter=${encodeURIComponent(returnTo)}`}>Registrieren</a></>:screen==="register"?<>Schon ein Konto? <a href={`/anmelden?weiter=${encodeURIComponent(returnTo)}`}>Anmelden</a></>:<a href="/anmelden">Zur Anmeldung</a>}</p>}<div className="auth-privacy"><LockKeyhole size={16}/><p>Deine Nachweise bleiben privat und deinem Konto zugeordnet.</p></div></section></main></>;
}
