"use client";
import {Brand} from "@/components/brand";
import {useState,useEffect,useCallback} from "react";
import {Wrench,MapPin,Search,ShieldCheck,Star,CarFront,Globe,Check,MessageCircle,FileCheck2,Phone,RefreshCw} from "lucide-react";
import {SiteHeader} from "@/components/site-header";
import {Picker} from "@/components/picker";
import type {AccountIdentity} from "@/components/account-storage-notice";
import {DetailSearch,Profile,VisitForm,MyVisits,type SearchContext,type Visit} from "./journeys";
import {ModalContent} from "@/components/modal-shell";
import {Dialog} from "@/components/ui/dialog";
import {cities,services,findWorkshops,type Workshop} from "@/lib/workshops";

type Props={initialWorkshops:Workshop[];initialError:string;signedIn:boolean;account:AccountIdentity|null;isAdmin:boolean};
export default function Finder({initialWorkshops,initialError,signedIn,account,isAdmin}:Props){
 const [directory,setDirectory]=useState(initialWorkshops),[error,setError]=useState(initialError),[loading,setLoading]=useState(false);
 const [service,setService]=useState(services[0]),[city,setCity]=useState(cities[0]),[selected,setSelected]=useState<Workshop|null>(null),[info,setInfo]=useState(false),[searched,setSearched]=useState(false);
 const [detailed,setDetailed]=useState(false),[context,setContext]=useState<SearchContext|null>(null),[visitOpen,setVisitOpen]=useState(false),[visitWorkshop,setVisitWorkshop]=useState<Workshop|null>(null),[existingVisit,setExistingVisit]=useState<Visit|null>(null),[myVisits,setMyVisits]=useState(false),[language,setLanguage]=useState("Alle Sprachen"),[sort,setSort]=useState("Passung zuerst");
 const result=findWorkshops(directory,service,city,context?.brand??"Alle Marken",context?.radius??0,language,context?.additionalCity??"").sort((a,b)=>sort==="Geprüfte Bewertung"?(b.rating??0)-(a.rating??0)||b.count-a.count:sort==="Name A–Z"?a.name.localeCompare(b.name):Number(b.services[0]===service)-Number(a.services[0]===service));
 const shown=searched?result:result.slice(0,6);
 const refresh=useCallback(async()=>{setLoading(true);try{const r=await fetch("/api/workshops");const d=await r.json() as {workshops:Workshop[];error?:string};if(!r.ok)throw Error(d.error);setDirectory(d.workshops);setError("");}catch(e){setError(e instanceof Error?e.message:"Werkstätten konnten nicht geladen werden.");}finally{setLoading(false);}},[]);
 function search(){setSearched(true);setTimeout(()=>document.getElementById("werkstaetten")?.scrollIntoView({behavior:"smooth",block:"start"}),30);}
 function startVisit(w:Workshop|null=null,v:Visit|null=null){setVisitWorkshop(w);setExistingVisit(v);setVisitOpen(true);}
 function applyContext(c:SearchContext){setContext(c);setCity(c.city);setService(c.service);search();}
 function clearPrivateView(){const u=new URL(window.location.href);u.searchParams.delete("nachweis");u.searchParams.delete("besuche");window.history.replaceState(null,"",u);}
 function openProfile(w:Workshop){setSelected(w);const u=new URL(window.location.href);u.searchParams.set("werkstatt",w.id);window.history.pushState(null,"",u);}
 function closeProfile(){setSelected(null);const u=new URL(window.location.href);u.searchParams.delete("werkstatt");window.history.pushState(null,"",u);}
 useEffect(()=>{const sync=()=>{const p=new URLSearchParams(window.location.search),id=p.get("werkstatt");setSelected(directory.find(w=>w.id===id)??null);if(p.get("besuche"))setMyVisits(true);if(p.get("nachweis")){setVisitWorkshop(directory.find(w=>w.id===p.get("nachweis"))??null);setVisitOpen(true);}};sync();window.addEventListener("popstate",sync);return()=>window.removeEventListener("popstate",sync);},[directory]);
 useEffect(()=>{const mc=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>Promise<void>|void}}).modelContext;if(!mc?.registerTool)return;const lifecycle=new AbortController();void Promise.resolve(mc.registerTool({name:"configure_workshop_search",title:"Werkstattsuche einstellen",description:"Set service and city filters in the published Kosovo workshop directory. Returns source-backed business records. Does not contact a workshop, send a request, or book a repair.",inputSchema:{type:"object",properties:{service:{type:"string",enum:services},city:{type:"string",enum:cities}},required:["service","city"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},async execute(input:unknown){if(!input||typeof input!=="object")throw Error("Expected search filters");const f=input as {service:string;city:string};if(!services.includes(f.service)||!cities.includes(f.city)||Object.keys(f).some(k=>!["service","city"].includes(k)))throw Error("Invalid service or city");setContext(null);setLanguage("Alle Sprachen");setService(f.service);setCity(f.city);setSearched(true);await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));return {workshops:findWorkshops(directory,f.service,f.city).map(w=>({id:w.id,name:w.name,city:w.city,reviewCount:w.count}))};}},{signal:lifecycle.signal})).catch(e=>console.warn("WebMCP registration",e));return()=>lifecycle.abort();},[directory]);
 const reset=()=>{setService(services[0]);setCity(cities[0]);setLanguage("Alle Sprachen");setContext(null);};
 return <>
 <SiteHeader account={account} isAdmin={isAdmin} onVisits={()=>setMyVisits(true)} onNewVisit={()=>startVisit()}/>
 <main>
 <div className="hero-band"><section className="hero wrap" aria-labelledby="hero-title"><div className="hero-copy"><span className="hero-kicker"><MapPin size={15}/> Werkstattsuche in Kosovo</span><h1 id="hero-title">Dein Auto.<br/><span>Deine Werkstatt.</span></h1><p>Leistungen vergleichen. Erfahrungen prüfen.<br className="desktop-break"/> Direkt Kontakt aufnehmen.</p><div className="hero-points"><span><FileCheck2 size={17}/> Quellen im Profil</span><span><ShieldCheck size={17}/> Bewertungen nach Besuchsprüfung</span></div></div><figure className="hero-visual"><img src="/workshop.jpg" width="1536" height="1024" fetchPriority="high" alt="Symbolbild: Fahrzeug auf einer Hebebühne in einer hellen Werkstatt"/><figcaption className="image-label">Symbolbild</figcaption><div className="image-label-card"><Phone size={19}/><strong>Direkter Kontakt. Deine Entscheidung.</strong></div></figure></section></div>
 <div className="search-band"><section id="suche" className="search-section wrap" aria-label="Werkstattsuche"><div className="search-tabs"><span className="search-tab active"><Search size={17}/> Schnellsuche</span><button onClick={()=>setDetailed(true)}><CarFront size={18}/> Mit Fahrzeug & Problem</button></div><form className="search-box" onSubmit={e=>{e.preventDefault();search();}}><label><span><Wrench size={16}/> Leistung</span><Picker value={service} onChange={v=>{setService(v);setContext(null);}} values={services} label="Leistung"/></label><label><span><MapPin size={16}/> Ort</span><Picker value={city} onChange={v=>{setCity(v);setContext(null);}} values={cities} label="Ort"/></label><button type="submit" className="primary search-button"><Search size={18}/> Werkstätten finden</button></form><div className="popular" aria-label="Häufig gesuchte Leistungen">{services.slice(1,4).map(s=><button key={s} onClick={()=>{setService(s);setContext(null);setSearched(true);}}>{s}</button>)}</div></section></div>
 <div className="results-band"><section id="werkstaetten" className="results-section wrap" aria-labelledby="results-title"><div className="section-top"><div className="section-heading"><h2 id="results-title">{searched?`${result.length} ${result.length===1?"Werkstatt":"Werkstätten"} gefunden`:"Werkstätten entdecken"}</h2>{searched&&<p>{service} · {city}</p>}</div><span className="directory-count">{directory.length} Standorte</span></div>
 {error&&<div className="error" role="alert">{error} <button className="text-action" disabled={loading} onClick={()=>void refresh()}><RefreshCw size={14}/> Erneut laden</button></div>}
 {context&&<div className="context-summary"><CarFront size={20}/><div><strong>{context.brand} {context.model} {context.year&&`· ${context.year}`}</strong><p>{context.problem}</p><span>{context.additionalCity&&`${context.additionalCity} · `}{context.radius>0&&`${context.radius} km Luftlinie · `}{(context.from||context.to)&&`Reise: ${context.from||"offen"} bis ${context.to||"offen"}`}</span></div><button onClick={()=>setDetailed(true)}>Suchkontext ändern</button></div>}
 {searched&&<><div className="results-filters"><div><Globe size={16}/><Picker value={language} onChange={setLanguage} values={["Alle Sprachen","Albanisch","Deutsch","Englisch"]} label="Veröffentlichte Beratungssprache"/></div><div><Picker value={sort} onChange={setSort} values={["Passung zuerst","Geprüfte Bewertung","Name A–Z"]} label="Ergebnisse sortieren"/></div><button onClick={reset}>Filter zurücksetzen</button></div><p className="results-note">Leistungen laut Betriebsquelle. Fahrzeug und Termin direkt klären.</p></>}
 <div className="cards">{shown.map(w=><article className="workshop-card" key={w.id}><div className="card-top"><span className={`workshop-mark ${w.color}`}>{w.initials}<Wrench size={17}/></span><span className="specialty">{w.specialty}</span></div><div className="card-heading"><h3><a href={`/?werkstatt=${encodeURIComponent(w.id)}`} onClick={e=>{e.preventDefault();openProfile(w);}}>{w.name}</a></h3><span><MapPin size={14}/>{w.city}</span></div><div className={`rating ${w.count===0?"unrated":""}`}>{w.rating!==null?<><Star size={16} fill="currentColor"/><strong>{w.rating.toLocaleString("de-DE",{maximumFractionDigits:1,minimumFractionDigits:1})}</strong><span>{w.count} {w.count===1?"geprüfter Besuch":"geprüfte Besuche"}</span></>:<><MessageCircle size={16}/><span>Noch keine geprüften Bewertungen</span></>}</div><div className="brand-tags">{w.brands.length?w.brands.slice(0,4).map(b=><span key={b}>{b}</span>):<span>Marken auf Anfrage</span>}{w.brands.length>4&&<span>+{w.brands.length-4}</span>}</div><div className="card-services">{w.serviceDetails.slice(0,2).map(s=><span key={s}><Check size={14}/><span>{s}</span></span>)}</div><div className="card-footer"><span><FileCheck2 size={14}/>Quelle im Profil</span><a className="profile-link" href={`/?werkstatt=${encodeURIComponent(w.id)}`} onClick={e=>{e.preventDefault();openProfile(w);}}>Profil ansehen</a></div></article>)}</div>
 {!error&&shown.length===0&&<div className="empty"><Search size={30}/><h3>{directory.length?"Für diese Auswahl ist noch kein Betrieb dabei.":"Das Verzeichnis startet gerade."}</h3><p>{language!=="Alle Sprachen"?"Beratungssprachen sind noch nicht für alle Betriebe belegt. Kläre die Sprache direkt oder entferne den Sprachfilter.":"Das Verzeichnis wird schrittweise ergänzt. Probiere einen anderen Ort oder einen größeren Umkreis."}</p><button className="outline" onClick={reset}>Filter zurücksetzen</button>{isAdmin&&<a className="text-action" href="/verwaltung">Werkstätten verwalten</a>}</div>}
 {!searched&&directory.length>6&&<button className="all-button" onClick={search}>Alle {directory.length} Werkstätten anzeigen</button>}</section></div>
 <section id="so-gehts" className="trust-section wrap" aria-labelledby="trust-title"><figure className="trust-visual"><img src="/diagnostics.jpg" width="1536" height="1024" loading="lazy" alt="Symbolbild: Mechaniker prüft ein Fahrzeug mit einem Diagnosegerät"/><figcaption className="image-label">Symbolbild</figcaption></figure><div className="trust-content"><div className="trust-title"><span className="hero-kicker"><ShieldCheck size={16}/> Geprüfte Bewertungen</span><h2 id="trust-title">Finden. Kontaktieren. Bewerten.</h2></div><div className="trust-steps"><div><span>1</span><div><h3>Werkstatt auswählen</h3><p>Leistung, Standort und Erfahrungen vergleichen.</p></div></div><div><span>2</span><div><h3>Direkt Kontakt aufnehmen</h3><p>Arbeit, Kosten und Termin persönlich klären.</p></div></div><div><span>3</span><div><h3>Nach dem Besuch bewerten</h3><p>Bewertung und Nachweis einreichen. Nach Freigabe sichtbar.</p></div></div></div><button className="text-action" onClick={()=>setInfo(true)}>Mehr zu Quellen & Nachweisen</button></div></section>
 </main><div className="footer-band"><footer className="footer wrap"><Brand/><button onClick={()=>setInfo(true)}>Quellen & Datenschutz</button><span>© 2026 Mjeshtër</span></footer></div>
 <Dialog open={info} onOpenChange={setInfo}><ModalContent className="info-modal" title="Quellen & Nachweise" description="Was geprüft wird – und was privat bleibt."><section><h3>Betriebsangaben</h3><p>Kontakt, Standort und Leistungen stammen aus den im Profil verlinkten offiziellen Quellen. Der Quellenabgleich ist keine Qualitätsprüfung. Markenautorisierungen nennen wir nur mit Beleg.</p></section><section><h3>Geprüfte Besuche</h3><p>Rechnung, Servicebeleg oder andere nachvollziehbare Unterlagen werden privat geprüft. Eine Werkstattbestätigung ist nicht nötig. Bewertung und Nachweis reichst du gemeinsam ein. Nach Freigabe wird die Bewertung veröffentlicht. Die Prüfung ist keine Garantie für künftige Arbeiten.</p></section><section><h3>Direkter Kontakt</h3><p>Du kontaktierst den Betrieb selbst. Ein Kontaktklick belegt keine Nachricht und keinen Besuch. Deine Suchangaben sind privat; sie sind keine Ausschreibung und kein Auftrag.</p></section><section><h3>Deine Daten</h3><p>Eingereichte Besuche und Belege werden auf dem Server zu deinem Konto gespeichert. Sie bleiben beim Browserwechsel erhalten. Nur du und die zuständige Prüfung können die Nachweise sehen.</p><p>Bei Veröffentlichung werden Anzeigename, Fahrzeug, Arbeit, Datum, Sterne und Bewertung sichtbar. Unter „Meine Bewertungen“ kannst du Nachweis, Besuch und Bewertung löschen. Suchangaben bleiben nur im Arbeitsspeicher.</p></section><p className="help">Das Verzeichnis wird schrittweise ergänzt. Abdeckung und Nachfrage werden weiter geprüft.</p></ModalContent></Dialog>
 <DetailSearch open={detailed} onClose={()=>setDetailed(false)} onSearch={applyContext}/>
 <Profile workshop={selected} onClose={closeProfile} onVisit={startVisit} context={context}/>
 <VisitForm onDone={()=>setMyVisits(true)} open={visitOpen} onClose={()=>{clearPrivateView();setVisitOpen(false);void refresh();}} workshop={visitWorkshop} directory={directory} signedIn={signedIn} account={account} existing={existingVisit}/>
 <MyVisits open={myVisits} onClose={()=>{clearPrivateView();setMyVisits(false);void refresh();}} directory={directory} signedIn={signedIn} account={account} isAdmin={isAdmin} onResubmit={v=>{clearPrivateView();setMyVisits(false);startVisit(directory.find(w=>w.id===v.workshop)??null,v);}}/>
 </>;
}
