"use client";
import { useState, useEffect } from "react";
import { Wrench, MapPin, Search, ShieldCheck, Star, CarFront, Globe, Check, MessageCircle, FileCheck2, ChevronRight, Phone } from "lucide-react";
import { Picker } from "@/components/picker";
import { DetailSearch, Profile, VisitForm, MyVisits, type SearchContext } from "./journeys";
import { Dialog, DialogContent, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { cities, services, workshops, findWorkshops, type Workshop } from "@/lib/workshops";

export default function Finder(){
 const [service,setService]=useState(services[0]);const [city,setCity]=useState(cities[0]);const [selected,setSelected]=useState<Workshop|null>(null);const [info,setInfo]=useState(false);const [searched,setSearched]=useState(false);
 const [detailed,setDetailed]=useState(false),[context,setContext]=useState<SearchContext|null>(null),[visitOpen,setVisitOpen]=useState(false),[visitWorkshop,setVisitWorkshop]=useState<Workshop|null>(null),[myVisits,setMyVisits]=useState(false),[language,setLanguage]=useState("Alle Sprachen"),[sort,setSort]=useState("Spezialisierung zuerst");
 const result=findWorkshops(service,city,context?.brand??"Alle Marken",context?.radius??0,language,context?.additionalCity??"").sort((a,b)=>sort==="Beispielbewertung"?b.rating-a.rating:sort==="Name A–Z"?a.name.localeCompare(b.name):Number(b.services[0]===service)-Number(a.services[0]===service));const shown=searched?result:result.slice(0,3);
 function startVisit(w:Workshop|null=null){setVisitWorkshop(w);setVisitOpen(true);}
 function applyContext(c:SearchContext){setContext(c);setCity(c.city);setService(c.service);setSearched(true);setTimeout(()=>document.getElementById("werkstaetten")?.scrollIntoView({behavior:"smooth"}),50);}
 useEffect(()=>{const mc=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>Promise<void>|void}}).modelContext;if(!mc?.registerTool)return;const lifecycle=new AbortController();const afterRender=()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));void Promise.resolve(mc.registerTool({name:"configure_workshop_search",title:"Werkstattsuche einstellen",description:"Filter the fictional pilot workshop directory by service and city and update the visible results. Does not send a message, submit a request, or book a repair.",inputSchema:{type:"object",properties:{service:{type:"string",enum:services},city:{type:"string",enum:cities}},required:["service","city"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},async execute(input:unknown){if(!input||typeof input!=="object")throw Error("Expected search filters");const f=input as {service:string;city:string};if(!services.includes(f.service)||!cities.includes(f.city)||Object.keys(f).some(k=>!["service","city"].includes(k)))throw Error("Invalid service or city");setContext(null);setLanguage("Alle Sprachen");setService(f.service);setCity(f.city);setSearched(true);await afterRender();return {demo:true,workshops:findWorkshops(f.service,f.city).map(w=>({id:w.id,name:w.name,city:w.city}))};}}, {signal:lifecycle.signal})).catch(e=>console.warn("WebMCP unavailable",e));return()=>lifecycle.abort();},[]);
 function search(){setSearched(true);setTimeout(()=>document.getElementById("werkstaetten")?.scrollIntoView({behavior:"smooth",block:"start"}),50);}
 return <>
 <div className="pilotbar"><span>PILOTVERSION</span> Entdecke die Suche mit Beispieldaten. <button onClick={()=>setInfo(true)}>Was bedeutet das?</button></div>
 <header className="header wrap"><a className="brand" href="/"><span className="brandmark"><Wrench size={21}/></span>mjeshtër<span className="brandperiod">.</span></a><nav><a className="navactive" href="#werkstaetten">Werkstätten finden</a><button onClick={()=>setInfo(true)}>So entsteht Vertrauen</button></nav><div className="header-right"><span><Globe size={16}/> DE</span><button className="my-visits-link" onClick={()=>setMyVisits(true)}>Meine Besuche</button><button className="outline small" onClick={()=>startVisit()}><FileCheck2 size={16}/> Besuch bewerten</button></div></header>
 <main>
 <section className="hero wrap"><div className="hero-copy"><div className="eyebrow"><span className="small-rule"/> FÜR DEIN AUTO. FÜR DEINE ZEIT IN KOSOVO.</div><h1>Gute Arbeit.<br/>Ein gutes Gefühl.</h1><p>Finde eine passende Werkstatt in Kosovo – anhand nachvollziehbarer Kundenerfahrungen statt auf gut Glück.</p><div className="hero-points"><span><ShieldCheck size={18}/> Erfahrungen mit Besuchsnachweis</span><span><MessageCircle size={18}/> Direkt mit der Werkstatt sprechen</span></div></div><div className="hero-visual"><img src="/workshop.jpg" alt="Symbolbild einer hellen Autowerkstatt mit Fahrzeug auf einer Hebebühne"/><span className="image-caption">Gute Arbeit beginnt mit der richtigen Wahl.</span><span className="image-label">Symbolbild</span><div className="image-label-card"><ShieldCheck size={22}/><div><strong>Vertrauen braucht Einblick.</strong><span>Arbeit, Erfahrung, Spezialisierung.</span></div></div></div></section>
 <section className="search-section wrap" aria-label="Werkstattsuche"><div className="search-tabs"><span className="search-tab active"><Search size={17}/> Schnell suchen</span><button onClick={()=>setDetailed(true)}><CarFront size={18}/> Suche mit Fahrzeug & Problem</button><span className="search-side">Deine Werkstatt. Deine Entscheidung.</span></div><div className="search-box"><label><span><Wrench size={16}/> Was soll gemacht werden?</span><Picker value={service} onChange={v=>{setService(v);setContext(null);}} values={services} label="Leistung"/></label><label><span><MapPin size={16}/> Wo in Kosovo?</span><Picker value={city} onChange={v=>{setCity(v);setContext(null);}} values={cities} label="Ort"/></label><button className="primary search-button" onClick={search}><Search size={18}/> Werkstätten finden</button></div><div className="popular"><span>Schnellauswahl:</span>{services.slice(1,4).map(s=><button key={s} onClick={()=>{setService(s);setContext(null);setSearched(true);}}>{s}</button>)}</div></section>
 <section id="werkstaetten" className="results-section wrap"><div className="section-top"><div className="section-heading"><span className="eyebrow">PASSEND STATT BELIEBIG</span><h2>{searched?`${result.length} passende ${result.length===1?"Werkstatt":"Werkstätten"}`:"Werkstätten kennenlernen"}</h2><p>{searched?`${service} · ${city}`:"Spezialisierungen entdecken. Erfahrungen einordnen. Selbst entscheiden."}</p></div><span className="demo-tag">Beispielprofile</span></div>{context&&<div className="context-summary"><CarFront size={20}/><div><strong>{context.brand} {context.model} {context.year&&`· ${context.year}`}</strong><p>{context.problem}</p><span>{context.additionalCity&&`${context.additionalCity} · `}{context.radius>0&&`${context.radius} km Luftlinie · `}{(context.from||context.to)&&`Reise: ${context.from||"offen"} bis ${context.to||"offen"}`}</span></div><button onClick={()=>setDetailed(true)}>Suchkontext ändern</button></div>}{searched&&<div className="results-filters"><div><Globe size={16}/><Picker value={language} onChange={setLanguage} values={["Alle Sprachen","Albanisch","Deutsch","Englisch"]} label="Kommunikationssprache"/></div><div><Picker value={sort} onChange={setSort} values={["Spezialisierung zuerst","Beispielbewertung","Name A–Z"]} label="Ergebnisse sortieren"/></div><button onClick={()=>{setService(services[0]);setCity(cities[0]);setLanguage("Alle Sprachen");setContext(null);}}>Filter zurücksetzen</button></div>}<div className="cards">{shown.map(w=><article className="workshop-card" key={w.id}><div className="card-top"><span className={`workshop-mark ${w.color}`}>{w.initials}<Wrench size={17}/></span><span className="specialty">{w.specialty}</span></div><div className="card-heading"><h3>{w.name}</h3><span><MapPin size={14}/>{w.city}</span></div><div className="rating"><Star size={16} fill="currentColor"/><strong>{w.rating.toFixed(1)}</strong><span>{w.count} Beispielbewertungen</span></div><div className="brand-tags">{w.brands.map(b=><span key={b}>{b}</span>)}</div><div className="card-services">{w.services.slice(0,2).map(s=><span key={s}><Check size={14}/>{s}</span>)}</div><div className="card-footer"><span><Globe size={14}/>{w.languages.join(" · ")}</span><button onClick={()=>setSelected(w)}>Profil ansehen<ChevronRight size={16}/></button></div></article>)}</div>{shown.length===0&&<div className="empty"><Search size={30}/><h3>Hier ist noch kein Beispielprofil dabei.</h3><p>Probiere einen anderen Ort oder eine andere Leistung.</p><button className="outline" onClick={()=>{setService(services[0]);setCity(cities[0]);setLanguage("Alle Sprachen");setContext(null);}}>Filter zurücksetzen</button></div>}{!searched&&<button className="all-button" onClick={search}>Alle {workshops.length} Beispielwerkstätten entdecken</button>}</section>
 <section className="trust-section wrap"><div className="trust-title"><ShieldCheck size={28}/><h2>Vertrauen entsteht<br/>nach dem Besuch.</h2><p>Ein Klick ist noch keine Reparatur. Deshalb beginnt eine nachvollziehbare Bewertung mit einem tatsächlichen Werkstattbesuch.</p><button onClick={()=>setInfo(true)}>So prüfen wir Erfahrungen<ChevronRight size={16}/></button></div><div className="trust-steps"><div><span>01</span><div><h3>Passende Werkstatt auswählen</h3><p>Leistungen, Standort und ähnliche Arbeiten vergleichen.</p></div></div><div><span>02</span><div><h3>Persönlich Kontakt aufnehmen</h3><p>Du klärst Arbeit und Termin direkt mit der Werkstatt.</p></div></div><div><span>03</span><div><h3>Besuch nachweisen & bewerten</h3><p>Nach der Prüfung wird deine Reparaturerfahrung sichtbar.</p></div></div></div></section>
 </main><footer className="footer wrap"><a className="brand" href="/">mjeshtër<span className="brandperiod">.</span></a><p>Gute Werkstätten finden. Mit gutem Grund.</p><button onClick={()=>setInfo(true)}>Über den Pilot & Datenschutz</button><span>© 2026 Mjeshtër</span></footer>
 <Dialog open={info} onOpenChange={setInfo}><DialogContent className="modal"><DialogTitle>Ein transparenter Start.</DialogTitle><DialogDescription>Diese private Pilotversion zeigt die Suche mit Beispieldaten.</DialogDescription><p>Alle Werkstätten, Bewertungen und Erfahrungen sind fiktive Beispiele. Echte Kontaktdaten werden nach Prüfung ergänzt. Die Veröffentlichung ist zunächst privat und nur für dich zugänglich.</p><p>Ein Kontaktklick beweist weder eine gesendete Nachricht noch einen Besuch. Als privater Besuchsnachweis kommen etwa eine Rechnung, ein Servicebeleg oder andere nachvollziehbare Unterlagen infrage. Eine Werkstattbestätigung ist nicht die einzige Möglichkeit.</p><p>Suchangaben bleiben nur während deiner Sitzung im Arbeitsspeicher. Besuchsnachweise werden privat gespeichert und sind nur für die einreichende Person und die zuständige Prüfung zugänglich. Im Profil erscheinen erst nach bestätigtem Besuch ausdrücklich veröffentlichte Bewertungen. Unter „Meine Besuche“ kannst du einen Nachweis samt Bewertung löschen.</p><p>Vorhandene Alternativen und die tatsächliche Nachfrage werden im Pilot geprüft. Geprüfte Besuche sind keine Garantie für die Qualität einer zukünftigen Reparatur.</p></DialogContent></Dialog>
 <DetailSearch open={detailed} onClose={()=>setDetailed(false)} onSearch={applyContext}/>
 <Profile workshop={selected} onClose={()=>setSelected(null)} onVisit={startVisit} context={context}/>
 <VisitForm open={visitOpen} onClose={()=>setVisitOpen(false)} workshop={visitWorkshop}/>
 <MyVisits open={myVisits} onClose={()=>setMyVisits(false)}/>
 </>;
}
