"use client";
import {useState,useEffect,useCallback} from "react";
import {Wrench,MapPin,Search,ShieldCheck,Star,CarFront,Globe,Check,MessageCircle,FileCheck2,Phone,RefreshCw} from "lucide-react";
import {Picker} from "@/components/picker";
import {DetailSearch,Profile,VisitForm,MyVisits,type SearchContext,type Visit} from "./journeys";
import {Dialog,DialogContent,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {cities,services,findWorkshops,type Workshop} from "@/lib/workshops";

type Props={initialWorkshops:Workshop[];initialError:string;signedIn:boolean;isAdmin:boolean};
export default function Finder({initialWorkshops,initialError,signedIn,isAdmin}:Props){
 const [directory,setDirectory]=useState(initialWorkshops),[error,setError]=useState(initialError),[loading,setLoading]=useState(false);
 const [service,setService]=useState(services[0]),[city,setCity]=useState(cities[0]),[selected,setSelected]=useState<Workshop|null>(null),[info,setInfo]=useState(false),[searched,setSearched]=useState(false);
 const [detailed,setDetailed]=useState(false),[context,setContext]=useState<SearchContext|null>(null),[visitOpen,setVisitOpen]=useState(false),[visitWorkshop,setVisitWorkshop]=useState<Workshop|null>(null),[existingVisit,setExistingVisit]=useState<Visit|null>(null),[myVisits,setMyVisits]=useState(false),[language,setLanguage]=useState("Alle Sprachen"),[sort,setSort]=useState("Passung zuerst");
 const result=findWorkshops(directory,service,city,context?.brand??"Alle Marken",context?.radius??0,language,context?.additionalCity??"").sort((a,b)=>sort==="Geprüfte Bewertung"?(b.rating??0)-(a.rating??0)||b.count-a.count:sort==="Name A–Z"?a.name.localeCompare(b.name):Number(b.services[0]===service)-Number(a.services[0]===service));
 const shown=searched?result:result.slice(0,3);
 const refresh=useCallback(async()=>{setLoading(true);try{const r=await fetch("/api/workshops");const d=await r.json() as {workshops:Workshop[];error?:string};if(!r.ok)throw Error(d.error);setDirectory(d.workshops);setError("");}catch(e){setError(e instanceof Error?e.message:"Werkstätten konnten nicht geladen werden.");}finally{setLoading(false);}},[]);
 function search(){setSearched(true);setTimeout(()=>document.getElementById("werkstaetten")?.scrollIntoView({behavior:"smooth",block:"start"}),30);}
 function startVisit(w:Workshop|null=null,v:Visit|null=null){setVisitWorkshop(w);setExistingVisit(v);setVisitOpen(true);}
 function applyContext(c:SearchContext){setContext(c);setCity(c.city);setService(c.service);search();}
 function clearPrivateView(){const u=new URL(window.location.href);u.searchParams.delete("nachweis");u.searchParams.delete("besuche");window.history.replaceState(null,"",u);}
 function openProfile(w:Workshop){setSelected(w);const u=new URL(window.location.href);u.searchParams.set("werkstatt",w.id);window.history.pushState(null,"",u);}
 function closeProfile(){setSelected(null);const u=new URL(window.location.href);u.searchParams.delete("werkstatt");window.history.pushState(null,"",u);}
 useEffect(()=>{const sync=()=>{const p=new URLSearchParams(window.location.search),id=p.get("werkstatt");setSelected(directory.find(w=>w.id===id)??null);if(p.get("besuche"))setMyVisits(true);if(p.get("nachweis")){setVisitWorkshop(directory.find(w=>w.id===p.get("nachweis"))??null);setVisitOpen(true);}};sync();window.addEventListener("popstate",sync);return()=>window.removeEventListener("popstate",sync);},[directory]);
 useEffect(()=>{const mc=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>Promise<void>|void}}).modelContext;if(!mc?.registerTool)return;const lifecycle=new AbortController();void Promise.resolve(mc.registerTool({name:"configure_workshop_search",title:"Werkstattsuche einstellen",description:"Set service and city filters in the published Kosovo workshop directory. Returns source-backed business records. Does not contact a workshop, send a request, or book a repair.",inputSchema:{type:"object",properties:{service:{type:"string",enum:services},city:{type:"string",enum:cities}},required:["service","city"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},async execute(input:unknown){if(!input||typeof input!=="object")throw Error("Expected search filters");const f=input as {service:string;city:string};if(!services.includes(f.service)||!cities.includes(f.city)||Object.keys(f).some(k=>!["service","city"].includes(k)))throw Error("Invalid service or city");setContext(null);setLanguage("Alle Sprachen");setService(f.service);setCity(f.city);setSearched(true);await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));return {workshops:findWorkshops(directory,f.service,f.city).map(w=>({id:w.id,name:w.name,city:w.city,reviewCount:w.count}))};}},{signal:lifecycle.signal})).catch(e=>console.warn("WebMCP registration",e));return()=>lifecycle.abort();},[directory]);
 const reset=()=>{setService(services[0]);setCity(cities[0]);setLanguage("Alle Sprachen");setContext(null);};
 return <>
 <div className="pilotbar"><span>FRÜHER START</span> Echte Betriebe. Transparente Quellen. Bewertungen nach geprüftem Besuch. <button onClick={()=>setInfo(true)}>So funktioniert’s</button></div>
 <header className="header wrap"><a className="brand" href="/"><span className="brandmark"><Wrench size={21}/></span>mjeshtër<span className="brandperiod">.</span></a><nav><a className="navactive" href="#werkstaetten">Werkstätten finden</a><button onClick={()=>setInfo(true)}>So entsteht Vertrauen</button></nav><div className="header-right"><span><Globe size={16}/> DE</span><button className="my-visits-link" onClick={()=>setMyVisits(true)}>Meine Besuche</button><button className="outline small" onClick={()=>startVisit()}><FileCheck2 size={16}/> Besuch bewerten</button></div></header>
 <main>
 <section className="hero wrap"><div className="hero-copy"><div className="eyebrow"><span className="small-rule"/> FÜR DEIN AUTO. FÜR DEINE ZEIT IN KOSOVO.</div><h1>Gute Arbeit.<br/>Ein gutes Gefühl.</h1><p>Finde eine passende Werkstatt in Kosovo – anhand von Spezialisierung, Standort und nachvollziehbaren Kundenerfahrungen.</p><div className="hero-points"><span><ShieldCheck size={18}/> Nur Erfahrungen mit geprüftem Besuch</span><span><Phone size={18}/> Du kontaktierst die Werkstatt direkt</span></div></div><div className="hero-visual"><img src="/workshop.jpg" alt="Symbolbild einer Autowerkstatt mit Fahrzeug auf einer Hebebühne"/><span className="image-label">Symbolbild</span><div className="image-label-card"><ShieldCheck size={22}/><div><strong>Vertrauen braucht Einblick.</strong><span>Quellen, Leistungen, Erfahrungen.</span></div></div></div></section>
 <section className="search-section wrap" aria-label="Werkstattsuche"><div className="search-tabs"><span className="search-tab active"><Search size={17}/> Schnell suchen</span><button onClick={()=>setDetailed(true)}><CarFront size={18}/> Suche mit Fahrzeug & Problem</button><span className="search-side">Deine Werkstatt. Deine Entscheidung.</span></div><div className="search-box"><label><span><Wrench size={16}/> Was soll gemacht werden?</span><Picker value={service} onChange={v=>{setService(v);setContext(null);}} values={services} label="Leistung"/></label><label><span><MapPin size={16}/> Wo in Kosovo?</span><Picker value={city} onChange={v=>{setCity(v);setContext(null);}} values={cities} label="Ort"/></label><button className="primary search-button" onClick={search}><Search size={18}/> Werkstätten finden</button></div><div className="popular"><span>Schnellauswahl:</span>{services.slice(1,4).map(s=><button key={s} onClick={()=>{setService(s);setContext(null);setSearched(true);}}>{s}</button>)}</div></section>
 <section id="werkstaetten" className="results-section wrap"><div className="section-top"><div className="section-heading"><span className="eyebrow">PASSEND STATT BELIEBIG</span><h2>{searched?`${result.length} ${result.length===1?"Werkstatt":"Werkstätten"} für deine Suche`:"Werkstätten kennenlernen"}</h2><p>{searched?`${service} · ${city}`:"Betriebsangaben vergleichen. Erfahrungen einordnen. Selbst entscheiden."}</p></div><span className="demo-tag">{directory.length} veröffentlichte Betriebe</span></div>
 {error&&<div className="error" role="alert">{error} <button className="text-action" disabled={loading} onClick={()=>void refresh()}><RefreshCw size={14}/> Erneut laden</button></div>}
 {context&&<div className="context-summary"><CarFront size={20}/><div><strong>{context.brand} {context.model} {context.year&&`· ${context.year}`}</strong><p>{context.problem}</p><span>{context.additionalCity&&`${context.additionalCity} · `}{context.radius>0&&`${context.radius} km Luftlinie · `}{(context.from||context.to)&&`Reise: ${context.from||"offen"} bis ${context.to||"offen"}`}</span></div><button onClick={()=>setDetailed(true)}>Suchkontext ändern</button></div>}
 {searched&&<><div className="results-filters"><div><Globe size={16}/><Picker value={language} onChange={setLanguage} values={["Alle Sprachen","Albanisch","Deutsch","Englisch"]} label="Veröffentlichte Beratungssprache"/></div><div><Picker value={sort} onChange={setSort} values={["Passung zuerst","Geprüfte Bewertung","Name A–Z"]} label="Ergebnisse sortieren"/></div><button onClick={reset}>Filter zurücksetzen</button></div><p className="results-note">Die Auswahl beruht auf veröffentlichten Leistungen. Eignung für dein Fahrzeug und freie Termine klärst du direkt.</p></>}
 <div className="cards">{shown.map(w=><article className="workshop-card" key={w.id}><div className="card-top"><span className={`workshop-mark ${w.color}`}>{w.initials}<Wrench size={17}/></span><span className="specialty">{w.specialty}</span></div><div className="card-heading"><h3>{w.name}</h3><span><MapPin size={14}/>{w.city}</span></div><div className={`rating ${w.count===0?"unrated":""}`}>{w.rating!==null?<><Star size={16} fill="currentColor"/><strong>{w.rating.toLocaleString("de-DE",{maximumFractionDigits:1,minimumFractionDigits:1})}</strong><span>{w.count} {w.count===1?"geprüfter Besuch":"geprüfte Besuche"}</span></>:<><MessageCircle size={16}/><span>Noch keine geprüften Bewertungen</span></>}</div><div className="brand-tags">{w.brands.length?w.brands.slice(0,4).map(b=><span key={b}>{b}</span>):<span>Markeneignung direkt klären</span>}{w.brands.length>4&&<span>+{w.brands.length-4}</span>}</div><div className="card-services">{w.serviceDetails.slice(0,2).map(s=><span key={s}><Check size={14}/>{s}</span>)}</div><div className="card-footer"><span><FileCheck2 size={14}/>Betriebsangaben mit Quelle</span><a className="profile-link" href={`/?werkstatt=${encodeURIComponent(w.id)}`} onClick={e=>{e.preventDefault();openProfile(w);}}>Profil ansehen</a></div></article>)}</div>
 {!error&&shown.length===0&&<div className="empty"><Search size={30}/><h3>{directory.length?"Für diese Auswahl ist noch kein Betrieb dabei.":"Das Verzeichnis startet gerade."}</h3><p>{language!=="Alle Sprachen"?"Beratungssprachen sind noch nicht für alle Betriebe belegt. Kläre die Sprache direkt oder entferne den Sprachfilter.":"Das Verzeichnis wird schrittweise ergänzt. Probiere einen anderen Ort oder einen größeren Umkreis."}</p><button className="outline" onClick={reset}>Filter zurücksetzen</button>{isAdmin&&<a className="text-action" href="/verwaltung">Werkstätten verwalten</a>}</div>}
 {!searched&&directory.length>3&&<button className="all-button" onClick={search}>Alle {directory.length} Werkstätten entdecken</button>}</section>
 <section className="trust-section wrap"><div className="trust-title"><ShieldCheck size={28}/><h2>Vertrauen entsteht<br/>nach dem Besuch.</h2><p>Ein Kontaktklick ist noch keine Reparatur. Deshalb beginnt eine nachvollziehbare Bewertung mit einem tatsächlichen Werkstattbesuch.</p><button onClick={()=>setInfo(true)}>So prüfen wir Erfahrungen</button></div><div className="trust-steps"><div><span>01</span><div><h3>Passende Werkstatt auswählen</h3><p>Leistungen, Standort und ähnliche Arbeiten vergleichen.</p></div></div><div><span>02</span><div><h3>Persönlich Kontakt aufnehmen</h3><p>Du klärst Arbeit, Kosten und Termin direkt mit der Werkstatt.</p></div></div><div><span>03</span><div><h3>Besuch nachweisen & bewerten</h3><p>Nach der Prüfung kannst du deine Reparaturerfahrung veröffentlichen.</p></div></div></div></section>
 </main><footer className="footer wrap"><a className="brand" href="/">mjeshtër<span className="brandperiod">.</span></a><p>Gute Werkstätten finden. Mit gutem Grund.</p><button onClick={()=>setInfo(true)}>Daten & Nachweise</button>{isAdmin&&<a href="/verwaltung">Verwaltung</a>}{!signedIn&&<a href="/signin-with-chatgpt?return_to=%2F" target="_top">Anmelden</a>}<span>© 2026 Mjeshtër</span></footer>
 <Dialog open={info} onOpenChange={setInfo}><DialogContent className="modal"><DialogTitle>Woran du dich orientieren kannst.</DialogTitle><DialogDescription>Betriebsangaben und Besuchserfahrungen haben unterschiedliche Quellen.</DialogDescription><h3>Betriebsangaben mit Quelle</h3><p>Kontakt, Standort und veröffentlichte Leistungen stammen aus den im Profil verlinkten Unternehmens- oder Herstellerquellen. Das Prüfdatum bezeichnet den Quellenabgleich. Es ist keine unabhängige Qualitätsprüfung. Markenautorisierungen sind nur dann genannt, wenn die Quelle sie ausdrücklich nennt.</p><h3>Erfahrungen nach geprüftem Besuch</h3><p>Eine Rechnung, ein Servicebeleg oder andere nachvollziehbare Unterlagen werden privat und manuell geprüft. Eine Werkstattbestätigung ist nicht zwingend erforderlich. Erst nach bestätigtem Besuch kannst du eine reparaturbezogene Bewertung veröffentlichen. Eine bestätigte Erfahrung ist keine Garantie für die nächste Reparatur.</p><h3>Dein Kontakt bleibt deine Entscheidung</h3><p>Telefon und gegebenenfalls offiziell veröffentlichter WhatsApp-Kontakt führen direkt zum Betrieb. Ein Klick beweist keine gesendete Nachricht und keinen Besuch. Deine Suchangaben sind persönlicher Kontext, keine öffentliche Ausschreibung und kein Auftrag. Kein Betrieb muss sich bewerben oder ein Angebot schreiben.</p><h3>Private Nachweise</h3><p>Suchangaben bleiben während deiner Sitzung im Arbeitsspeicher. Belege und Prüfvermerke sind nur für die einreichende Person und die zuständige Prüfung zugänglich. Anzeigename, Fahrzeug, Arbeit, Besuchsdatum, Sterne und Text werden erst bei deiner Veröffentlichung im Profil sichtbar. Unter „Meine Besuche“ kannst du deinen Nachweis samt Bewertung löschen.</p><p className="help">Das Verzeichnis startet mit wenigen Betrieben. Abdeckung, vorhandene Alternativen und tatsächliche Nachfrage werden weiter geprüft.</p></DialogContent></Dialog>
 <DetailSearch open={detailed} onClose={()=>setDetailed(false)} onSearch={applyContext}/>
 <Profile workshop={selected} onClose={closeProfile} onVisit={startVisit} context={context}/>
 <VisitForm open={visitOpen} onClose={()=>{clearPrivateView();setVisitOpen(false);void refresh();}} workshop={visitWorkshop} directory={directory} signedIn={signedIn} existing={existingVisit}/>
 <MyVisits open={myVisits} onClose={()=>{clearPrivateView();setMyVisits(false);void refresh();}} directory={directory} signedIn={signedIn} onResubmit={v=>{clearPrivateView();setMyVisits(false);startVisit(directory.find(w=>w.id===v.workshop)??null,v);}}/>
 </>;
}
