"use client";
import Link from "next/link";
import {useState,useEffect,useRef,useId,type FormEvent} from "react";
import {CarFront,ShieldCheck,FileCheck2,Upload,Check,MessageCircle,Phone,Copy,Star,Share2,Wrench,MapPin,Globe,LoaderCircle,Trash2} from "lucide-react";
import {ModalContent,ModalBody} from "@/components/modal-shell";
import {Dialog,DialogClose,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {Checkbox} from "@/components/ui/checkbox";
import {Progress} from "@/components/ui/progress";
import {Tabs,TabsList,TabsTrigger,TabsContent} from "@/components/ui/tabs";
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogCancel,AlertDialogAction,AlertDialogFooter,AlertDialogHeader} from "@/components/ui/alert-dialog";
import {Picker} from "@/components/picker";
import {AccountStorageNotice,type AccountIdentity} from "@/components/account-storage-notice";
import {services,cities,brands,contactHref,type Workshop} from "@/lib/workshops";
export type SearchContext={brand:string;model:string;year:string;problem:string;service:string;city:string;additionalCity:string;radius:number;from:string;to:string};

const initial:SearchContext={brand:"Alle Marken",model:"",year:"",problem:"",service:services[0],city:cities[1],additionalCity:"",radius:0,from:"",to:""};
export function DetailSearch({open,onClose,onSearch}:{open:boolean;onClose:()=>void;onSearch:(c:SearchContext)=>void}){
 const searchFormId=useId();
 const [step,setStep]=useState(0),[ctx,setCtx]=useState(initial),[error,setError]=useState("");const change=(key:keyof SearchContext,value:string|number)=>{setCtx(c=>({...c,[key]:value}));setError("");};
 function submit(e:FormEvent){e.preventDefault();if(step===0){if(!ctx.model.trim()){setError("Bitte ergänze das Fahrzeugmodell.");return;}setStep(1);}else if(step===1){if(ctx.problem.trim().length<10){setError("Beschreibe das Problem oder die gewünschte Arbeit mit mindestens 10 Zeichen.");return;}setStep(2);}else{if(ctx.from&&ctx.to&&ctx.from>ctx.to){setError("Das Ende des Reisezeitraums muss nach dem Beginn liegen.");return;}let service=ctx.service;if(service===services[0]){const p=ctx.problem.toLowerCase();if(/brems|fahrwerk|feder|stoßdämpf/.test(p))service=services[3];else if(/motor|getriebe|kupplung/.test(p))service=services[4];else if(/lack|karosserie|delle/.test(p))service=services[5];else if(/reifen|klima/.test(p))service=services[6];else if(/wartung|öl|inspektion/.test(p))service=services[1];else if(/fehler|elektr|diagnos|leuchte/.test(p))service=services[2];}onSearch({...ctx,service});onClose();}}
 return <Dialog open={open} onOpenChange={v=>{if(!v)onClose();}}><ModalContent title="Suche mit Fahrzeug" description="Drei Schritte zur passenden Auswahl." footer={<>{step>0&&<button type="button" className="outline" onClick={()=>{setStep(s=>s-1);setError("");}}>Zurück</button>}<button className="primary" type="submit" form={searchFormId}>{step===2?"Werkstätten zeigen":"Weiter"}</button></>}><div className="wizard-labels">{["Fahrzeug","Arbeit","Ort & Reise"].map((s,i)=><span className={step===i?"current":""} key={s}>{i+1} · {s}</span>)}</div><Progress value={(step+1)/3*100} aria-label={`Schritt ${step+1} von 3`} className="h-1.5"/><form id={searchFormId} onSubmit={submit} className="journey-form">
 {step===0&&<><div className="field"><label>Fahrzeugmarke</label><Picker value={ctx.brand} onChange={v=>change("brand",v)} values={brands} label="Fahrzeugmarke"/></div><div className="form-grid"><label>Modell<input required maxLength={80} placeholder="z. B. Golf 7" value={ctx.model} onChange={e=>change("model",e.target.value)}/></label><label>Baujahr <span>(optional)</span><input type="number" min="1950" max={new Date().getFullYear()+1} placeholder="z. B. 2019" value={ctx.year} onChange={e=>change("year",e.target.value)}/></label></div><div className="note"><CarFront size={20}/><p>Marken und Leistungen laut Betriebsquelle. Keine Kennzeichen oder Fahrgestellnummer nötig.</p></div></>}
 {step===1&&<><label>Was soll gemacht werden?<textarea required minLength={10} maxLength={2000} rows={4} placeholder="z. B. Beim Bremsen vibriert das Lenkrad. Ich möchte die Ursache prüfen lassen." value={ctx.problem} onChange={e=>change("problem",e.target.value)}/></label><div className="field"><label>Leistungsbereich</label><Picker value={ctx.service} onChange={v=>change("service",v)} values={services} label="Leistungsbereich"/></div><p className="help">„Alle Leistungen“ nutzt passende Stichwörter. Das ist keine Diagnose.</p></>}
 {step===2&&<><div className="form-grid"><div className="field"><label>Dein Ort</label><Picker value={ctx.city} onChange={v=>change("city",v)} values={cities.slice(1)} label="Dein Ort"/></div><div className="field"><label>Weiterer Ort <span>(optional)</span></label><Picker value={ctx.additionalCity||"Kein weiterer Ort"} onChange={v=>change("additionalCity",v==="Kein weiterer Ort"?"":v)} values={["Kein weiterer Ort",...cities.slice(1).filter(c=>c!==ctx.city)]} label="Weiterer Ort"/></div></div><div className="field"><label>Umkreis um deinen Ort</label><Picker value={ctx.radius===0?"Nur im Ort":`${ctx.radius} km`} onChange={v=>change("radius",v==="Nur im Ort"?0:parseInt(v))} values={["Nur im Ort","25 km","50 km","100 km"]} label="Umkreis"/></div><p className="help">Luftlinie ab Stadtzentrum. Ohne genaue Betriebskoordinaten zählt dessen Stadtzentrum.</p><div className="form-grid"><label>Reisebeginn <span>(optional)</span><input type="date" value={ctx.from} onChange={e=>change("from",e.target.value)}/></label><label>Reiseende <span>(optional)</span><input type="date" min={ctx.from||undefined} value={ctx.to} onChange={e=>change("to",e.target.value)}/></label></div><p className="help">Reisezeitraum für das Gespräch – keine Terminbestätigung.</p></>}
 <div className="private-caption"><ShieldCheck size={16}/>Private Suche. Keine Ausschreibung, kein Auftrag.</div>{error&&<p role="alert" className="error">{error}</p>}</form></ModalContent></Dialog>;
}
export type Review={display_name:string;vehicle:string;service:string;date:string;rating:number;review:string};
export type Visit={id:string;workshop:string;workshop_name?:string;date:string;vehicle:string;service:string;evidence_type:string;evidence_note:string;status:string;moderator_note:string;display_name:string|null;rating:number|null;review:string|null;created_at:string;file_name:string|null;revision:number};
function LoginPrompt({returnTo,description}:{returnTo:string;description:string}){return <div className="login-prompt"><ShieldCheck size={27}/><p>{description}</p><a className="primary" href={`/anmelden?weiter=${encodeURIComponent(returnTo)}`}>Anmelden oder registrieren</a><p className="help">Suchen und Kontakt aufnehmen geht ohne Nachweis.</p></div>;}
export function Profile({workshop:w,onClose,onVisit,context}:{workshop:Workshop|null;onClose:()=>void;onVisit:(w:Workshop)=>void;context:SearchContext|null}){
 const [contact,setContact]=useState<"whatsapp"|"phone"|null>(null),[message,setMessage]=useState(""),[feedback,setFeedback]=useState(""),[reviews,setReviews]=useState<Review[]>([]),[reviewError,setReviewError]=useState(""),[reviewLoading,setReviewLoading]=useState(false);
 // eslint-disable-next-line react-hooks/set-state-in-effect -- Reset controlled profile state when its external selection changes.
 useEffect(()=>{setContact(null);setFeedback("");setReviews([]);setReviewError("");if(!w)return;setMessage(`Hallo, ich interessiere mich für eine Reparatur bei ${w.name}.${context?`\nFahrzeug: ${context.brand} ${context.model}${context.year?` (${context.year})`:""}\nGewünschte Arbeit: ${context.problem}${context.from||context.to?`\nReisezeitraum: ${context.from||"offen"} bis ${context.to||"offen"}`:""}`:""}\nKönnen wir die Arbeit und einen möglichen Termin direkt besprechen?`);const a=new AbortController();setReviewLoading(true);fetch(`/api/reviews?workshop=${encodeURIComponent(w.id)}`,{signal:a.signal}).then(async r=>{const d=await r.json() as {reviews:Review[];error?:string};if(!r.ok)throw Error(d.error);setReviews(d.reviews);}).catch(e=>{if(e.name!=="AbortError")setReviewError(e.message);}).finally(()=>{if(!a.signal.aborted)setReviewLoading(false);});return()=>a.abort();},[w?.id,context]);
 async function copy(text:string,success:string){try{await navigator.clipboard.writeText(text);setFeedback(success);}catch{setFeedback("Kopieren ist hier nicht verfügbar. Du kannst den Text manuell auswählen.");}}
 return <><Dialog open={!!w} onOpenChange={v=>{if(!v)onClose();}}><ModalContent className="profile-modal" header={w&&<div className="profile-head"><span className={`workshop-mark ${w.color}`}>{w.initials}<Wrench size={17}/></span><div><DialogTitle>{w.name}</DialogTitle><DialogDescription><MapPin size={14}/>{w.city}</DialogDescription></div></div>} footer={<><button className="outline" onClick={()=>void copy(`${window.location.origin}/?werkstatt=${encodeURIComponent(w?.id??"")}`,"Profillink kopiert.")}><Share2 size={16}/>Link kopieren</button><button className="primary" onClick={()=>{if(w){onClose();onVisit(w);}}}><FileCheck2 size={17}/>Besuch nachweisen</button></>}>{w&&<>
 <div className="profile-contact"><h3>Direkter Kontakt</h3><p>Arbeit, Kosten und Termin direkt klären.</p><div className="contact-row">{w.whatsapp&&<button className="primary" onClick={()=>{setFeedback("");setContact("whatsapp");}}><MessageCircle size={17}/>WhatsApp</button>}<button className={w.whatsapp?"outline":"primary"} onClick={()=>{setFeedback("");setContact("phone");}}><Phone size={17}/>Anrufen</button></div><p className="phone-number">{w.phone} <span>· {w.phoneNote||"Werkstattkontakt"}</span></p>{!w.whatsapp&&<p className="help">WhatsApp nicht bestätigt.</p>}</div>
  <details className="profile-about"><summary>Über den Betrieb</summary><p>{w.description}</p></details><div className="source-status"><FileCheck2 size={16}/><span>Quellenabgleich · {new Date(w.checkedAt+"T12:00:00").toLocaleDateString("de-DE")}</span></div><p className="help">Der Quellenabgleich ist keine unabhängige Qualitätsprüfung.</p>
 <div className="profile-grid"><div><h3>Marken laut Quelle</h3><div className="brand-tags">{w.brands.length?w.brands.map(b=><span key={b}>{b}</span>):<span>Markeneignung direkt klären</span>}</div></div><div><h3>Beratungssprache</h3><p className="languages"><Globe size={15}/>{w.languages.length?w.languages.join(" · "):"Direkt klären"}</p></div></div>
 <div><h3>Leistungen laut Quelle</h3><div className="service-grid">{w.serviceDetails.map(s=><span key={s}><Check size={15}/>{s}</span>)}</div></div>
 <div className="profile-location"><h3>Standort</h3><p><MapPin size={16}/>{w.address}</p><a className="text-action" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(w.lat!==null&&w.lng!==null?`${w.lat},${w.lng}`:`${w.name} ${w.address}`)}`} target="_blank" rel="noopener noreferrer">Standort auf Karte öffnen</a></div>

 <div className="profile-reviews"><div className="review-heading"><h3>Bewertungen</h3>{w.count>0&&<span className="demo-tag">{w.count} {w.count===1?"geprüfter Besuch":"geprüfte Besuche"}</span>}</div>{reviewLoading&&<p className="help" role="status">Erfahrungen werden geladen …</p>}{!reviewLoading&&!reviewError&&!reviews.length&&<div className="no-reviews"><ShieldCheck size={23}/><p>Noch keine Erfahrungen mit geprüftem Besuch.</p><span>Bewertungen sind erst nach geprüftem Besuch möglich.</span></div>}{reviews.map((r,i)=><article className="review" key={i}><div className="review-title"><strong>{r.display_name}</strong><span>{r.rating} / 5 <Star size={13} fill="currentColor"/></span></div><p className="review-meta">{r.vehicle} · {r.service} · {new Date(r.date+"T12:00:00").toLocaleDateString("de-DE")}</p><p className="review-text">{r.review}</p><span className="proof-badge"><ShieldCheck size={13}/>Besuchsnachweis geprüft</span></article>)}{reviewError&&<p className="error" role="status">{reviewError}</p>}</div>
 <div className="profile-sources"><h3>Offizielle Quellen</h3>{w.sources.map(s=><a key={s.url} href={s.url} target="_blank" rel="noopener noreferrer">{s.title}<span>{new URL(s.url).hostname}</span></a>)}</div>
 {feedback&&!contact&&<p className="help" role="status">{feedback}</p>}
 </>}</ModalContent></Dialog>
 <Dialog open={!!contact} onOpenChange={v=>{if(!v)setContact(null);}}><ModalContent title={contact==="whatsapp"?"Nachricht vorbereiten":"Werkstatt anrufen"} description="Direkter Kontakt. Kein Reparaturauftrag." footer={w&&<><button className="outline" onClick={()=>void copy(contact==="whatsapp"?message:w.phone,contact==="whatsapp"?"Nachricht kopiert.":"Telefonnummer kopiert.")}><Copy size={16}/>{contact==="whatsapp"?"Text kopieren":"Nummer kopieren"}</button><a className="primary" href={contactHref(w,contact==="whatsapp"?"whatsapp":"phone",message)!} target={contact==="whatsapp"?"_blank":undefined} rel={contact==="whatsapp"?"noopener noreferrer":undefined}>{contact==="whatsapp"?<MessageCircle size={18}/>:<Phone size={18}/>} {contact==="whatsapp"?"WhatsApp öffnen":"Telefon öffnen"}</a></>}>{w&&<>{contact==="whatsapp"?<><label className="message-label">Deine Nachricht<textarea rows={7} value={message} maxLength={3000} onChange={e=>setMessage(e.target.value)}/></label><p className="help">WhatsApp erhält Nummer und Text. Du sendest die Nachricht selbst.</p></>:<div className="call-box"><strong>{w.name}</strong><span>{w.phoneNote||"Werkstattkontakt"}</span><a href={contactHref(w,"phone")!} className="phone-display">{w.phone}</a></div>}{feedback&&<p className="help" role="status">{feedback}</p>}</>}<p className="help">Ein Klick belegt keine Nachricht und keinen Besuch.</p></ModalContent></Dialog></>;
}
export function VisitForm({open,onClose,workshop,directory,signedIn,account,existing}:{open:boolean;onClose:()=>void;workshop:Workshop|null;directory:Workshop[];signedIn:boolean;account:AccountIdentity|null;existing:Visit|null}){
 const visitFormId=useId();
 const consentCheckbox=useRef<HTMLButtonElement>(null),consentId=useId();const [consentError,setConsentError]=useState(false);
 const [wid,setWid]=useState(""),[kind,setKind]=useState("Rechnung"),[service,setService]=useState(services[1]),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[done,setDone]=useState(false),[id,setId]=useState(""),[vehicle,setVehicle]=useState(""),[date,setDate]=useState(""),[note,setNote]=useState("");
 // eslint-disable-next-line react-hooks/set-state-in-effect -- A fresh opening or replacement initializes this controlled form.
 useEffect(()=>{if(open){setWid(existing?.workshop??workshop?.id??directory[0]?.id??"");setKind(existing?.evidence_type??"Rechnung");setService(existing?.service??workshop?.services[0]??directory[0]?.services[0]??services[1]);setVehicle(existing?.vehicle??"");setDate(existing?.date??"");setNote(existing?.evidence_note??"");setDone(false);setError("");setConsent(false);setConsentError(false);setId(existing?.id??crypto.randomUUID());}},[open,workshop?.id,existing?.id]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!consent){setConsentError(true);consentCheckbox.current?.focus();return;}setBusy(true);setError("");const f=new FormData(e.currentTarget);f.set("id",id);f.set("workshop",wid);f.set("service",service);f.set("evidenceType",kind);f.set("revision",String(existing?.revision??0));try{const r=await fetch("/api/visits",{method:existing?"PUT":"POST",body:f});const d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error);setDone(true);}catch(e){setError(e instanceof Error?e.message:"Einreichen fehlgeschlagen. Bitte versuche es erneut.");}finally{setBusy(false);}}
 const returnTo=`/?nachweis=${encodeURIComponent(workshop?.id??directory[0]?.id??"neu")}`;
 return <Dialog open={open} onOpenChange={v=>{if(!v&&!busy)onClose();}}><ModalContent closeDisabled={busy} title={done?"Nachweis eingereicht":existing?"Nachweis ergänzen":"Besuch nachweisen"} description={done?"Prüfung ausstehend. Deine Unterlagen bleiben privat.":"Privater Beleg. Bewertung nach Prüfung."} footer={<><DialogClose asChild><button className="outline" disabled={busy}>{done?"Schließen":"Abbrechen"}</button></DialogClose>{signedIn&&done?<Link className="primary" href="/?besuche=1" prefetch={false}>Meine Besuche</Link>:signedIn&&directory.length>0?<button type="submit" form={visitFormId} disabled={busy} className="primary">{busy?<><LoaderCircle className="spin" size={17}/>Wird eingereicht …</>:"Nachweis einreichen"}</button>:null}</>}>{!signedIn?<LoginPrompt returnTo={returnTo} description="Melde dich an, um deinen Nachweis privat zu speichern."/>:done?<><AccountStorageNotice account={account}/><div className="success-icon"><FileCheck2 size={34}/></div><p>Nach der Prüfung kannst du unter „Meine Besuche“ bewerten.</p></>:!directory.length?<p className="help">Es ist noch keine veröffentlichte Werkstatt verfügbar.</p>:<form id={visitFormId} className="journey-form" onSubmit={submit}><AccountStorageNotice account={account}/>
 {existing?.moderator_note&&<div className="note"><FileCheck2 size={20}/><p>{existing.moderator_note}</p></div>}
 <div className="field"><label>Besuchte Werkstatt</label><Picker value={wid} onChange={setWid} values={directory.map(w=>w.id)} label="Besuchte Werkstatt" displayLabels={Object.fromEntries(directory.map(w=>[w.id,w.name]))}/></div>
 <div className="form-grid"><label>Besuchsdatum<input required name="date" type="date" value={date} max={new Date().toISOString().slice(0,10)} onChange={e=>setDate(e.target.value)}/></label><label>Fahrzeug<input required name="vehicle" minLength={3} maxLength={100} placeholder="z. B. Audi A4, 2018" value={vehicle} onChange={e=>setVehicle(e.target.value)}/></label></div>
 <div className="field"><label>Durchgeführte Arbeit</label><Picker value={service} onChange={setService} values={services.slice(1)} label="Durchgeführte Arbeit"/></div><div className="field"><label>Art des Nachweises</label><Picker value={kind} onChange={setKind} values={["Rechnung","Service- oder Arbeitsbeleg","Anderer Nachweis"]} label="Nachweisart"/></div>
 <label className="upload"><Upload size={21}/><strong>{existing?"Ergänzten Beleg auswählen":"Beleg auswählen"}</strong><span>PDF, JPG oder PNG · maximal 5 MB</span><input name="file" type="file" accept="application/pdf,image/jpeg,image/png" required={kind!=="Anderer Nachweis"}/></label>
 <label>{kind==="Anderer Nachweis"?"Beschreibe deinen anderen Nachweis":"Hinweise zum Beleg (optional)"}<textarea name="evidenceNote" rows={3} minLength={kind==="Anderer Nachweis"?40:undefined} required={kind==="Anderer Nachweis"} maxLength={3000} value={note} onChange={e=>setNote(e.target.value)} placeholder={kind==="Anderer Nachweis"?"Zum Beispiel datierte Reparaturfotos zusammen mit einem Nachrichtenverlauf. Erkläre den Bezug zu Arbeit und Werkstatt.":"Was hilft bei der Prüfung?"}/></label>
 <p className="help">Persönliche Daten darfst du schwärzen. Datum, Werkstatt und Arbeit müssen erkennbar bleiben. Eine Werkstattbestätigung ist nicht nötig.</p>
 <div className={`consent-block${consentError?" invalid":""}`}><label className="consent" htmlFor={consentId}><Checkbox id={consentId} ref={consentCheckbox} checked={consent} onCheckedChange={v=>{setConsent(v===true);if(v===true)setConsentError(false);}} aria-label="Besuch und private Prüfung bestätigen" aria-invalid={consentError} aria-describedby={consentError?`${consentId}-error`:`${consentId}-help`}/><span><strong>Besuch und private Prüfung bestätigen</strong><span>Ich war bei dieser Werkstatt und erlaube, dass mein Nachweis privat gespeichert und manuell geprüft wird.</span></span></label><p className="consent-help" id={`${consentId}-help`}>Der Beleg bleibt privat. Unter „Meine Besuche“ kannst du Besuch, Beleg und Bewertung löschen.</p>{consentError&&<p className="consent-error" id={`${consentId}-error`} role="alert">Bitte aktiviere die Checkbox „Besuch und private Prüfung bestätigen“ direkt darüber.</p>}</div>{error&&<p role="alert" className="error">{error}</p>}</form>}</ModalContent></Dialog>;
}
const statusLabels:Record<string,string>={pending:"Prüfung ausstehend",approved:"Besuch geprüft",needs_more:"Weiterer Nachweis nötig",published:"Bewertung veröffentlicht",deleting:"Löschung ausstehend"};
export function MyVisits({open,onClose,directory,signedIn,account=null,onResubmit,startWithModeration=false}:{open:boolean;onClose:()=>void;directory:Workshop[];signedIn:boolean;account?:AccountIdentity|null;onResubmit:(v:Visit)=>void;startWithModeration?:boolean}){
 const reviewFormId=useId();
 const [currentAccount,setCurrentAccount]=useState<AccountIdentity|null>(account);
 const [list,setList]=useState<Visit[]>([]),[moderator,setModerator]=useState(false),[tab,setTab]=useState("mine"),[busy,setBusy]=useState(false),[error,setError]=useState(""),[reviewVisit,setReviewVisit]=useState<Visit|null>(null),[deleteId,setDeleteId]=useState<string|null>(null),[rating,setRating]=useState("5"),[notes,setNotes]=useState<Record<string,string>>({}),[cursor,setCursor]=useState<string|null>(null);
 async function load(admin=false,append=false){setBusy(true);setError("");try{const r=await fetch(`/api/visits?${admin?"moderation=1&":""}${append&&cursor?`cursor=${encodeURIComponent(cursor)}`:""}`);const d=await r.json() as {visits:Visit[];moderator:boolean;account:AccountIdentity;nextCursor:string|null;error?:string};if(!r.ok)throw Error(d.error);setList(old=>append?[...old,...d.visits]:d.visits);setCursor(d.nextCursor);setModerator(d.moderator);setCurrentAccount(d.account);}catch(e){setError(e instanceof Error?e.message:"Laden fehlgeschlagen.");}finally{setBusy(false);}}
 // eslint-disable-next-line react-hooks/set-state-in-effect -- Opening the controlled dialog starts a remote account-data load.
 useEffect(()=>{if(open&&signedIn){setTab(startWithModeration?"moderation":"mine");void load(startWithModeration);}},[open,signedIn,startWithModeration]);
 async function mutate(body:object,method="PATCH"){setBusy(true);setError("");try{const r=await fetch("/api/visits",{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error);await load(tab==="moderation");return true;}catch(e){setError(e instanceof Error?e.message:"Speichern fehlgeschlagen.");return false;}finally{setBusy(false);}}
 async function review(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);if(await mutate({action:"review",id:reviewVisit!.id,name:f.get("name"),review:f.get("review"),rating:Number(rating)}))setReviewVisit(null);}
 return <><Dialog open={open} onOpenChange={v=>{if(!v&&!busy)onClose();}}><ModalContent className="visits-modal" closeDisabled={busy} title={startWithModeration?"Besuchsnachweise prüfen":"Meine Besuche"} description="Nachweise bleiben privat. Bewertungen brauchen einen geprüften Besuch." footer={<><DialogClose asChild><button className="outline" disabled={busy}>Schließen</button></DialogClose>{signedIn&&<button className="primary" disabled={busy} onClick={()=>void load(tab==="moderation")}>{busy?<><LoaderCircle className="spin" size={16}/>Wird geladen …</>:"Aktualisieren"}</button>}</>}>{!signedIn?<LoginPrompt returnTo="/?besuche=1" description="Melde dich an, um deine Besuche und ihren Prüfstatus zu sehen."/>:<><AccountStorageNotice account={currentAccount}/><Tabs value={tab} onValueChange={v=>{setTab(v);setList([]);void load(v==="moderation");}}><TabsList><TabsTrigger value="mine">Meine Nachweise</TabsTrigger>{moderator&&<TabsTrigger value="moderation">Besuche prüfen</TabsTrigger>}</TabsList><TabsContent value={tab}><div className="visit-list">{busy&&<p role="status"><LoaderCircle size={16} className="spin"/> Wird geladen …</p>}{!busy&&!error&&!list.length&&<div className="empty"><FileCheck2 size={25}/><h3>{tab==="moderation"?"Keine eingereichten Nachweise.":"Noch keine Nachweise."}</h3><p>Nach dem Besuch kannst du einen Nachweis einreichen.</p></div>}
 {list.map(v=><article className="visit" key={v.id}><div className="visit-top"><strong>{v.workshop_name??"Ehemaliges Pilotprofil"}</strong><span className={`visit-status ${v.status}`}>{statusLabels[v.status]??v.status}</span></div><p className="review-meta">{v.vehicle} · {v.date} · {v.service}</p><p className="help">Nachweis: {v.evidence_type}</p>{v.file_name&&<a className="text-action" href={`/api/evidence/${v.id}`}>Privaten Beleg herunterladen</a>}{v.evidence_note&&<p className="evidence-note">{v.evidence_note}</p>}{v.moderator_note&&<p className="note">Hinweis aus der Prüfung: {v.moderator_note}</p>}
 {tab==="mine"&&<div className="visit-actions">{v.status==="approved"&&directory.some(w=>w.id===v.workshop)&&<button className="primary small" disabled={busy} onClick={()=>{setReviewVisit(v);setRating("5");}}>Reparatur bewerten</button>}{v.status==="needs_more"&&directory.some(w=>w.id===v.workshop)&&<button className="outline small" disabled={busy} onClick={()=>onResubmit(v)}>Nachweis ergänzen</button>}{v.status==="published"&&<p className="help">{v.rating}/5 · {v.review}</p>}<button className="delete-button" disabled={busy} onClick={()=>setDeleteId(v.id)}><Trash2 size={14}/>Löschen</button></div>}
 {tab==="moderation"&&<div className="moderation-actions">{v.review&&<p className="review-text">Bewertung: {v.rating}/5 · {v.review}</p>}<label>Prüfvermerk<textarea rows={2} value={notes[v.id]??""} onChange={e=>setNotes({...notes,[v.id]:e.target.value})} placeholder="Welche Unterlagen belegen Werkstatt, Datum und Arbeit? Was fehlt?" maxLength={1000}/></label><p className="help">Ein Prüfvermerk ist erforderlich. Prüfe Datum, Betrieb, Arbeit und mögliche doppelte Einreichungen.</p><div className="contact-row">{["pending","needs_more"].includes(v.status)&&<button className="primary small" disabled={busy||(notes[v.id]??"").trim().length<10} onClick={()=>void mutate({action:"moderate",id:v.id,status:"approved",revision:v.revision,note:notes[v.id]??""})}>Besuch bestätigen</button>}<button className="outline small" disabled={busy||(notes[v.id]??"").trim().length<10} onClick={()=>void mutate({action:"moderate",id:v.id,status:"needs_more",revision:v.revision,note:notes[v.id]??""})}>{v.status==="published"?"Bewertung ausblenden & Nachweis anfordern":"Weiteren Nachweis anfordern"}</button></div></div>}
 </article>)}{cursor&&<button className="outline" disabled={busy} onClick={()=>void load(tab==="moderation",true)}>Weitere Besuche laden</button>}</div></TabsContent></Tabs>{error&&<p className="error" role="alert">{error}</p>}</>}</ModalContent></Dialog>
 <Dialog open={!!reviewVisit} onOpenChange={v=>{if(!v&&!busy)setReviewVisit(null);}}><ModalContent closeDisabled={busy} title="Deine Reparaturerfahrung" description="Beschreibe die durchgeführte Arbeit." footer={<><DialogClose asChild><button className="outline" disabled={busy}>Abbrechen</button></DialogClose><button className="primary" form={reviewFormId} type="submit" disabled={busy}>{busy?"Wird gespeichert …":"Bewertung veröffentlichen"}</button></>}><form id={reviewFormId} onSubmit={review} className="journey-form"><label>Öffentlicher Anzeigename<input required name="name" minLength={2} maxLength={40} placeholder="z. B. Arben K."/></label><div className="field"><label>Deine Bewertung</label><Picker value={rating} onChange={setRating} values={["1","2","3","4","5"]} label="Sterne von 1 bis 5"/></div><label>Wie war die Arbeit an deinem Fahrzeug?<textarea required name="review" minLength={30} maxLength={2000} rows={5} placeholder="Beschreibe Ergebnis, Kommunikation und was gut oder weniger gut lief. Bitte ohne persönliche Daten."/></label><p className="help">Anzeigename, Fahrzeug, Arbeit, Besuchsdatum, Sterne und Text werden im Profil angezeigt. Dein Beleg bleibt privat.</p>{error&&<p role="alert" className="error">{error}</p>}</form></ModalContent></Dialog>
 <AlertDialog open={!!deleteId} onOpenChange={v=>{if(!v&&!busy)setDeleteId(null);}}><AlertDialogContent className="app-dialog confirmation-dialog"><AlertDialogHeader><AlertDialogTitle>Nachweis löschen?</AlertDialogTitle></AlertDialogHeader><ModalBody><AlertDialogDescription>Der private Beleg, Besuchseintrag und eine zugehörige Bewertung werden dauerhaft entfernt.</AlertDialogDescription>{error&&<p className="error" role="alert">{error}</p>}</ModalBody><AlertDialogFooter><AlertDialogCancel disabled={busy}>Behalten</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={e=>{e.preventDefault();void mutate({id:deleteId},"DELETE").then(ok=>{if(ok)setDeleteId(null);});}}>{busy?"Wird gelöscht …":"Löschen"}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></>;
}
