"use client";
import Link from "next/link";
import {useState} from "react";
import {Wrench,ChevronDown,UserRound,FileCheck2,LayoutDashboard,LogOut,LoaderCircle,Search} from "lucide-react";
import {DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuLabel,DropdownMenuItem,DropdownMenuSeparator} from "@/components/ui/dropdown-menu";
import type {AccountIdentity} from "./account-storage-notice";

type Props={account:AccountIdentity|null;isAdmin?:boolean;onVisits?:()=>void;onNewVisit?:()=>void;section?:string};
export function SiteHeader({account,isAdmin=false,onVisits,onNewVisit,section}:Props){
 const [busy,setBusy]=useState(false),[error,setError]=useState("");
 const name=account?.displayName.trim()||account?.email||"";
 const initials=name.includes("@")?name.slice(0,2):name.split(/\s+/).map(part=>part[0]).slice(0,2).join("");
 async function logout(){setBusy(true);setError("");try{const r=await fetch("/api/auth/logout",{method:"POST",headers:{"Content-Type":"application/json"},body:"{}"});if(!r.ok)throw Error("Abmelden fehlgeschlagen. Bitte erneut versuchen.");window.location.assign("/anmelden");}catch(e){setBusy(false);setError(e instanceof Error?e.message:"Abmelden fehlgeschlagen.");}}
 return <div className="navbar"><header className="header wrap"><Link className="brand" href="/" aria-label="Mjeshtër Startseite"><span className="brandmark"><Wrench size={21}/></span>mjeshtër<span className="brandperiod">.</span></Link><nav aria-label="Hauptnavigation"><Link className="navactive" href={section?"/":"#suche"}><Search size={16}/> Werkstätten</Link>{section?<span className="nav-section">{section}</span>:<a className="nav-how" href="#so-gehts">So funktioniert’s</a>}</nav><div className="header-right">{account?<DropdownMenu><DropdownMenuTrigger className="user-menu-trigger" aria-label="Benutzermenü öffnen"><span className="user-avatar">{initials.toUpperCase()}</span><span className="user-menu-name">{name.includes("@")?"Mein Konto":name.split(" ")[0]}</span><ChevronDown size={16}/></DropdownMenuTrigger><DropdownMenuContent className="user-menu" align="end" sideOffset={10}><DropdownMenuLabel className="user-menu-identity"><strong>{name}</strong><span>{account.email}</span><small>{isAdmin?"Admin":`Angemeldet${account.provider?` · ${account.provider}`:""}`}</small></DropdownMenuLabel><DropdownMenuSeparator/>{onVisits?<DropdownMenuItem onSelect={onVisits}><UserRound/>Meine Besuche</DropdownMenuItem>:<DropdownMenuItem asChild><Link href="/?besuche=1" prefetch={false}><UserRound/>Meine Besuche</Link></DropdownMenuItem>}{onNewVisit?<DropdownMenuItem onSelect={onNewVisit}><FileCheck2/>Besuch nachweisen</DropdownMenuItem>:<DropdownMenuItem asChild><Link href="/?nachweis=neu" prefetch={false}><FileCheck2/>Besuch nachweisen</Link></DropdownMenuItem>}{isAdmin&&<><DropdownMenuSeparator/><DropdownMenuItem asChild><a href="/verwaltung"><LayoutDashboard/>Verwaltung</a></DropdownMenuItem></>}<DropdownMenuSeparator/>{account.provider==="E-Mail"?<DropdownMenuItem disabled={busy} onSelect={e=>{e.preventDefault();void logout();}}>{busy?<LoaderCircle className="spin"/>:<LogOut/>}{busy?"Wird abgemeldet …":"Abmelden"}</DropdownMenuItem>:<DropdownMenuItem asChild><a href="/signout-with-chatgpt?return_to=%2F" target="_top"><LogOut/>Abmelden</a></DropdownMenuItem>}</DropdownMenuContent></DropdownMenu>:<div className="header-auth"><a href="/anmelden">Anmelden</a><a className="primary small" href="/registrieren">Registrieren</a></div>}</div></header>{error&&<p className="header-error wrap" role="alert">{error}</p>}</div>;
}
