"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {ArrowLeft,Check,ChevronDown,Copy,FileCheck2,Globe,MapPin,MessageCircle,Phone,Share2,ShieldCheck,Star,Wrench} from "lucide-react";
import {SiteHeader} from "@/components/site-header";
import {ReviewForm} from "@/components/review-form";
import {ModalContent} from "@/components/modal-shell";
import {Dialog} from "@/components/ui/dialog";
import type {AccountIdentity} from "@/components/account-storage-notice";
import {MyVisits,VisitForm,type Review,type Visit} from "@/app/journeys";
import {contactHref,type Workshop} from "@/lib/workshops";
import {readSearchSession} from "@/lib/search-session";

type Props={workshop:Workshop;directory:Workshop[];reviews:Review[];reviewError:string;signedIn:boolean;account:AccountIdentity|null;isAdmin:boolean};
export default function WorkshopProfile({workshop:w,directory,reviews,reviewError,signedIn,account,isAdmin}:Props){
 const router=useRouter();const [reviewOpen,setReviewOpen]=useState(false),[reviewBusy,setReviewBusy]=useState(false),[myReviews,setMyReviews]=useState(false),[editing,setEditing]=useState<Visit|null>(null),[contact,setContact]=useState<"phone"|"whatsapp"|null>(null),[message,setMessage]=useState(""),[feedback,setFeedback]=useState(""),[backHref,setBackHref]=useState("/werkstaetten");
 const path=`/werkstatt/${encodeURIComponent(w.id)}`,mapHref=`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(w.lat!==null&&w.lng!==null?`${w.lat},${w.lng}`:`${w.name} ${w.address}`)}`;
 const hasDirectorySources=w.sources.some(source=>"kind" in source&&source.kind==="directory");
 // eslint-disable-next-line react-hooks/set-state-in-effect -- The return link uses only a validated public catalogue URL from browser memory.
 useEffect(()=>{const href=readSearchSession()?.catalogueHref;if(href?.startsWith("/werkstaetten"))setBackHref(href);},[]);
 // eslint-disable-next-line react-hooks/set-state-in-effect -- A login return may target the inline review section.
 useEffect(()=>{if(window.location.hash==="#bewerten"||new URLSearchParams(window.location.search).get("bewerten")==="1")setReviewOpen(true);},[]);
 function openReview(){setReviewOpen(true);requestAnimationFrame(()=>document.getElementById("bewerten")?.scrollIntoView({behavior:"smooth",block:"start"}));}
 function startContact(channel:"phone"|"whatsapp"){
  setFeedback("");const context=readSearchSession()?.context;
  setMessage(`Hallo, ich interessiere mich für eine Reparatur bei ${w.name}.${context?`\nFahrzeug: ${context.brand} ${context.model}${context.year?` (${context.year})`:""}\nGewünschte Arbeit: ${context.problem}${context.from||context.to?`\nReisezeitraum: ${context.from||"offen"} bis ${context.to||"offen"}`:""}`:""}\nKönnen wir die Arbeit und einen möglichen Termin besprechen?`);setContact(channel);
 }
 async function copy(value:string,label:string){try{await navigator.clipboard.writeText(value);setFeedback(label);}catch{setFeedback("Bitte wähle den Text aus und kopiere ihn manuell.");}}
 return <><SiteHeader account={account} isAdmin={isAdmin} section="Werkstattprofil" onVisits={()=>setMyReviews(true)} onNewVisit={openReview}/>
 <main className="workshop-page wrap">
  <Link className="profile-back" href={backHref}><ArrowLeft size={16}/>Zurück zur Suche</Link>
  <header className="workshop-overview"><div className="workshop-overview-identity"><span className={`workshop-mark ${w.color}`} aria-hidden="true">{w.initials}<Wrench size={18}/></span><div><p className="profile-place"><MapPin size={15}/>{w.city} · {w.specialty}</p><h1>{w.name}</h1><div className="profile-rating">{w.rating!==null?<><Star size={17} fill="currentColor"/><strong>{w.rating.toLocaleString("de-DE",{minimumFractionDigits:1,maximumFractionDigits:1})}</strong><span>{w.count} {w.count===1?"geprüfte Bewertung":"geprüfte Bewertungen"}</span></>:<><MessageCircle size={16}/><span>Noch keine geprüften Bewertungen</span></>}</div></div></div><div className="workshop-overview-actions"><button className="primary" onClick={()=>startContact("phone")}><Phone size={17}/>Anrufen</button>{w.whatsapp&&<button className="outline" onClick={()=>startContact("whatsapp")}><MessageCircle size={17}/>WhatsApp</button>}<button className="outline" onClick={openReview}><Star size={17}/>Bewerten</button></div></header>
  <nav className="profile-section-nav" aria-label="Profilbereiche"><a href="#leistungen">Leistungen</a><a href="#bewertungen">Bewertungen</a><a href="#standort">Standort</a><a href="#quellen">Quellen</a></nav>
  <div className="workshop-page-grid"><div className="workshop-page-main">
   <section className="profile-page-section" id="leistungen"><div className="profile-section-heading"><h2>Leistungen & Marken</h2><span><FileCheck2 size={15}/>Mit Quelle</span></div><p className="profile-description">{w.description}</p><ul className="profile-service-list">{w.serviceDetails.map(service=><li key={service}><Check size={16}/><span>{service}</span></li>)}</ul><div className="profile-facts"><div><h3>Veröffentlichte Marken</h3>{w.brands.length?<div className="brand-tags">{w.brands.map(brand=><span key={brand}>{brand}</span>)}</div>:<p>Markeneignung direkt klären.</p>}</div><div><h3>Beratungssprache</h3><p><Globe size={15}/>{w.languages.length?w.languages.join(" · "):"Nicht veröffentlicht – direkt klären."}</p></div></div><p className="profile-scope">Die Quellen beschreiben das Angebot des Betriebs. Eignung für dein Fahrzeug und freie Termine klärst du direkt.</p></section>
   <section className="profile-page-section" id="bewertungen"><div className="profile-section-heading"><h2>Reparaturerfahrungen</h2><button className="text-action" onClick={openReview}>Bewertung schreiben</button></div>{reviewError?<p className="error" role="alert">{reviewError}</p>:reviews.length?<div className="public-review-list">{reviews.map((review,index)=><article className="public-review" key={`${review.display_name}:${review.date}:${index}`}><div className="review-title"><strong>{review.display_name}</strong><span><Star size={14} fill="currentColor"/>{review.rating} / 5</span></div><p className="review-meta">{review.vehicle} · {review.service} · {new Date(review.date+"T12:00:00").toLocaleDateString("de-DE")}</p><p className="public-review-text">{review.review}</p><span className="proof-badge"><ShieldCheck size={13}/>Besuchsnachweis geprüft</span></article>)}{w.count>reviews.length&&<p className="help">Die neuesten {reviews.length} Bewertungen werden angezeigt.</p>}</div>:<div className="profile-review-empty"><ShieldCheck size={24}/><div><h3>Die erste Erfahrung zählt.</h3><p>Noch keine veröffentlichten Bewertungen mit geprüftem Besuch.</p></div></div>}
    <section className="inline-review" id="bewerten"><button type="button" className="inline-review-toggle" aria-expanded={reviewOpen} aria-controls="review-editor" disabled={reviewBusy} onClick={()=>setReviewOpen(value=>!value)}><span><Star size={19}/><strong>Deine Werkstatterfahrung</strong></span><ChevronDown size={19}/></button>{reviewOpen&&<div className="inline-review-body" id="review-editor"><p className="help">Bewertung und privaten Beleg gemeinsam einreichen. Nach Freigabe erscheint deine Erfahrung hier.</p><ReviewForm workshop={w} directory={directory} signedIn={signedIn} returnTo={`${path}#bewerten`} onBusyChange={setReviewBusy} onSubmitted={()=>router.refresh()}/></div>}</section>
   </section>
   <section className="profile-page-section" id="quellen"><div className="profile-section-heading"><h2>Quellen & Einordnung</h2></div><p className="profile-scope">Abgeglichen am {new Date(w.checkedAt+"T12:00:00").toLocaleDateString("de-DE")}. Der Quellenabgleich ist keine unabhängige Qualitätsprüfung.{hasDirectorySources&&" Einzelne Angaben stammen aus öffentlichen Branchenverzeichnissen."}</p><ul className="profile-source-list">{w.sources.map(source=><li key={source.url}><a href={source.url} target="_blank" rel="noopener noreferrer"><strong>{source.title}</strong><span>{new URL(source.url).hostname}</span></a></li>)}</ul></section>
  </div><aside className="workshop-page-aside"><section className="profile-contact-summary" id="standort"><h2>Kontakt & Standort</h2><p className="profile-address"><MapPin size={18}/><span>{w.address}</span></p><a className="text-action" href={mapHref} target="_blank" rel="noopener noreferrer">Standort auf Karte öffnen</a><div className="profile-phone-summary"><strong>{w.phone}</strong><span>{w.phoneNote||"Werkstattkontakt"}</span></div><button className="primary" onClick={()=>startContact("phone")}><Phone size={17}/>Kontakt aufnehmen</button>{!w.whatsapp&&<p className="help">WhatsApp ist in den Quellen nicht bestätigt.</p>}<p className="profile-scope">Arbeit, Kosten und Termin persönlich vereinbaren. Ein Klick belegt keinen Besuch.</p></section><button className="profile-share" onClick={()=>void copy(`${window.location.origin}${path}`,"Profillink kopiert.")}><Share2 size={16}/>Profil teilen</button>{feedback&&!contact&&<p className="help" role="status">{feedback}</p>}</aside></div>
 </main>
 <Dialog open={!!contact} onOpenChange={value=>{if(!value)setContact(null);}}><ModalContent title={contact==="whatsapp"?"Nachricht vorbereiten":"Werkstatt anrufen"} description="Direkter Kontakt. Kein Reparaturauftrag." footer={<><button className="outline" onClick={()=>void copy(contact==="whatsapp"?message:w.phone,contact==="whatsapp"?"Nachricht kopiert.":"Telefonnummer kopiert.")}><Copy size={16}/>{contact==="whatsapp"?"Text kopieren":"Nummer kopieren"}</button><a className="primary" href={contactHref(w,contact==="whatsapp"?"whatsapp":"phone",message)??undefined} target={contact==="whatsapp"?"_blank":undefined} rel={contact==="whatsapp"?"noopener noreferrer":undefined}>{contact==="whatsapp"?<MessageCircle size={18}/>:<Phone size={18}/>} {contact==="whatsapp"?"WhatsApp öffnen":"Telefon öffnen"}</a></>}>
  {contact==="whatsapp"?<><label className="message-label">Deine Nachricht<textarea rows={5} value={message} maxLength={3000} onChange={e=>setMessage(e.target.value)}/></label><p className="help">WhatsApp erhält Nummer und Text. Du sendest die Nachricht dort selbst.</p></>:<div className="call-box"><strong>{w.name}</strong><span>{w.phoneNote||"Werkstattkontakt"}</span><a href={contactHref(w,"phone")??undefined}>{w.phone}</a></div>}{feedback&&<p className="help" role="status">{feedback}</p>}<p className="help">Ein Kontaktklick bestätigt keine Nachricht und keinen Werkstattbesuch.</p>
 </ModalContent></Dialog>
 <MyVisits open={myReviews} onClose={()=>{setMyReviews(false);router.refresh();}} directory={directory} signedIn={signedIn} account={account} onResubmit={visit=>{setMyReviews(false);setEditing(visit);}}/>
 <VisitForm open={!!editing} existing={editing} workshop={directory.find(workshop=>workshop.id===editing?.workshop)??null} directory={directory} signedIn={signedIn} account={account} onClose={()=>{setEditing(null);router.refresh();}} onDone={()=>setMyReviews(true)}/>
 </>;
}
