export const services = ["Alle Leistungen", "Inspektion & Wartung", "Diagnose & Elektronik", "Bremsen & Fahrwerk", "Motor & Getriebe", "Karosserie & Lack", "Reifen & Klima"];
export const cities = ["Ganz Kosovo", "Prishtina", "Prizren", "Peja", "Gjakova", "Ferizaj", "Mitrovica"];
export type Workshop = { id:string; name:string; city:string; brands:string[]; services:string[]; languages:string[]; rating:number; count:number; initials:string; color:string; specialty:string; description:string; lat:number; lng:number; experience:{name:string;car:string;work:string;date:string;rating:number;text:string;proof:string}[] };
export const workshops: Workshop[] = [
{id:"prishtina",name:"Auto Service Dardania",city:"Prishtina",brands:["Volkswagen","Audi","Škoda"],services:["Inspektion & Wartung","Diagnose & Elektronik","Bremsen & Fahrwerk"],languages:["Albanisch","Deutsch"],rating:4.8,count:24,initials:"AD",color:"green",specialty:"VAG-Spezialist",lat:42.6629,lng:21.1655,description:"Ein Beispielprofil für Wartung und elektronische Diagnose an Fahrzeugen der Volkswagen-Gruppe.",experience:[{name:"Arben K.",car:"Audi A4 · 2018",work:"Diagnose & Elektronik",date:"August 2026",rating:5,text:"Der Fehler wurde zuerst erklärt, dann behoben. Ich konnte nachvollziehen, welche Teile gewechselt wurden. Auch die Kommunikation auf Deutsch war unkompliziert.",proof:"Rechnung geprüft"},{name:"Liridona M.",car:"VW Golf · 2020",work:"Inspektion & Wartung",date:"Juli 2026",rating:4,text:"Saubere Arbeit und eine verständliche Erklärung zur Wartung. Die Abholung hat einen Tag länger gedauert als zunächst besprochen.",proof:"Servicebeleg geprüft"}]},
{id:"prizren",name:"Servis Auto Lumbardhi",city:"Prizren",brands:["Mercedes-Benz","BMW","Volkswagen"],services:["Motor & Getriebe","Inspektion & Wartung","Bremsen & Fahrwerk"],languages:["Albanisch","Deutsch"],rating:4.9,count:18,initials:"AL",color:"blue",specialty:"Motor & Getriebe",lat:42.2153,lng:20.7415,description:"Ein Beispiel für eine Werkstatt mit Schwerpunkt auf Motor und Getriebe.",experience:[{name:"Blerim S.",car:"Mercedes C-Klasse · 2017",work:"Motor & Getriebe",date:"August 2026",rating:5,text:"Das Getriebeproblem wurde verständlich eingegrenzt. Nach der Reparatur haben wir eine gemeinsame Probefahrt gemacht.",proof:"Rechnung geprüft"}]},
{id:"peja",name:"Garage Dukagjini",city:"Peja",brands:["BMW","MINI","Mercedes-Benz"],services:["Bremsen & Fahrwerk","Diagnose & Elektronik","Inspektion & Wartung","Reifen & Klima"],languages:["Albanisch","Englisch"],rating:4.7,count:16,initials:"GD",color:"orange",specialty:"Bremsen & Fahrwerk",lat:42.6591,lng:20.2883,description:"Ein Beispielprofil für Diagnose, Fahrwerk und Wartung im Westen Kosovos.",experience:[{name:"Drita H.",car:"BMW 3er · 2019",work:"Bremsen & Fahrwerk",date:"Juli 2026",rating:5,text:"Die alten Teile wurden mir gezeigt und die neue Bremse erklärt. Der vereinbarte Termin wurde eingehalten.",proof:"Arbeitsbeleg geprüft"}]},
{id:"ferizaj",name:"Auto Teknik Ferizaj",city:"Ferizaj",brands:["Volkswagen","Audi","BMW"],services:["Diagnose & Elektronik","Reifen & Klima","Inspektion & Wartung"],languages:["Albanisch","Deutsch"],rating:4.6,count:12,initials:"AT",color:"purple",specialty:"Elektronik & Klima",lat:42.3702,lng:21.1483,description:"Ein Beispiel für elektronische Fehlersuche und Klimaservice.",experience:[]},
{id:"gjakova",name:"Karoseri Gjakova",city:"Gjakova",brands:["Alle Marken"],services:["Karosserie & Lack"],languages:["Albanisch","Englisch"],rating:4.8,count:9,initials:"KG",color:"blue",specialty:"Karosserie & Lack",lat:42.3803,lng:20.4308,description:"Ein Beispielprofil für Karosserie- und Lackierarbeiten.",experience:[]},
{id:"mitrovica",name:"Servis Trepça",city:"Mitrovica",brands:["Volkswagen","Škoda","Opel"],services:["Reifen & Klima","Bremsen & Fahrwerk","Inspektion & Wartung"],languages:["Albanisch"],rating:4.5,count:11,initials:"ST",color:"green",specialty:"Wartung & Reifen",lat:42.8914,lng:20.866,description:"Ein Beispiel für Wartung, Reifen und Fahrwerk im Norden Kosovos.",experience:[]}
];
const coordinates: Record<string,[number,number]>={Prishtina:[42.6629,21.1655],Prizren:[42.2153,20.7415],Peja:[42.6591,20.2883],Gjakova:[42.3803,20.4308],Ferizaj:[42.3702,21.1483],Mitrovica:[42.8914,20.866]};
export function distance(w:Workshop,city:string){const c=coordinates[city];if(!c)return 0;const rad=Math.PI/180;const a=Math.sin((w.lat-c[0])*rad/2)**2+Math.cos(c[0]*rad)*Math.cos(w.lat*rad)*Math.sin((w.lng-c[1])*rad/2)**2;return Math.round(6371*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a)));}
export function findWorkshops(service:string,city:string,brand="Alle Marken",radius=0,language="Alle Sprachen",additionalCity=""){return workshops.filter(w=>(service===services[0]||w.services.includes(service))&&(city===cities[0]||w.city===city||(additionalCity&&w.city===additionalCity)||(radius>0&&distance(w,city)<=radius))&&(brand==="Alle Marken"||w.brands.includes("Alle Marken")||w.brands.includes(brand))&&(language==="Alle Sprachen"||w.languages.includes(language)));}
