export const services = ["Alle Leistungen", "Inspektion & Wartung", "Diagnose & Elektronik", "Bremsen & Fahrwerk", "Motor & Getriebe", "Karosserie & Lack", "Reifen & Klima"];
export const cities = ["Ganz Kosovo", "Prishtina", "Prizren", "Peja", "Gjakova", "Ferizaj", "Mitrovica", "Fushë Kosovë", "Graçanicë", "Klinë", "Viti", "Gjilan", "Deçan", "Istog", "Skenderaj"];
export const brands = ["Alle Marken","Volkswagen","Audi","SEAT","CUPRA","Volkswagen Nutzfahrzeuge","Volvo","Porsche","BMW","Mercedes-Benz","Škoda","MINI","Opel","Renault","Dacia","Nissan","Toyota","Ford","Peugeot","Citroën","Hyundai","Kia","Fiat","Honda","Suzuki","Isuzu","BYD","Ferrari","Lamborghini","Land Rover","Range Rover"];
export type Source = {url:string;title:string;kind?:"official"|"directory"};
export type GoogleRating = {rating:number|null;count:number|null;mapsUrl:string;sourceUrl:string|null;sourceLabel:string|null;checkedAt:string;sourceUpdatedAt:string|null};
export type Workshop = {id:string;name:string;city:string;address:string;phone:string;phoneNote:string;whatsapp:string;brands:string[];services:string[];serviceDetails:string[];languages:string[];rating:number|null;count:number;googleRating?:GoogleRating|null;initials:string;color:string;specialty:string;description:string;lat:number|null;lng:number|null;sources:Source[];checkedAt:string;status:"draft"|"published";updatedAt:string};
export const cityCoordinates: Record<string,[number,number]>={Prishtina:[42.6629,21.1655],Prizren:[42.2153,20.7415],Peja:[42.6591,20.2883],Gjakova:[42.3803,20.4308],Ferizaj:[42.3702,21.1483],Mitrovica:[42.8914,20.866],"Fushë Kosovë":[42.663944,21.096111],"Graçanicë":[42.601111,21.195833],"Klinë":[42.621667,20.577778],"Viti":[42.321389,21.358333],"Gjilan":[42.46045,21.46986],"Deçan":[42.54018,20.28793],"Istog":[42.78083,20.4875]};
export function distance(w:Workshop,city:string){const c=cityCoordinates[city],p=w.lat!==null&&w.lng!==null?[w.lat,w.lng]:cityCoordinates[w.city];if(!c||!p)return Infinity;const rad=Math.PI/180;const a=Math.sin((p[0]-c[0])*rad/2)**2+Math.cos(c[0]*rad)*Math.cos(p[0]*rad)*Math.sin((p[1]-c[1])*rad/2)**2;return Math.round(6371*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a)));}
export function findWorkshops(directory:Workshop[],service:string,city:string,brand="Alle Marken",radius=0,language="Alle Sprachen",additionalCity=""){return directory.filter(w=>(service===services[0]||w.services.includes(service))&&(city===cities[0]||w.city===city||(additionalCity&&w.city===additionalCity)||(radius>0&&distance(w,city)<=radius))&&(brand==="Alle Marken"||w.brands.includes("Alle Marken")||w.brands.includes(brand)||w.brands.length===0)&&(language==="Alle Sprachen"||w.languages.includes(language)));}
export function contactHref(w:Workshop,channel:"phone"|"whatsapp",message=""){if(channel==="phone")return w.phone?`tel:${w.phone}`:null;return w.whatsapp?`https://wa.me/${w.whatsapp.replace(/\D/g,"")}?text=${encodeURIComponent(message)}`:null;}
