import { storage } from "./storage";
import curated from "@/data/initial-workshops.json";
import {services,cities,type Workshop,type Source} from "@/lib/workshops";
export const profileColumns=["id","name","city","address","phone","phone_note","whatsapp","brands","services","service_details","languages","specialty","description","lat","lng","sources","checked_at","status","updated_at"];
export type ProfileInput=Omit<Workshop,"initials"|"color"|"rating"|"count">;
function parseArray<T>(value:unknown):T[]{if(typeof value!=="string")return [];try{const a=JSON.parse(value);return Array.isArray(a)?a:[];}catch{return [];}}
export function decodeProfile(row:Record<string,unknown>):Workshop{return {id:String(row.id),name:String(row.name),city:String(row.city),address:String(row.address),phone:String(row.phone),phoneNote:String(row.phone_note??""),whatsapp:String(row.whatsapp??""),brands:parseArray<string>(row.brands),services:parseArray<string>(row.services),serviceDetails:parseArray<string>(row.service_details),languages:parseArray<string>(row.languages),specialty:String(row.specialty),description:String(row.description),lat:row.lat===null?null:Number(row.lat),lng:row.lng===null?null:Number(row.lng),sources:parseArray<Source>(row.sources),checkedAt:String(row.checked_at),status:row.status==="published"?"published":"draft",updatedAt:String(row.updated_at),initials:String(row.name).split(/\s+/).filter(Boolean).slice(0,2).map(s=>s[0]).join("").toUpperCase(),color:["green","blue","orange","purple"][String(row.id).length%4],rating:row.rating===null||row.rating===undefined?null:Number(row.rating),count:Number(row.count??0)};}
export function profileValues(w:ProfileInput){return [w.id,w.name,w.city,w.address,w.phone,w.phoneNote,w.whatsapp,JSON.stringify(w.brands),JSON.stringify(w.services),JSON.stringify(w.serviceDetails),JSON.stringify(w.languages),w.specialty,w.description,w.lat===null?null:String(w.lat),w.lng===null?null:String(w.lng),JSON.stringify(w.sources),w.checkedAt,w.status,w.updatedAt];}
const insertSql=`INSERT OR IGNORE INTO workshops (${profileColumns.join(",")}) VALUES (${profileColumns.map(()=>"?").join(",")})`;
// Curated source data is seeded separately from schema migrations, once per catalog version.
export async function ensureInitialCatalog(){const {db}=storage();if(!curated.length)return;const marker=await db.prepare("SELECT value FROM catalog_state WHERE key='initial-catalog-v1'").first();if(marker)return;const statements=(curated as ProfileInput[]).map(w=>db.prepare(insertSql).bind(...profileValues(w)));statements.push(db.prepare("INSERT OR IGNORE INTO catalog_state (key,value) VALUES ('initial-catalog-v1',?)").bind(new Date().toISOString()));await db.batch(statements);}
export async function listWorkshops(includeDrafts=false){await ensureInitialCatalog();const {db}=storage();const result=await db.prepare(`SELECT w.*, ROUND(AVG(v.rating),1) AS rating, COUNT(v.id) AS count FROM workshops w LEFT JOIN visits v ON v.workshop=w.id AND v.status='published' ${includeDrafts?"":"WHERE w.status='published'"} GROUP BY w.id ORDER BY w.name COLLATE NOCASE`).all<Record<string,unknown>>();return result.results.map(decodeProfile);}
export async function publishedWorkshop(id:string){await ensureInitialCatalog();return storage().db.prepare("SELECT id FROM workshops WHERE id=? AND status='published'").bind(id).first();}
export function validateProfile(body:Record<string,unknown>,id:string):ProfileInput{
 const text=(key:string,max:number)=>String(body[key]??"").trim().slice(0,max),arrays=(key:string,max=30)=>Array.isArray(body[key])?[...new Set((body[key] as unknown[]).map(String).map(v=>v.trim().slice(0,200)).filter(Boolean))].slice(0,max):[];
 const name=text("name",120),city=text("city",80),address=text("address",250),phone=text("phone",30).replace(/[ ()-]/g,""),whatsapp=text("whatsapp",30).replace(/[ ()-]/g,"");const brandList=arrays("brands"),serviceList=arrays("services"),serviceDetails=arrays("serviceDetails"),languages=arrays("languages",8),description=text("description",2000),specialty=text("specialty",100),checkedAt=text("checkedAt",10),status=body.status==="published"?"published":"draft";
 const inputSources=Array.isArray(body.sources)?body.sources:[];const sources:Source[]=inputSources.slice(0,8).map(item=>{if(!item||typeof item!=="object")throw Error("Bitte ergänze gültige Quellen.");const r=item as Record<string,unknown>;const u=new URL(String(r.url));if(u.protocol!=="https:"||u.username||u.password)throw Error("Quellen müssen HTTPS-Links ohne Zugangsdaten sein.");return {url:u.href,title:String(r.title??u.hostname).slice(0,150)};});
 const today=new Date().toISOString().slice(0,10);if(name.length<3||!cities.slice(1).includes(city)||address.length<5||!/^\+[1-9]\d{7,14}$/.test(phone)||!serviceList.length||!serviceDetails.length||serviceList.some(v=>!services.slice(1).includes(v))||description.length<20||specialty.length<3||!/^\d{4}-\d{2}-\d{2}$/.test(checkedAt)||!Number.isFinite(Date.parse(checkedAt))||new Date(checkedAt).toISOString().slice(0,10)!==checkedAt||checkedAt>today)throw Error("Bitte prüfe Name, Ort, Adresse, Telefonnummer, Marke, Leistungen, Beschreibung und Prüfdatum.");
 if(whatsapp&&!/^\+[1-9]\d{7,14}$/.test(whatsapp))throw Error("Bitte ergänze WhatsApp als internationale Telefonnummer oder lasse das Feld leer.");if(status==="published"&&!sources.length)throw Error("Ein veröffentlichtes Profil braucht mindestens eine nachvollziehbare Quelle.");
 const lat=body.lat===null||body.lat===undefined||body.lat===""?null:Number(body.lat),lng=body.lng===null||body.lng===undefined||body.lng===""?null:Number(body.lng);if((lat===null)!==(lng===null)||(lat!==null&&(!Number.isFinite(lat)||lat<41.8||lat>43.3||!Number.isFinite(lng)||lng!<19.8||lng!>21.9)))throw Error("Bitte ergänze gültige Koordinaten in Kosovo oder lasse beide Felder leer.");
 return {id,name,city,address,phone,phoneNote:text("phoneNote",150),whatsapp,brands:brandList,services:serviceList,serviceDetails,languages,specialty,description,lat,lng,sources,checkedAt,status,updatedAt:new Date().toISOString()};
}
