import {getAppUser,getAdminUser,ownsVisit,ownerPair} from "@/app/auth";
import {storage,moderatorEmail,cleanupVisitEvidence} from "@/db/storage";
import {publishedWorkshop} from "@/db/directory";
import {services} from "@/lib/workshops";
import {json,sameOrigin,readJson,validDate} from "@/lib/http";
export const dynamic="force-dynamic";
const failure=()=>json({error:"Der Nachweis konnte gerade nicht verarbeitet werden. Deine Eingaben bleiben erhalten. Bitte versuche es erneut."},503);
const fields="v.id, v.workshop, v.date, v.vehicle, v.service, v.evidence_type, v.evidence_note, v.status, v.moderator_note, v.display_name, v.rating, v.review, v.created_at, v.file_name, v.revision, w.name AS workshop_name";
export async function GET(request:Request){const params=new URL(request.url).searchParams,admin=params.get("moderation")==="1",user=admin?await getAdminUser():await getAppUser();if(!user)return json({error:"Bitte melde dich an, um deine Nachweise zu sehen."},401);try{const {db}=storage(),moderator=!!(await getAdminUser(user))?.isModerator;if(admin&&!moderator)return json({error:"Kein Zugriff auf die Prüfung."},403);const where=admin?[]:["v.owner IN (?,?)"],bindings:(string|number)[]=admin?[]:ownerPair(user);const cursor=params.get("cursor");if(cursor){if(cursor.length>512)return json({error:"Ungültige Seitenangabe."},400);let c;try{c=JSON.parse(atob(cursor));}catch{return json({error:"Ungültige Seitenangabe."},400);}if(typeof c.date!=="string"||typeof c.id!=="string"||c.date.length>30||! /^[0-9a-f-]{36}$/.test(c.id))return json({error:"Ungültige Seitenangabe."},400);where.push("(v.created_at<? OR (v.created_at=? AND v.id<?))");bindings.push(c.date,c.date,c.id);}const r=await db.prepare(`SELECT ${fields} FROM visits v LEFT JOIN workshops w ON w.id=v.workshop ${where.length?`WHERE ${where.join(" AND ")}`:""} ORDER BY v.created_at DESC,v.id DESC LIMIT 51`).bind(...bindings).all<Record<string,unknown>>();const items=r.results.slice(0,50),last=items.at(-1),nextCursor=r.results.length>50&&last?btoa(JSON.stringify({date:last.created_at,id:last.id})):null;const pending=admin?await db.prepare("SELECT COUNT(*) AS count FROM visits WHERE status='pending'").first<{count:number}>():null;return json({visits:items,nextCursor,pendingCount:pending?.count,moderator,account:{email:user.email,displayName:user.displayName,provider:user.provider}});}catch(e){console.error("visits-read",e);return failure();}}
export async function POST(request:Request){return submitEvidence(request,false);}
export async function PUT(request:Request){return submitEvidence(request,true);}
async function submitEvidence(request:Request,replacing:boolean){const user=await getAppUser();if(!user)return json({error:"Bitte melde dich an, bevor du einen Nachweis einreichst."},401);if(!sameOrigin(request))return json({error:"Ungültige Anfrage."},403);if(Number(request.headers.get("content-length")??0)>6*1024*1024)return json({error:"Die Datei ist zu groß. Maximal 5 MB."},413);let key:string|null=null;
 try{const {db,bucket}=storage(),f=await request.formData(),str=(key:string,max=100)=>String(f.get(key)??"").trim().slice(0,max);const id=str("id"),workshop=str("workshop"),date=str("date"),vehicle=str("vehicle"),service=str("service"),evidenceType=str("evidenceType"),evidenceNote=str("evidenceNote",3000);
 if(!/^[0-9a-f-]{36}$/.test(id)||!validDate(date)||date>new Date().toISOString().slice(0,10)||vehicle.length<3||!services.slice(1).includes(service)||!["Rechnung","Service- oder Arbeitsbeleg","Anderer Nachweis"].includes(evidenceType))return json({error:"Bitte prüfe Werkstatt, Besuchsdatum, Fahrzeug, Leistung und Nachweisart."},400);
 if(!(await publishedWorkshop(workshop)))return json({error:"Bitte wähle eine veröffentlichte Werkstatt."},400);
 const prior=await db.prepare("SELECT owner,status,file_key,revision FROM visits WHERE id=?").bind(id).first<{owner:string;status:string;file_key:string|null;revision:number}>();
 if(!replacing&&prior)return ownsVisit(user,prior.owner)?json({id,status:prior.status}):json({error:"Ungültige Kennung."},409);
 if(replacing&&(!prior||!ownsVisit(user,prior.owner)||prior.status!=="needs_more"||prior.revision!==Number(str("revision"))))return json({error:"Der Nachweis kann gerade nicht ergänzt werden. Bitte aktualisiere deine Besuche."},409);
 const recordOwner=prior?.owner??user.userId;const file=f.get("file");let fileName:string|null=null,fileType:string|null=null;
 if(file&&typeof file!=="string"&&file.size){if(file.size>5*1024*1024)return json({error:"Die Datei ist zu groß. Maximal 5 MB."},413);const bytes=await file.arrayBuffer(),b=new Uint8Array(bytes);const valid=(file.type==="application/pdf"&&String.fromCharCode(...b.slice(0,5))==="%PDF-")||(file.type==="image/jpeg"&&b[0]===255&&b[1]===216&&b[2]===255)||(file.type==="image/png"&&b[0]===137&&b[1]===80&&b[2]===78&&b[3]===71);if(!valid)return json({error:"Bitte lade eine gültige PDF-, JPG- oder PNG-Datei hoch."},400);key=`evidence/${recordOwner}/${id}/${crypto.randomUUID()}`;fileName=file.name.replace(/[^\p{L}\p{N}._ -]/gu,"_").slice(0,120);fileType=file.type;await bucket.put(key,bytes,{httpMetadata:{contentType:fileType}});}
 if(!key&&(evidenceType!=="Anderer Nachweis"||evidenceNote.length<40))return json({error:"Bitte lade einen Beleg hoch oder beschreibe einen anderen nachvollziehbaren Nachweis mit mindestens 40 Zeichen."},400);
 if(replacing){const r=await db.prepare("UPDATE visits SET workshop=?,date=?,vehicle=?,service=?,evidence_type=?,evidence_note=?,file_key=?,file_name=?,file_type=?,status='pending',revision=revision+1 WHERE id=? AND owner=? AND status='needs_more' AND revision=?").bind(workshop,date,vehicle,service,evidenceType,evidenceNote,key,fileName,fileType,id,recordOwner,prior!.revision).run();if(!r.meta.changes){if(key)await bucket.delete(key);return json({error:"Der Nachweis wurde zwischenzeitlich geändert. Bitte aktualisiere deine Besuche."},409);}try{await cleanupVisitEvidence(recordOwner,id,key);}catch(e){console.error("old-evidence-cleanup",e);}}
 else{await db.prepare("INSERT INTO visits (id,owner,workshop,date,vehicle,service,evidence_type,evidence_note,file_key,file_name,file_type,status,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,'pending',?)").bind(id,user.userId,workshop,date,vehicle,service,evidenceType,evidenceNote,key,fileName,fileType,new Date().toISOString()).run();}
 return json({id,status:"pending"},replacing?200:201);
 }catch(e){if(key){try{const referenced=await storage().db.prepare("SELECT id FROM visits WHERE file_key=?").bind(key).first();if(!referenced)await storage().bucket.delete(key);}catch{}}console.error("visit-submit",e);return failure();}}
export async function PATCH(request:Request){if(!sameOrigin(request))return json({error:"Ungültige Anfrage."},403);let body:Record<string,unknown>;try{body=await readJson(request);}catch{return json({error:"Ungültige Eingaben."},400);}const user=body.action==="moderate"?await getAdminUser():await getAppUser();if(!user)return json({error:"Bitte melde dich an."},401);try{const {db}=storage(),id=String(body.id??"");
 if(body.action==="moderate"){if(!user.isModerator)return json({error:"Kein Zugriff auf die Prüfung."},403);const status=String(body.status??""),note=String(body.note??"").trim().slice(0,1000);if(!["approved","needs_more"].includes(status)||note.length<10)return json({error:"Bitte ergänze einen Prüfvermerk mit mindestens 10 Zeichen."},400);const revision=Number(body.revision);if(!Number.isInteger(revision))return json({error:"Bitte aktualisiere die Prüfwarteschlange."},400);const allowed=status==="approved"?"('pending','needs_more')":"('pending','needs_more','approved','published')";const r=await db.prepare(`UPDATE visits SET status=?,moderator_note=?,moderated_at=?,moderated_by=?,revision=revision+1 WHERE id=? AND status IN ${allowed} AND revision=?`).bind(status,note,new Date().toISOString(),user.userId,id,revision).run();if(!r.meta.changes)return json({error:"Der Nachweis wurde zwischenzeitlich bearbeitet. Bitte aktualisiere die Liste."},409);return json({status});}
 if(body.action==="review"){const rating=Number(body.rating),review=String(body.review??"").trim(),name=String(body.name??"").trim();if(!Number.isInteger(rating)||rating<1||rating>5||review.length<30||review.length>2000||name.length<2||name.length>40)return json({error:"Bitte ergänze einen Anzeigenamen, 1–5 Sterne und mindestens 30 Zeichen zu deiner Reparatur."},400);const result=await db.prepare("UPDATE visits SET rating=?,review=?,display_name=?,status='published',revision=revision+1 WHERE id=? AND owner IN (?,?) AND status='approved' AND EXISTS (SELECT 1 FROM workshops WHERE workshops.id=visits.workshop AND workshops.status='published')").bind(rating,review,name,id,...ownerPair(user)).run();if(!result.meta.changes)return json({error:"Eine Bewertung ist erst nach geprüftem Besuch bei einer veröffentlichten Werkstatt möglich."},409);return json({status:"published"});}
 return json({error:"Ungültige Aktion."},400);
 }catch(e){console.error("visit-update",e);return failure();}}
export async function DELETE(request:Request){const user=await getAppUser();if(!user)return json({error:"Bitte melde dich an."},401);if(!sameOrigin(request))return json({error:"Ungültige Anfrage."},403);let body:Record<string,unknown>;try{body=await readJson(request);}catch{return json({error:"Ungültige Eingaben."},400);}try{const {db,bucket}=storage(),id=String(body.id??"");const v=await db.prepare("UPDATE visits SET status='deleting',revision=revision+1 WHERE id=? AND owner IN (?,?) RETURNING file_key,owner").bind(id,...ownerPair(user)).first<{file_key:string|null;owner:string}>();if(!v)return json({error:"Nachweis nicht gefunden."},404);await cleanupVisitEvidence(v.owner,id);await db.prepare("DELETE FROM visits WHERE id=? AND owner IN (?,?) AND status='deleting'").bind(id,...ownerPair(user)).run();return json({deleted:true});}catch(e){console.error("visit-delete",e);return failure();}}
