"use client";
import {useCallback,useEffect,useId,useRef,useState} from "react";
import {CarFront,Filter,LoaderCircle,RefreshCw,Search,X} from "lucide-react";
import {SiteHeader} from "@/components/site-header";
import {DirectoryFooter} from "@/components/directory-footer";
import {useDirectoryAccountActions} from "@/components/directory-account-actions";
import {CatalogueFilterFields} from "@/components/catalogue-filter-fields";
import {WorkshopCard} from "@/components/workshop-card";
import {Picker} from "@/components/picker";
import {Dialog,DialogTrigger} from "@/components/ui/dialog";
import {ModalContent} from "@/components/modal-shell";
import {DetailSearch,type SearchContext} from "@/app/journeys";
import {activeCatalogueFilters,catalogueHref,defaultCatalogueFilters,filterLabels,hasPublishedRatings,matchCatalogue,parseCatalogueFilters,type CatalogueFilters} from "@/lib/catalogue-filters";
import {readSearchSession,rememberSearchSession} from "@/lib/search-session";
import {cities,services,type Workshop} from "@/lib/workshops";
import type {AccountIdentity} from "@/components/account-storage-notice";

type Props={initialWorkshops:Workshop[];initialError:string;initialFilters:CatalogueFilters;signedIn:boolean;account:AccountIdentity|null;isAdmin:boolean};
function SortControl({id,filters,onChange,ratingAvailable}:{id:string;filters:CatalogueFilters;onChange:(sort:CatalogueFilters["sort"])=>void;ratingAvailable:boolean}){return <div className="catalogue-sort"><label htmlFor={id}>Sortieren</label><Picker id={id} value={filters.sort} onChange={value=>onChange(value as CatalogueFilters["sort"])} values={["name","rating"]} displayLabels={{name:"Name A–Z",rating:"Bewertung (höchste zuerst)"}} disabledValues={ratingAvailable?[]:["rating"]} label="Sortieren"/></div>;}

export default function Catalogue({initialWorkshops,initialError,initialFilters,signedIn,account,isAdmin}:Props){
 const [directory,setDirectory]=useState(initialWorkshops),[filters,setFilters]=useState(initialFilters),[draft,setDraft]=useState(initialFilters),[ready,setReady]=useState(!initialError),[error,setError]=useState(initialError),[refreshing,setRefreshing]=useState(false),[visibleCount,setVisibleCount]=useState(12),[context,setContext]=useState<SearchContext|null>(null),[privateMatchingActive,setPrivateMatchingActive]=useState(false),[hydrated,setHydrated]=useState(false),[filterOpen,setFilterOpen]=useState(false),[detailOpen,setDetailOpen]=useState(false);
 const filterButton=useRef<HTMLButtonElement>(null),resultsHeading=useRef<HTMLParagraphElement>(null),restoreScroll=useRef<number|null>(null),sortId=useId();
 const matches=matchCatalogue(directory,filters,context,privateMatchingActive),chips=activeCatalogueFilters(filters),ratingAvailable=hasPublishedRatings(directory),activeContext=privateMatchingActive&&context?.city===filters.city?context:null;
 const draftMatches=matchCatalogue(directory,draft,context,privateMatchingActive);
 const refresh=useCallback(async()=>{setRefreshing(true);setError("");try{const response=await fetch("/api/workshops"),data=await response.json() as {workshops:Workshop[];error?:string};if(!response.ok)throw Error(data.error);const records=data.workshops.filter(w=>w.status==="published");setDirectory(records);setFilters(parseCatalogueFilters(new URLSearchParams(window.location.search),records));setReady(true);}catch(e){setError(e instanceof Error?e.message:"Die Angaben konnten nicht aktualisiert werden.");}finally{setRefreshing(false);}},[]);
 const personal=useDirectoryAccountActions({directory,signedIn,account,onRefresh:()=>void refresh()});
 // eslint-disable-next-line react-hooks/set-state-in-effect -- Private context and paging are read only after hydration, never from server props.
 useEffect(()=>{const saved=readSearchSession();setFilters(initialFilters);setVisibleCount(12);if(saved){setContext(saved.context);setPrivateMatchingActive(saved.privateMatchingActive&&saved.context?.city===initialFilters.city);if(saved.catalogueHref===catalogueHref(initialFilters)){setVisibleCount(Math.max(12,saved.visibleCount));restoreScroll.current=saved.scrollY;}}setHydrated(true);},[initialFilters]);
 useEffect(()=>{if(!hydrated)return;const persist=()=>rememberSearchSession({...filters,searched:true,context,privateMatchingActive,catalogueHref:catalogueHref(filters),visibleCount,scrollY:window.scrollY});persist();window.addEventListener("scroll",persist,{passive:true});return()=>window.removeEventListener("scroll",persist);},[hydrated,filters,context,privateMatchingActive,visibleCount]);
 useEffect(()=>{if(!hydrated||restoreScroll.current===null)return;const y=restoreScroll.current;restoreScroll.current=null;const frame=requestAnimationFrame(()=>window.scrollTo({top:y,behavior:"auto"}));return()=>cancelAnimationFrame(frame);},[hydrated,visibleCount]);
 useEffect(()=>{if(!hydrated)return;const sync=()=>{const next=parseCatalogueFilters(new URLSearchParams(window.location.search),directory);setFilters(next);setVisibleCount(12);setPrivateMatchingActive(previous=>previous&&next.city===context?.city);};window.addEventListener("popstate",sync);return()=>window.removeEventListener("popstate",sync);},[hydrated,directory,context]);
 useEffect(()=>{if(hydrated&&ready)window.history.replaceState(window.history.state,"",catalogueHref(filters));},[hydrated,ready,filters]);
 useEffect(()=>{const mc=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>Promise<void>|void}}).modelContext;if(!mc?.registerTool)return;const lifecycle=new AbortController();void Promise.resolve(mc.registerTool({name:"configure_workshop_search",title:"Werkstattsuche einstellen",description:"Set service and city filters in the published Kosovo workshop catalogue. Does not contact a business, send a message, or book a repair.",inputSchema:{type:"object",properties:{service:{type:"string",enum:services},city:{type:"string",enum:cities}},required:["service","city"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},async execute(input:unknown){if(!ready)throw Error("Workshop directory is currently unavailable");if(!input||typeof input!=="object")throw Error("Expected search filters");const value=input as {service:string;city:string};if(!services.includes(value.service)||!cities.includes(value.city)||Object.keys(value).some(key=>!["service","city"].includes(key)))throw Error("Invalid service or city");const next={...defaultCatalogueFilters,service:value.service,city:value.city};setPrivateMatchingActive(false);setFilters(next);setVisibleCount(12);window.history.replaceState(window.history.state,"",catalogueHref(next));return {workshops:matchCatalogue(directory,next).map(w=>({id:w.id,name:w.name,city:w.city,reviewCount:w.count}))};}},{signal:lifecycle.signal})).catch(error=>console.warn("WebMCP registration",error));return()=>lifecycle.abort();},[directory,ready]);
 function commit(next:CatalogueFilters,resetPrivate=false){if(resetPrivate||next.city!==filters.city)setPrivateMatchingActive(false);setFilters(next);setVisibleCount(12);window.history.replaceState(window.history.state,"",catalogueHref(next));}
 function change(field:"service"|"city"|"brand"|"language",value:string){commit({...filters,[field]:value});}
 function reset(){commit({...defaultCatalogueFilters,sort:filters.sort},true);}
 function applyDraft(){commit(draft);setFilterOpen(false);requestAnimationFrame(()=>{filterButton.current?.focus({preventScroll:true});resultsHeading.current?.scrollIntoView({block:"start",behavior:"auto"});});}
 function applyContext(value:SearchContext){const next={...defaultCatalogueFilters,service:value.service,city:value.city,brand:value.brand,sort:filters.sort};setContext(value);setPrivateMatchingActive(true);setFilters(next);setVisibleCount(12);window.history.replaceState(window.history.state,"",catalogueHref(next));}

 return <><SiteHeader account={account} isAdmin={isAdmin} section="Werkstätten" onVisits={personal.onVisits} onNewVisit={personal.onNewVisit}/><main className="catalogue-page wrap">
  <header className="catalogue-heading"><div><h1>Werkstätten</h1><p>Leistungen vergleichen. Passende Profile ansehen. Direkt Kontakt aufnehmen.</p></div><button className="catalogue-detail-search" onClick={()=>setDetailOpen(true)}><CarFront size={18}/>Mit Fahrzeug & Problem suchen</button></header>
  {activeContext&&<div className="catalogue-private-context"><CarFront size={18}/><div><strong>Privater Suchkontext · {activeContext.brand} {activeContext.model}</strong><p>{activeContext.radius>0?`${activeContext.radius} km Umkreis · `:""}{activeContext.additionalCity?`${activeContext.additionalCity} · `:""}Fahrzeug und Problem bleiben nur in diesem Browserlauf.</p></div><button onClick={()=>setDetailOpen(true)}>Suchkontext ändern</button></div>}
  <section className="catalogue-desktop-filters" aria-label="Suche eingrenzen"><CatalogueFilterFields filters={filters} onChange={change} directory={directory}/><p className="catalogue-filter-help">Leistungen und Marken laut Profil. Fahrzeug und Termin direkt klären.</p></section>
  <div className="catalogue-mobile-toolbar"><Dialog open={filterOpen} onOpenChange={setFilterOpen}><DialogTrigger asChild><button className="outline catalogue-filter-button" ref={filterButton} onClick={()=>setDraft({...filters})}><Filter size={18}/>Filter{chips.length>0&&<span>{chips.length}</span>}</button></DialogTrigger><ModalContent className="catalogue-filter-dialog" title="Filter" description="Grenze die veröffentlichten Werkstätten ein." footer={<><button className="outline" onClick={()=>setDraft({...defaultCatalogueFilters,sort:filters.sort})}>Zurücksetzen</button><button className="primary" onClick={applyDraft}>Ergebnisse anzeigen{ready?` (${draftMatches.length})`:""}</button></>}><CatalogueFilterFields filters={draft} onChange={(field,value)=>setDraft(old=>({...old,[field]:value}))} directory={directory}/><p className="catalogue-filter-help">Genauen Leistungsumfang im Profil prüfen.</p>{ready&&draftMatches.length===0&&<p className="catalogue-draft-empty">Für diese Auswahl ist noch keine Werkstatt dabei. Ändere einen Filter oder setze die Auswahl zurück.</p>}</ModalContent></Dialog><SortControl id={`${sortId}-mobile`} filters={filters} onChange={sort=>commit({...filters,sort})} ratingAvailable={ratingAvailable}/></div>
  {chips.length>0&&<div className="catalogue-active-filters" aria-label="Aktive Filter">{chips.map(key=><button className="catalogue-filter-chip" key={key} aria-label={`${filterLabels[key]} ${filters[key]} entfernen`} onClick={()=>change(key,defaultCatalogueFilters[key])}><span>{filterLabels[key]}: {filters[key]}</span><X size={15}/></button>)}<button className="catalogue-reset" onClick={reset}>Alle Filter zurücksetzen</button></div>}
  {!ready?error?<div className="catalogue-load-error" role="alert"><h2>Werkstätten konnten nicht geladen werden.</h2><p>Bitte versuche es erneut.</p><button className="primary" disabled={refreshing} onClick={()=>void refresh()}><RefreshCw size={16}/>{refreshing?"Wird geladen …":"Erneut laden"}</button></div>:<div className="review-loading" role="status"><LoaderCircle size={18} className="spin"/>Werkstätten werden geladen …</div>:<>
   <div className="catalogue-results-toolbar"><p className="catalogue-result-count" ref={resultsHeading} role="status" aria-live="polite" aria-atomic="true">{matches.length} {matches.length===1?"Werkstatt":"Werkstätten"}</p><div className="catalogue-desktop-sort"><SortControl id={`${sortId}-desktop`} filters={filters} onChange={sort=>commit({...filters,sort})} ratingAvailable={ratingAvailable}/></div>{refreshing&&<span className="catalogue-refreshing" role="status"><LoaderCircle size={15} className="spin"/>Aktualisieren …</span>}</div>
   {error&&<div className="error catalogue-refresh-error" role="alert">Die Angaben konnten nicht aktualisiert werden. <button disabled={refreshing} onClick={()=>void refresh()}>Erneut laden</button></div>}
   {directory.length===0?<div className="empty catalogue-empty"><Search size={27}/><h2>Das Verzeichnis wird gerade ergänzt.</h2><p>Sobald veröffentlichte Profile vorliegen, erscheinen sie hier.</p></div>:matches.length===0?<div className="empty catalogue-empty"><Search size={27}/><h2>Für diese Auswahl ist noch keine Werkstatt dabei.</h2><p>{filters.language!==defaultCatalogueFilters.language?"Für diese Sprache fehlen veröffentlichte Angaben. Kläre die Sprache direkt oder entferne den Sprachfilter.":"Ändere einen Filter oder zeige alle Werkstätten."}</p><div>{filters.language!==defaultCatalogueFilters.language&&<button className="primary" onClick={()=>change("language",defaultCatalogueFilters.language)}>Sprachfilter entfernen</button>}<button className="outline" onClick={reset}>Alle Filter zurücksetzen</button></div></div>:<><div className="catalogue-grid">{matches.slice(0,visibleCount).map(workshop=><WorkshopCard key={workshop.id} workshop={workshop} selectedBrand={filters.brand}/>)}</div><div className="catalogue-pagination"><p>{Math.min(visibleCount,matches.length)} von {matches.length} angezeigt</p>{visibleCount<matches.length&&<button className="outline" onClick={()=>setVisibleCount(count=>count+12)}>Weitere Werkstätten anzeigen</button>}</div></>}
  </>}
 </main><DirectoryFooter/><DetailSearch open={detailOpen} onClose={()=>setDetailOpen(false)} onSearch={applyContext} initialContext={context}/>{personal.dialogs}</>;
}
